/*
 * mini_bowling.c -- REL module: isolated function lbl_0000B460.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "pool.h"
#include "rend_efc.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "pause_menu.h"
#include "string.h"
#include "avdisp.h"
#include "background.h"
#include "obj_collision.h"
#include "ord_tbl.h"
#include "stcoli.h"
#include "shadow.h"
#include "vibration.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_bowling.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000F020[];
extern u8 lbl_00010C40[];
extern u8 lbl_00010CC0[];
extern u8 lbl_00010CC8[];
extern u8 lbl_00010D58[];
extern u8 lbl_00010D60[];
extern u8 lbl_00010EE0[];
extern u8 lbl_00010EE8[];
extern u8 lbl_00010EF0[];
extern u8 lbl_00010F24[];
extern u8 lbl_00010F94[];
extern u8 lbl_00011250[];
extern u8 lbl_00011258[];
extern u8 lbl_000112C0[];
extern u8 lbl_000112C8[];
extern u8 lbl_00011338[];
extern u8 lbl_00011340[];
extern u8 lbl_00011490[];
extern u8 lbl_000146A0[];
extern u8 lbl_000147F8[];
extern u8 lbl_00014800[];
extern u8 lbl_00014B78[];
extern u8 lbl_00014BE8[];
extern u8 lbl_00014C00[];
extern u8 lbl_00014C08[];
extern u8 lbl_00014CB8[];
extern u8 lbl_00014D70[];
extern u8 lbl_00014D90[];
extern u8 lbl_00014E10[];
extern u8 lbl_00014F20[];
extern u8 lbl_00014F24[];
extern u8 lbl_00015020[];
extern u8 lbl_00015024[];
extern u8 lbl_00015040[];
extern u8 lbl_00015380[];
extern u8 lbl_00015388[];
extern u8 lbl_000153E0[];
extern u8 lbl_000153E4[];
extern u8 lbl_000153E8[];
extern u8 lbl_000153F4[];
extern u8 lbl_00015428[];
extern u8 lbl_00015434[];
extern u8 lbl_0001543C[];
extern u8 lbl_00015444[];
extern u8 lbl_00015454[];
extern u8 lbl_00015460[];
extern u8 lbl_0001546C[];
extern u8 lbl_00015480[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_1000000C[];
extern u8 lbl_1000013C[];
extern u8 lbl_1000013E[];
extern u8 lbl_1000013F[];
extern u8 lbl_10000154[];
extern u8 lbl_10000178[];
extern u8 lbl_100004C0[];
extern u8 lbl_100004E0[];
extern u8 lbl_10012140[];
extern u8 lbl_10012180[];
extern u8 lbl_10018510[];

// Imported functions the code calls that no included header declares.
extern void draw_test_camera_target();
extern void func_80071B08();
extern void func_8009C5E4();
extern void func_8009CD5C();
extern void func_8009D794();
extern void func_8009DB40();
extern void func_8009DDC4();
extern void func_800AB2A0();
extern void func_800AB444();
extern void func_800AB6F8();
extern void func_800AC43C();
extern void func_800AC5E0();
extern void mini_commend_free_data();
extern void u_load_minigame_graphics();
extern void u_set_minigame_callbacks_2();

