/*
 * mini_billiards.c -- REL module: isolated function lbl_00018F4C.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "pause_menu.h"
#include "pool.h"
#include "recplay.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "mot_ape.h"
#include "avdisp.h"
#include "vibration.h"
#include "ord_tbl.h"
#include "background.h"
#include "effect.h"
#include "nl2ngc.h"
#include "string.h"

struct BilliardsPlayerC48
{
    s8 unk0;
    s8 unk1;
    s8 unk2;
    u8 filler3;
    s16 unk4;
};                     /* 6 */

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_billiards.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0001C2B8[];
extern u8 lbl_0001CAD8[];
extern u8 lbl_0001CBD0[];
extern u8 lbl_0001CC88[];
extern u8 lbl_0001CE18[];
extern u8 lbl_0001CF00[];
extern u8 lbl_0001CF50[];
extern u8 lbl_0001CFD0[];
extern u8 lbl_00020840[];
extern u8 lbl_00020848[];
extern u8 lbl_00020AF0[];
extern u8 lbl_00020B10[];
extern u8 lbl_00020B30[];
extern u8 lbl_00020B58[];
extern u8 lbl_00020B68[];
extern u8 lbl_00020B78[];
extern u8 lbl_00020C20[];
extern u8 lbl_00020C40[];
extern u8 lbl_00020CA0[];
extern u8 lbl_00020DA0[];
extern u8 lbl_00020E30[];
extern u8 lbl_00020E38[];
extern u8 lbl_00020E40[];
extern u8 lbl_00020EC0[];
extern u8 lbl_00020EE0[];
extern u8 lbl_00020F00[];
extern u8 lbl_00020F70[];
extern u8 lbl_00020FC0[];
extern u8 lbl_00021080[];
extern u8 lbl_000210A8[];
extern u8 lbl_00021204[];
extern u8 lbl_0002157C[];
extern u8 lbl_000215B0[];
extern u8 lbl_10000000[];
extern u8 lbl_10000002[];
extern u8 lbl_10000003[];
extern u8 lbl_10000004[];
extern u8 lbl_10000006[];
extern u8 lbl_10000008[];
extern u8 lbl_1000000A[];
extern u8 lbl_1000000B[];
extern u8 lbl_1000000C[];
extern u8 lbl_1000000D[];
extern u8 lbl_1000000E[];
extern u8 lbl_1000000F[];
extern u8 lbl_10000010[];
extern u8 lbl_10000011[];
extern u8 lbl_10000012[];
extern u8 lbl_10000013[];
extern u8 lbl_10000014[];
extern u8 lbl_10000015[];
extern u8 lbl_10000016[];
extern u8 lbl_10000017[];
extern u8 lbl_10000018[];
extern u8 lbl_1000001A[];
extern u8 lbl_1000001C[];
extern u8 lbl_1000001E[];
extern u8 lbl_1000001F[];
extern u8 lbl_10000020[];
extern u8 lbl_10000024[];
extern u8 lbl_10000028[];
extern u8 lbl_1000002C[];
extern u8 lbl_10000030[];
extern u8 lbl_10000034[];
extern u8 lbl_10000038[];
extern u8 lbl_1000003C[];
extern u8 lbl_10000048[];
extern u8 lbl_10000049[];
extern u8 lbl_1000004A[];
extern u8 lbl_1000004C[];
extern u8 lbl_1000004E[];
extern u8 lbl_10000050[];
extern u8 lbl_10000054[];
extern u8 lbl_10000058[];
extern u8 lbl_1000005C[];
extern u8 lbl_10000060[];
extern u8 lbl_10000061[];
extern u8 lbl_10000062[];
extern u8 lbl_10000064[];
extern u8 lbl_100000A4[];
extern struct BilliardsPlayerC48 lbl_10000A64[];
extern u8 lbl_10000A70[];
extern u8 lbl_10009710[];
extern u8 lbl_10009878[];
extern u8 lbl_10009C88[];
extern u8 lbl_10009C8C[];
extern u8 lbl_10009CA0[];
extern u8 lbl_10009CBC[];
extern u8 lbl_1000A5BC[];
extern u8 lbl_1000AA38[];
extern u8 lbl_1000B340[];
extern u8 lbl_1000B360[];
extern u8 lbl_1000B361[];
extern u8 lbl_1000B390[];
extern u8 lbl_1000B418[];
extern u8 s_somethingLightRelated[];

// Imported functions the code calls that no included header declares.
extern void __cvt_fp2unsigned();
extern void func_8009C5E4();
extern void func_8009CAE0();
extern void func_8009CD5C();
extern void func_8009DB40();
extern void func_8009DB9C();
extern void func_8009DDC4();
extern void mini_commend_free_data();
extern void sqrt();
extern void u_load_minigame_graphics();
extern void window_printf_1();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_000001E0(void);
void lbl_00000614(void);
void lbl_00000754(void);
void lbl_00000800(void);
void lbl_00000E68(void);
void lbl_00000F34(void);
void lbl_00000F5C(void);
void lbl_000023B0(void);
void lbl_000025B0(void);
void lbl_00002B4C(void);
void lbl_00002C80(void);
void lbl_0000341C(void);
void lbl_0000367C(void);
void lbl_00003CC8(void);
void lbl_00003F4C(void);
void lbl_00004634(void);
void lbl_000055FC(void);
void lbl_00005654(void);
void lbl_000059A8(void);
void lbl_00005DD0(void);
void lbl_00006DC0(void);
void lbl_000077D8(void);
void lbl_00007974(void);
void lbl_00007C74(void);
void lbl_00007D18(void);
void lbl_00007D80(void);
void lbl_00008EC0(void);
void lbl_0000939C(void);
void lbl_00009540(void);
void lbl_00009788(void);
void lbl_00009E34(void);
void lbl_00009EC4(void);
void lbl_00009F0C(void);
void lbl_00009F3C(void);
void lbl_0000A054(void);
void lbl_0000C85C(void);
void lbl_0000D0A4(void);
void lbl_0000D330(void);
void lbl_0000D7E8(void);
void lbl_0000E8D0(void);
void lbl_00010FD0(void);
void lbl_000111B4(void);
void lbl_000115F4(void);
void lbl_00016D24(void);
void lbl_00016D9C(void);
void lbl_0001723C(void);
void lbl_00017408(void);
void lbl_00017A00(void);
void lbl_00018008(void);
void lbl_00018474(void);
void lbl_00018608(void);
void lbl_000186EC(void);
void lbl_000189B4(void);
void lbl_00018A98(void);
void lbl_00018C78(void);
void lbl_00018F4C(struct Ape *, f32);
void lbl_00019264(void);
void lbl_0001968C(void);
void lbl_00019F5C(void);
void lbl_00019FD4(void);
void lbl_0001A074(void);
void lbl_0001A0B0(void);
void lbl_0001A18C(void);
void lbl_0001B880(void);

#pragma force_active on
void lbl_00018F4C(struct Ape *ape, f32 f)
{
    u8 *p = lbl_00020B58;
    int b = 0;
    u32 a;

    if ((u8)((u8)*(s8 *)lbl_1000000A - 14) <= 3
        && *(s8 *)lbl_10000049 == ape->ballId) {
        a = 5;
        b = 0xc;
    } else if (ape->flags & 0x80000) {
        a = 5;
        if (*(s8 *)lbl_1000000A == 0x17) {
            if (ape->ballId == 0)
                b = lbl_10000A64[lbl_802F1C32].unk4 % 6 * 2;
            else
                b = 0;
        } else {
            b = 6;
        }
    } else if ((*(s8 *)lbl_1000000A != 0x16
                && (ape->unk24 == 0xf
                    || (ape->unk24 == 0xa && ape->unkC2 < 3)))
               || (*(s8 *)lbl_1000000A == 0x16 && (ape->flags & 0x800000))) {
        a = 0xa;
        b = 4;
        if (ape->unk24 == 0xa)
            ape->flags &= ~0x1000;
    } else if ((*(s8 *)lbl_1000000A == 0x12 || *(s8 *)lbl_1000000A == 9)
               && *(s32 *)lbl_10000020 == 0 && ape->ballId == 0) {
        a = 0xf;
        if (*(f32 *)lbl_10000038 < *(f32 *)(p + 0xb0))
            b = 2;
        else if ((*(s8 *)lbl_10000048 == 0
                  && *(f32 *)lbl_10000038 < *(f32 *)(p + 0xbc))
                 || (*(s8 *)lbl_10000048 == 1
                     && *(f32 *)lbl_10000038 < *(f32 *)(p + 0xc0)))
            b = 1;
        else
            b = 0;
        ape->flags |= 0x1000;
    } else if (*(s8 *)lbl_1000000A == 9 && *(s32 *)lbl_10000020 == 0
               && ape->ballId == 1) {
        a = 0xf;
        if (*(f32 *)lbl_1000003C < *(f32 *)(p + 0xb0))
            b = 2;
        else if (*(f32 *)lbl_1000003C < *(f32 *)(p + 0xbc))
            b = 1;
        else
            b = 0;
        ape->flags |= 0x1000;
    } else if (ape->flags & 2) {
        a = 3;
    } else if (ape->flags & 0x200000) {
        a = 9;
        b = 3;
    } else if (ape->flags & 1) {
        a = 1;
        if (ape->ballId == 0 && (u8)((u8)*(s8 *)lbl_1000000A - 7) <= 4
            && ape->ballId == 1)
            f = *(f32 *)(p + 0x18);
        else
            f = (f32)ape->unk54++;
    } else {
        a = 0;
    }
    if (a != 1 || ape->unk24 != 0xa)
        ape->unk54 = 0;
    new_ape_stat_motion(ape, a, b, 0, f);
}
#pragma force_active reset
