/*
 * mini_bowling.c -- REL module, structurally split for per-function
 * byte-matching (part 4 of 96; contiguous .text range).  Each function
 * below is an asm-include of its body in asm/nonmatchings/mini_bowling/.
 * To convert one to C, isolate it into its own pure-C file (see the
 * --isolate option of tools/rel_split.py) -- an asm sibling in the same
 * TU disables mwcc's optimizer for the C function.  Keep the Makefile
 * SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "pool.h"
#include "rend_efc.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "pause_menu.h"
#include "string.h"
#include "avdisp.h"
#include "background.h"
#include "obj_collision.h"
#include "ord_tbl.h"
#include "stcoli.h"
#include "shadow.h"
#include "vibration.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_bowling.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000F020[];
extern u8 lbl_00010C40[];
extern u8 lbl_00010CC0[];
extern u8 lbl_00010CC8[];
extern u8 lbl_00010D58[];
extern u8 lbl_00010D60[];
extern u8 lbl_00010EE0[];
extern u8 lbl_00010EE8[];
extern u8 lbl_00010EF0[];
extern u8 lbl_00010F24[];
extern u8 lbl_00010F94[];
extern u8 lbl_00011250[];
extern u8 lbl_00011258[];
extern u8 lbl_000112C0[];
extern u8 lbl_000112C8[];
extern u8 lbl_00011338[];
extern u8 lbl_00011340[];
extern u8 lbl_00011490[];
extern u8 lbl_000146A0[];
extern u8 lbl_000147F8[];
extern u8 lbl_00014800[];
extern u8 lbl_00014B78[];
extern u8 lbl_00014BE8[];
extern u8 lbl_00014C00[];
extern u8 lbl_00014C08[];
extern u8 lbl_00014CB8[];
extern u8 lbl_00014D70[];
extern u8 lbl_00014D90[];
extern u8 lbl_00014E10[];
extern u8 lbl_00014F20[];
extern u8 lbl_00014F24[];
extern u8 lbl_00015020[];
extern u8 lbl_00015024[];
extern u8 lbl_00015040[];
extern u8 lbl_00015380[];
extern u8 lbl_00015388[];
extern u8 lbl_000153E0[];
extern u8 lbl_000153E4[];
extern u8 lbl_000153E8[];
extern u8 lbl_000153F4[];
extern u8 lbl_00015428[];
extern u8 lbl_00015434[];
extern u8 lbl_0001543C[];
extern u8 lbl_00015444[];
extern u8 lbl_00015454[];
extern u8 lbl_00015460[];
extern u8 lbl_0001546C[];
extern u8 lbl_00015480[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_1000000C[];
extern u8 lbl_1000013C[];
extern u8 lbl_1000013E[];
extern u8 lbl_1000013F[];
extern u8 lbl_10000154[];
extern u8 lbl_10000178[];
extern u8 lbl_100004C0[];
extern u8 lbl_100004E0[];
extern u8 lbl_10012140[];
extern u8 lbl_10012180[];
extern u8 lbl_10018510[];

// Imported functions the code calls that no included header declares.
extern void draw_test_camera_target();
extern void func_80071B08();
extern void func_8009C5E4();
extern void func_8009CD5C();
extern void func_8009D794();
extern void func_8009DB40();
extern void func_8009DDC4();
extern void func_800AB2A0();
extern void func_800AB444();
extern void func_800AB6F8();
extern void func_800AC43C();
extern void func_800AC5E0();
extern void mini_commend_free_data();
extern void u_load_minigame_graphics();
extern void u_set_minigame_callbacks_2();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_0000020C(int arg0);
void lbl_00000718(void);
void lbl_000009EC(void);
void lbl_00000F98(void);
void lbl_00001888(void);
void lbl_00001908(void);
void lbl_00001B14(void);
void lbl_00001C84(void);
void lbl_00001F1C(void);
void lbl_000021B4(void);
void lbl_00002454(void);
void lbl_000027B0(void);
void lbl_000029A8(void);
void lbl_00002DE0(void);
void lbl_00003574(void);
void lbl_00003A10(void);
void lbl_00003D24(void);
void lbl_00003DC0(void);
void lbl_000042A4(void);
void lbl_00004410(void);
void lbl_000045E8(void);
void lbl_00004A80(void);
void lbl_00004BD8(void);
void lbl_00004D10(void);
void lbl_00004DF8(void);
void lbl_00005128(void);
void lbl_000051E0(void);
void lbl_000054BC(void);
void lbl_00005564(void);
void lbl_00005B0C(void);
void lbl_000066C4(void);
void lbl_000068C4(void);
void lbl_00006E64(void);
void lbl_00006F0C(void);
void lbl_00007518(void);
void lbl_00007650(void);
void lbl_000076D0(void);
void lbl_00007740(void);
void lbl_00007778(void);
void lbl_00007878(void);
void lbl_00007964(int, struct Ball *);
void lbl_000079E8(void);
void lbl_00007A6C(void);
void lbl_00007C54(void);
void lbl_00007E74(void);
void lbl_00007FE0(void);
void lbl_000080E0(void);
void lbl_000082E4(void);
void lbl_000086E4(void);
void lbl_0000871C(void);
void lbl_000087CC(void);
void lbl_000089FC(void);
void lbl_00008B8C(void);
void lbl_00008C68(void);
void lbl_00008D2C(void);
void lbl_00008DF0(void);
void lbl_00008EC0(void);
void lbl_00008FB0(void);
void lbl_00009048(void);
void lbl_000090CC(void);
void lbl_00009134(void);
void lbl_0000919C(void);
void lbl_00009230(void);
void lbl_000096B4(void);
void lbl_000097B4(void);
void lbl_00009AA8(void);
void lbl_00009D18(void);
void lbl_00009F60(void);
void lbl_0000A138(void);
void lbl_0000A23C(void);
void lbl_0000A610(void);
void lbl_0000A778(void);
void lbl_0000A808(void);
void lbl_0000A878(void);
void lbl_0000AAAC(void);
void lbl_0000AB98(void);
void lbl_0000AC60(void);
void lbl_0000AD8C(void);
void lbl_0000AF18(void);
void lbl_0000AFEC(void);
void lbl_0000B0AC(void);
void lbl_0000B1BC(void);
void lbl_0000B344(void);
void lbl_0000B460(int);
void lbl_0000B654(void);
void lbl_0000B848(void);
void lbl_0000B914(void);
void lbl_0000BDE0(void);
void lbl_0000BEB8(void);
void lbl_0000C0D0(void);
void lbl_0000C1D0(void);
void lbl_0000CAA8(void);
void lbl_0000D4D4(void);
void lbl_0000D598(void);
void lbl_0000D650(void);
void lbl_0000D7F8(void);
void lbl_0000D8CC(void);
void lbl_0000D90C(void);
void lbl_0000DA0C(void);
void lbl_0000DAF4(void);
void lbl_0000DD4C(void);
void lbl_0000DFA4(void);
void lbl_0000E22C(void);
void lbl_0000E3A0(void);
void lbl_0000E510(void);
void lbl_0000E5D4(void);
void lbl_0000E7B0(void);
void lbl_0000E870(void);
void lbl_0000E894(void);
void lbl_0000EC38(void);
void lbl_0000EDB0(void);

#pragma force_active on
struct BowlPlayer {
    u8 filler0[0x4c];
};

void lbl_0000020C(int arg0)
{
    u8 *w = lbl_10000000;
    u8 *k = lbl_0000F020;
    u8 *q = lbl_00014F20;
    u8 *p;
    s32 i;
    s32 j;
    f32 a;
    f32 b;

    event_finish_all();
    free_all_bitmap_groups_except_com();
    func_800249D4();
    SoundGroupLoad(0xa);
    func_80044920();
    load_stage(0xb3);
    u_load_minigame_graphics(4);
    call_bitmap_load_group(6);
    submodeFinishFunc = lbl_00001888;
    event_start(1);
    event_start(2);
    event_start(3);
    event_start(4);
    event_start(9);
    event_start(0xf);
    event_start(0x10);
    event_start(0x12);
    event_start(0xd);
    event_start(0x13);
    event_start(0x14);
    event_start(0xb);
    light_init(0xb3);
    rend_efc_mirror_enable();
    stageInfo.unk1C |= 1;
    stageInfo.unk0 = 0;
    u_init_player_data_1();
    BALL_FOREACH(ball->state = 1;)
    WORLD_FOREACH(world->state = 1;)
    for (i = 0; i < 4; i++)
    {
        if (g_poolInfo.playerPool.statusList[i] != 0)
            apeThreadNo[i] = thread_create((ThreadCallback)lbl_000066C4,
                                           ballInfo[i].ape, THREAD_GROUP_5);
    }
    camera_set_state_all(0x3d);
    CAMERA_FOREACH_2(camera->subState = 0; camera->unk26 = 9;)
    for (i = 0; i < 4; i++)
    {
        a = *(f32 *)(k + 0x1c98);
        b = *(f32 *)(k + 0x1c9c);
        setup_camera_viewport(i, a, a, b, b);
    }
    info_init_first();
    for (i = 0; i < 4; i++)
    {
        p = (u8 *)&((struct BowlPlayer *)(w + 0xc))[i];
        *(s32 *)(p + 0) = 0;
        *(s16 *)(p + 4) = 0;
        p[6] = 1;
        p[7] = 1;
        p[8] = 0;
        p[9] = 0;
        *(s16 *)(p + 0xa) = 0;
        for (j = 1; j < 11; j++)
            *(s16 *)(p + 0xa + j * 2) = -1;
        for (j = 0; j < 0x15; j++)
        {
            ((u8 *)p)[0x20 + j] = 0;
            ((u8 *)p)[0x35 + j] = 0;
        }
    }
    *(s16 *)(w + 0x13c) = 0;
    w[0x13e] = 0;
    q[8] = 1;
    *(s16 *)(w + 4) = 0;
    w[6] = 0;
    w[7] = 0;
    w[8] = 0xb;
    *(s32 *)(w + 0x144) = 0;
    start_screen_fade(0x100, 0, 0x1e);
    *(s32 *)(q + 0xc) = -1;
    u_play_music(0x36, 0);
    lbl_0000A808();
    if ((s32)lbl_802F1BF0 == 0)
    {
        *(s32 *)q = 1;
        *(s32 *)(q + 4) = 0x21;
        *(s32 *)w = 0x2710;
    }
    else
    {
        *(s32 *)q = 0x800;
        *(s32 *)(q + 4) = 0x8001;
        *(s32 *)w = 0x2710;
    }
    lbl_00007964(0, ballInfo);
    lbl_0000B460(0);
    lbl_00007964(1, ballInfo);
    lbl_0000B460(1);
    w[0x13f] = 0;
    w[0x140] = 0;
    lbl_000097B4();
    *(s8 *)(w + 0x148) = -1;
    *(s8 *)(w + 0x149) = -1;
    *(s8 *)(w + 0x14a) = -1;
    *(s8 *)(w + 0x14b) = -1;
    w[0x14c] = 0;
}
#pragma force_active reset
