/*
 * mini_pilot.c -- REL module, structurally split for per-function
 * byte-matching (part 23 of 53; contiguous .text range).  Each function
 * below is an asm-include of its body in asm/nonmatchings/mini_pilot/.
 * To convert one to C, isolate it into its own pure-C file (see the
 * --isolate option of tools/rel_split.py) -- an asm sibling in the same
 * TU disables mwcc's optimizer for the C function.  Keep the Makefile
 * SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "game.h"
#include "input.h"
#include "item.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "ord_tbl.h"
#include "pause_menu.h"
#include "pool.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "stcoli.h"
#include "vibration.h"
#include "window.h"
#include "avdisp.h"
#include "background.h"
#include "effect.h"
#include "gxutil.h"
#include "hud.h"
#include "info.h"
#include "lens_flare.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "rend_efc.h"
#include "shadow.h"
#include "spline.h"
#include "stobj.h"
#include "world.h"
#include "stdlib.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_pilot.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000BE80[];
extern u8 lbl_0000BEB0[];
extern u8 lbl_0000BEB4[];
extern u8 lbl_0000BEE0[];
extern u8 lbl_0000BFD0[];
extern u8 lbl_0000BFE0[];
extern u8 lbl_0000BFE8[];
extern u8 lbl_0000C010[];
extern u8 lbl_0000C030[];
extern u8 lbl_0000C2A8[];
extern u8 lbl_0000C2C8[];
extern u8 lbl_0000C2F0[];
extern u8 lbl_0000C348[];
extern u8 lbl_0000C358[];
extern u8 lbl_0000C360[];
extern u8 lbl_0000C3C0[];
extern u8 lbl_0000C3C8[];
extern u8 lbl_0000C3CC[];
extern u8 lbl_0000C430[];
extern u8 lbl_0000C548[];
extern u8 lbl_0000C5B8[];
extern u8 lbl_0000C5C0[];
extern u8 lbl_0000C690[];
extern u8 lbl_0000C6D8[];
extern u8 lbl_0000C740[];
extern u8 lbl_0000C748[];
extern u8 lbl_0000C7BC[];
extern u8 lbl_0000C7CC[];
extern u8 lbl_0000C7EC[];
extern u8 lbl_0000C88C[];
extern u8 lbl_0000CB0C[];
extern u8 lbl_0000CBCC[];
extern u8 lbl_0000CCF8[];
extern u8 lbl_0000D1C8[];
extern u8 lbl_0000D218[];
extern u8 lbl_0000D2E8[];
extern u8 lbl_0000D300[];
extern u8 lbl_0000D314[];
extern u8 lbl_0000D320[];
extern u8 lbl_0000D324[];
extern u8 lbl_0000D328[];
extern u8 lbl_0000D338[];
extern u8 lbl_0000D360[];
extern u8 lbl_0000D368[];
extern u8 lbl_0000D3A0[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000018[];
extern u8 lbl_1000001E[];
extern u8 lbl_10000020[];
extern u8 lbl_10000034[];
extern u8 lbl_10000038[];
extern u8 lbl_1000003C[];
extern u8 lbl_10000040[];
extern u8 lbl_10000044[];
extern u8 lbl_10000054[];
extern u8 lbl_1000005C[];
extern u8 lbl_10000064[];
extern u8 lbl_10000066[];
extern u8 lbl_10000068[];
extern u8 lbl_10000074[];
extern u8 lbl_10000078[];
extern u8 lbl_10000087[];
extern u8 lbl_10000088[];
extern u8 lbl_1000008A[];
extern u8 lbl_1000008C[];
extern u8 lbl_10000090[];
extern u8 lbl_10000098[];
extern u8 lbl_100000A8[];
extern u8 lbl_100000B0[];
extern u8 lbl_100000B8[];
extern u8 neutralFaceTable[];
extern u8 smileFaceTable[];
extern u8 lbl_80285A58[];
extern u8 lbl_80285A68[];
extern u8 lbl_80285A80[];
extern u8 lbl_802F1F10[];
extern u8 lbl_802F1FD0[];
extern u8 lbl_802F1FD8[];
extern u8 lbl_802F1FDC[];
extern u8 lbl_802F1FE0[];
extern u8 lbl_802F1FE4[];
extern u8 lbl_802F1FEC[];
extern u8 lbl_802F1FF4[];

// Imported functions the code calls that no included header declares.
extern void ball_8003BBF4();
extern void draw_test_camera_target();
extern void func_80042214();
extern void func_8009C5E4();
extern void func_8009CD5C();
extern void func_8009D794();
extern void func_8009DB40();
extern void func_800AB2A0();
extern void func_800AB444();
extern void func_800AB6F8();
extern void func_800AC43C();
extern void func_800AC5E0();
extern void gxutil_draw_line_multicolor();
extern void item_create();
extern void mini_commend_free_data();
extern void qsort();
extern void set_shape_flags_in_model();
extern void stcoli_sub35();
extern void u_load_minigame_graphics();
extern void thread_create();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_000003B4(void);
void lbl_0000044C(void);
void lbl_000004E0(void);
void lbl_00000648(void);
void lbl_0000066C(void);
void lbl_00000698(void);
void lbl_000007B8(void);
void lbl_000008AC(void);
void lbl_00000A30(void);
void lbl_00000BFC(void);
void lbl_0000215C(void);
void lbl_000021B4(void);
void lbl_000022D8(void);
void lbl_00003B6C(void);
void lbl_00003BDC(void);
void lbl_00004024(void);
void lbl_000040EC(void);
void lbl_00004450(void);
void lbl_00004570(void);
void lbl_000048C0(void);
void lbl_00004A14(void);
void lbl_00004E84(void);
void lbl_00004F68(void);
void lbl_00005044(void);
void lbl_000051A4(void);
static void lbl_00005414(void);
void lbl_0000580C(void);
void lbl_00005824(void);
void lbl_00006124(void);
void lbl_00006490(void);
void lbl_0000669C(void);
void lbl_00006A94(void);
void lbl_00006B5C(void);
void lbl_00006B94(void);
void lbl_00006BF4(void);
void lbl_00006CCC(void);
void lbl_00006D14(void);
void lbl_00006DFC(void);
void lbl_00007EF8(void);
void lbl_00008134(void);
void lbl_000082C0(void);
void lbl_00008568(void);
void lbl_000085B4(void);
void lbl_0000893C(void);
void lbl_000089F8(void);
void lbl_00008C40(void);
void lbl_000090A0(void);
void lbl_000091EC(void);
void lbl_00009440(void);
void lbl_000097AC(void);
void lbl_000097C8(void);
void lbl_000099A4(void);
void lbl_00009A98(void);
void lbl_00009B04(void);
void lbl_00009C18(void);
void lbl_00009F4C(void);
void lbl_00009FB0(void);
void lbl_0000A098(void);
void lbl_0000A69C(void);
void lbl_0000A754(void);
void lbl_0000AD6C(void);
void lbl_0000AE94(void);
void lbl_0000AEE0(void);
void lbl_0000AF68(void);
void lbl_0000B000(void);
void lbl_0000B130(void);
void lbl_0000B624(void);
void lbl_0000BACC(void);

#pragma force_active on
asm void lbl_000051A4(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_pilot/lbl_000051A4.s"
}
static asm void lbl_00005414(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_pilot/lbl_00005414.s"
}
#pragma force_active reset
