/*
 * mini_golf.c -- REL module: isolated function run lbl_000252C0 .. lbl_0002572C.
 * This file holds one contiguous run of functions, meant to be a single
 * pure-C file once ALL of them are converted from the asm-includes below.
 * Until the last stub becomes C this file still contains an `asm` block,
 * which disables mwcc's scheduler/peephole for the C functions here -- so
 * convert the whole run (or match function-by-function with --isolate
 * singletons first, then consolidate into this range file).
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dolphin.h>
#include "global.h"
#include "avdisp.h"
#include "ball.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "pool.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "stcoli.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "input.h"
#include "background.h"
#include "light.h"
#include "polydisp.h"
#include "gxcache.h"
#include "stdlib.h"
#include "effect.h"
#include "vibration.h"
#include "lens_flare.h"
#include "nl2ngc.h"
#include "shadow.h"
#include "ord_tbl.h"
#include "stobj.h"
#include "item.h"
#include "gxutil.h"
#include "rend_efc.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_golf.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_000260F0[];
extern u8 lbl_00026118[];
extern u8 lbl_00026158[];
extern u8 lbl_000261E8[];
extern u8 lbl_000261F0[];
extern u8 lbl_000262F0[];
extern u8 lbl_00026378[];
extern u8 lbl_00026380[];
extern u8 lbl_00026390[];
extern u8 lbl_000263B0[];
extern u8 lbl_000264A8[];
extern u8 lbl_000264C8[];
extern u8 lbl_000264E0[];
extern u8 lbl_00026510[];
extern u8 lbl_00026538[];
extern u8 lbl_00026550[];
extern u8 lbl_000266A0[];
extern u8 lbl_000266F8[];
extern u8 lbl_00026A38[];
extern u8 lbl_00026A44[];
extern u8 lbl_00026A60[];
extern u8 lbl_00026A98[];
extern u8 lbl_00026AA0[];
extern u8 lbl_00026AB0[];
extern u8 lbl_00026AC4[];
extern u8 lbl_00026AEC[];
extern u8 lbl_00026AF0[];
extern u8 lbl_00026AF4[];
extern u8 lbl_00026AF8[];
extern u8 lbl_00026B40[];
extern u8 lbl_00026BCC[];
extern u8 lbl_00026BE8[];
extern u8 lbl_00026D08[];
extern u8 lbl_00026D50[];
extern u8 lbl_00026DA0[];
extern u8 lbl_00026DF0[];
extern u8 lbl_00026DF4[];
extern u8 lbl_00026E10[];
extern u8 lbl_00026E28[];
extern u8 lbl_00026FB8[];
extern u8 lbl_0002A4D8[];
extern u8 lbl_0002A9E8[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000010[];
extern u8 lbl_1000003A[];
extern u8 lbl_1000003E[];
extern u8 lbl_10000046[];
extern u8 lbl_10000048[];
extern u8 lbl_1000005C[];
extern u8 lbl_100000C8[];
extern u8 lbl_100000D0[];
extern u8 lbl_100000EB[];
extern u8 lbl_100000ED[];
extern u8 lbl_100000F6[];
extern u8 lbl_100000F8[];
extern u8 lbl_100000FB[];
extern u8 lbl_10000100[];
extern u8 lbl_10000130[];
extern u8 lbl_10000170[];
extern u8 lbl_10000178[];
extern u8 lbl_10000190[];
extern u8 lbl_100001C8[];
extern u8 lbl_100001CA[];
extern u8 lbl_100001D4[];
extern u8 lbl_10000204[];
extern u8 lbl_10000210[];
extern u8 lbl_10000248[];

// Imported functions the code calls that no included header declares.
extern void u_load_minigame_graphics();
extern void u_set_minigame_callbacks_2();
extern void __cvt_fp2unsigned();
extern void draw_test_camera_target();
extern void func_800AB444();
extern void func_8009CD5C();
extern void func_800AB6F8();
extern void func_800AB2A0();
extern void func_800AC43C();
extern void func_8009C5E4();
extern void func_8009D794();
extern void func_800AC5E0();
extern void alloc_pool_light();
extern void mini_commend_free_data();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void lbl_000000C8(void);
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_0000027C(void);
void lbl_000002A8(void);
void lbl_000005CC(void);
void lbl_000056C4(void);
void lbl_00007F34(void);
void lbl_00008A44(void);
void lbl_00008C78(void);
void lbl_00008D34(void);
void lbl_00008F44(void);
void lbl_0000907C(void);
void lbl_00009178(void);
void lbl_000091BC(void);
void lbl_000092C4(void);
void lbl_000092D0(void);
void lbl_000092E0(void);
void lbl_000092F0(void);
void lbl_00009300(void);
u8 lbl_00009310(void);
void lbl_00009320(void);
void lbl_00009340(void);
void lbl_00009360(void);
void lbl_00009384(void);
void lbl_00009394(void);
void lbl_000093A4(void);
void lbl_000093B4(void);
void lbl_000093C4(void);
u8 lbl_000093D4(int a, int b);
void lbl_000093F0(void);
u8 lbl_00009404(void);
void lbl_00009414(void);
void lbl_00009424(void);
void lbl_00009438(void);
void lbl_00009448(void);
u8 lbl_00009458(void);
void lbl_00009478(void);
void lbl_00009488(void);
void lbl_00009538(void);
void lbl_000095C4(void);
void lbl_000097D8(void);
void lbl_00009800(void);
void lbl_0000982C(void);
void lbl_00009880(void);
void lbl_00009968(void);
void lbl_000099B4(void);
void lbl_000099E0(void);
void lbl_00009B68(void);
void lbl_00009C10(void);
void lbl_00009C50(void);
void lbl_0000B280(void);
void lbl_0000B36C(void);
void lbl_0000B754(void);
void lbl_0000B8A8(void);
void lbl_0000BDEC(void);
void lbl_0000C128(void);
void lbl_0000C230(void);
void lbl_0000C33C(void);
void lbl_0000D64C(void);
void lbl_0000E8AC(void);
void lbl_0000E998(void);
void lbl_0000E99C(void);
void lbl_0000F11C(void);
void lbl_0000F194(void);
void lbl_0000F290(void);
void lbl_0000F750(void);
void lbl_0000F7E8(void);
void lbl_0000FA18(void);
void lbl_0000FBC8(void);
void lbl_0000FCE0(void);
void lbl_000100D4(void);
void lbl_00010304(void);
void lbl_000106B8(void);
void lbl_00010808(void);
void lbl_000109CC(void);
void lbl_00010E68(void);
void lbl_00010E74(void);
void lbl_00011254(void);
void lbl_000115F8(void);
void lbl_0001199C(void);
void lbl_00011A6C(void);
void lbl_00011DAC(void);
void lbl_00011FEC(void);
void lbl_000123B4(void);
void lbl_00012A14(void);
void lbl_00012C80(void);
void lbl_00012EEC(void);
void lbl_00013664(void);
void lbl_00015520(void);
void lbl_0001B5B8(void);
void lbl_00022524(void);
void lbl_00022610(void);
void lbl_00022904(void);
void lbl_00022D4C(void);
void lbl_000230E4(void);
void lbl_00023AB4(void);
void lbl_00023C68(void);
void lbl_00023DC4(void);
void lbl_00023DD4(void);
void lbl_000245D4(void);
void lbl_000246E8(void);
void lbl_00024A40(void);
void lbl_00024E70(void);
void lbl_000252C0(void);
void lbl_0002544C(void);
void lbl_000255CC(u8 a);
void lbl_0002572C(struct Ape *ape, f32 f);
void lbl_00025928(void);
void lbl_00025A44(void);
void lbl_00025B10(void);
void lbl_00025B70(void);
void lbl_00025BD0(void);
void lbl_00025EA8(void);
void lbl_0002609C(void);
void lbl_000260C0(void);

#pragma force_active on
void lbl_000252C0(void)
{
    if (*(u8 *)lbl_0002A9E8 != 4)
    {
        *(u8 *)lbl_0002A9E8 = 4;
        *(s32 *)(lbl_0002A9E8 + 4) = 0;
    }
    if (lbl_00009458() != 0 || lbl_000093D4(modeCtrl.currPlayer, lbl_00009404()) == 0)
    {
        new_ape_stat_motion(ballInfo[modeCtrl.currPlayer].ape, 2, 0xc, 0, *(f32 *)lbl_00026A44);
    }
    else if (ballInfo[modeCtrl.currPlayer].unk148 == 0)
    {
        lbl_0002572C(ballInfo[modeCtrl.currPlayer].ape, *(f32 *)lbl_00026A44);
    }
    else if (lbl_00009310() != 0)
    {
        new_ape_stat_motion(ballInfo[modeCtrl.currPlayer].ape, 1, 0, 0,
                            (f32)ballInfo[modeCtrl.currPlayer].ape->unk54++);
    }
    else
    {
        lbl_0002572C(ballInfo[modeCtrl.currPlayer].ape,
                     mathutil_vec_len(&ballInfo[modeCtrl.currPlayer].vel));
    }
}
void lbl_0002544C(void)
{
    u8 *p = (u8 *)lbl_0002A9E8;

    if (*(u8 *)p != 5)
    {
        *(u8 *)p = 5;
        *(u32 *)(p + 4) = 0;
    }
    *(u32 *)(p + 4) = *(u32 *)(p + 4) + 1;
    if (*(u32 *)(p + 4) < 0x3c)
    {
        new_ape_stat_motion(ballInfo[modeCtrl.currPlayer].ape, 0xa, 4, 0, *(f32 *)lbl_00026A44);
    }
    else if (ballInfo[modeCtrl.currPlayer].unk148 == 0)
    {
        lbl_0002572C(ballInfo[modeCtrl.currPlayer].ape, *(f32 *)lbl_00026A44);
    }
    else if (lbl_00009310() != 0)
    {
        new_ape_stat_motion(ballInfo[modeCtrl.currPlayer].ape, 1, 0, 0,
                            (f32)ballInfo[modeCtrl.currPlayer].ape->unk54++);
    }
    else
    {
        lbl_0002572C(ballInfo[modeCtrl.currPlayer].ape,
                     mathutil_vec_len(&ballInfo[modeCtrl.currPlayer].vel));
    }
}
void lbl_000255CC(u8 a)
{
    u8 *cfg = (u8 *)lbl_00026A38;
    struct Ape *ape;

    if (*(u8 *)lbl_0002A9E8 != 6) {
        *(u8 *)lbl_0002A9E8 = 6;
        *(s32 *)(lbl_0002A9E8 + 4) = 0;
        *(u32 *)((u8 *)ballInfo[modeCtrl.currPlayer].ape + 0x14) &= ~0x2000;
        *(u32 *)((u8 *)ballInfo[modeCtrl.currPlayer].ape + 0x14) &= ~0x1000;
    }

    ape = ballInfo[modeCtrl.currPlayer].ape;
    if (*(u32 *)((u8 *)ape + 0x14) & 0x4000) {
        new_ape_stat_motion(ape, 2, 0xf, 0, *(f32 *)(cfg + 0xc));
    } else if (a == 1) {
        new_ape_stat_motion(ape, 5, 8, 0, *(f32 *)(cfg + 0xc));
    } else if (a == 2) {
        new_ape_stat_motion(ape, 5, 4, 0, *(f32 *)(cfg + 0xc));
    } else if (a == 3) {
        new_ape_stat_motion(ape, 5, 0, 0, *(f32 *)(cfg + 0xc));
    } else {
        new_ape_stat_motion(ape, 0xd, 9, 0, *(f32 *)(cfg + 0xc));
    }
}
void lbl_0002572C(struct Ape *ape, f32 f)
{
    u8 *w = (u8 *)lbl_10000210;
    int b = 0;
    u32 a;

    if (*(s32 *)(w + 0x30) > 0)
        *(s32 *)(w + 0x30) = *(s32 *)(w + 0x30) - 1;
    if (ape->flags & 2)
    {
        a = 3;
    }
    else if (ape->flags & 1)
    {
        a = 1;
        f = (f32)ape->unk54++;
    }
    else if (ballInfo[modeCtrl.currPlayer].flags & 2)
    {
        a = 0xa;
        b = 4;
        if (*(s32 *)(w + 0x30) == 0)
        {
            *(s32 *)(w + 0x30) = 0x1e;
            w[0x34] = (rand() & 0x7FFF) % 8;
            if (w[0x34] == 0)
                u_play_sound_0(0x3a);
            else if (w[0x34] == 1)
                u_play_sound_0(0x3b);
            else if (w[0x34] == 2)
                u_play_sound_0(0x3f);
            else if (w[0x34] == 3)
                u_play_sound_0(0x53);
            else if (w[0x34] == 4)
                u_play_sound_0(0x54);
            else if (w[0x34] == 5)
                u_play_sound_0(0x55);
            else if (w[0x34] == 6)
                u_play_sound_0(0x56);
            else if (w[0x34] == 7)
                u_play_sound_0(0x57);
        }
    }
    else
    {
        a = 0;
    }
    if (a != 1 || gameSubmode == 0x31)
        ape->unk54 = 0;
    new_ape_stat_motion(ape, a, b, 0, f);
}
#pragma force_active reset
