/*
 * NOT MATCHED -- 9 in 4, span 20-190 of 304  (rel_sweep RAW 9 / ALIGNED 9)
 *
 * Everything is byte-exact except two residuals:
 *
 *  (1) 7 diffs: FP temp NUMBERING in the pos.y expression.  The instruction
 *      sequence, operand order and schedule are identical; only the register
 *      names differ.  exp: f1=pool[0x28], f2=pool[0x20], f3=startPos->pos.y.
 *      We get f3/f1/f2 because mwcc gives a CSE'd pointer-load the HIGHEST
 *      temp, and a source-level float LITERAL the lowest.  PROVEN with a
 *      build: replacing *(f64 *)(p + 0x28) with the literal 24.0 reproduces
 *      exp's exact f1/f2/f3 assignment.  pool+0x20 is the double 0.5 and
 *      pool+0x28 is the double 24.0, so this TU really does own that
 *      .rodata -- lbl_0000F290 is MIS-CLASSIFIED as b-POOL and needs a
 *      .rodata carve (Vec{0,0,0} @+0x00, Quaternion{0,0,0,1} @+0x0C,
 *      double 0.5 @+0x20, double 24.0 @+0x28, float 0.0f @+0x30).
 *
 *  (2) 2 diffs: the loop guard.  exp `li r6,0 / cmpw r6,r3 / bge`, we emit
 *      `li r6,0 / cmpwi r3,0 / ble` -- mwcc constant-folds i==0 into the
 *      guard and the original did not.  15 loop spellings swept, none move
 *      it; it is NOT fixed by the literals either.
 *
 * The object is .text only, 0x4c0 bytes, ZERO .rodata.
 */
/*
 * mini_golf.c -- REL module: isolated function lbl_0000F290.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dolphin.h>
#include "global.h"
#include "avdisp.h"
#include "ball.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "pool.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "stcoli.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "input.h"
#include "background.h"
#include "light.h"
#include "polydisp.h"
#include "gxcache.h"
#include "stdlib.h"
#include "effect.h"
#include "vibration.h"
#include "lens_flare.h"
#include "nl2ngc.h"
#include "shadow.h"
#include "ord_tbl.h"
#include "stobj.h"
#include "item.h"
#include "gxutil.h"
#include "rend_efc.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_golf.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_000260F0[];
extern u8 lbl_00026118[];
extern u8 lbl_00026158[];
extern u8 lbl_000261E8[];
extern u8 lbl_000261F0[];
extern u8 lbl_000262F0[];
extern u8 lbl_00026378[];
extern u8 lbl_00026380[];
extern u8 lbl_00026390[];
extern u8 lbl_000263B0[];
extern u8 lbl_000264A8[];
extern u8 lbl_000264C8[];
extern u8 lbl_000264E0[];
extern u8 lbl_00026510[];
extern u8 lbl_00026538[];
extern u8 lbl_00026550[];
extern u8 lbl_000266A0[];
extern u8 lbl_000266F8[];
extern u8 lbl_00026A38[];
extern u8 lbl_00026A44[];
extern u8 lbl_00026A60[];
extern u8 lbl_00026A98[];
extern u8 lbl_00026AA0[];
extern u8 lbl_00026AB0[];
extern u8 lbl_00026AC4[];
extern u8 lbl_00026AEC[];
extern u8 lbl_00026AF0[];
extern u8 lbl_00026AF4[];
extern u8 lbl_00026AF8[];
extern u8 lbl_00026B40[];
extern u8 lbl_00026BCC[];
extern u8 lbl_00026BE8[];
extern u8 lbl_00026D08[];
extern u8 lbl_00026D50[];
extern u8 lbl_00026DA0[];
extern u8 lbl_00026DF0[];
extern u8 lbl_00026DF4[];
extern u8 lbl_00026E10[];
extern u8 lbl_00026E28[];
extern u8 lbl_00026FB8[];
extern u8 lbl_0002A4D8[];
extern u8 lbl_0002A9E8[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000010[];
extern u8 lbl_1000003A[];
extern u8 lbl_1000003E[];
extern u8 lbl_10000046[];
extern u8 lbl_10000048[];
extern u8 lbl_1000005C[];
extern u8 lbl_100000C8[];
extern u8 lbl_100000D0[];
extern u8 lbl_100000EB[];
extern u8 lbl_100000ED[];
extern u8 lbl_100000F6[];
extern u8 lbl_100000F8[];
extern u8 lbl_100000FB[];
extern u8 lbl_10000100[];
extern u8 lbl_10000130[];
extern u8 lbl_10000170[];
extern u8 lbl_10000178[];
extern u8 lbl_10000190[];
extern u8 lbl_100001C8[];
extern u8 lbl_100001CA[];
extern u8 lbl_100001D4[];
extern u8 lbl_10000204[];
extern u8 lbl_10000210[];
extern u8 lbl_10000248[];

// Imported functions the code calls that no included header declares.
extern void u_load_minigame_graphics();
extern void u_set_minigame_callbacks_2();
extern void __cvt_fp2unsigned();
extern void draw_test_camera_target();
extern void func_800AB444();
extern void func_8009CD5C();
extern void func_800AB6F8();
extern void func_800AB2A0();
extern void func_800AC43C();
extern void func_8009C5E4();
extern void func_8009D794();
extern void func_800AC5E0();
extern void alloc_pool_light();
extern void mini_commend_free_data();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void lbl_000000C8(void);
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_0000027C(void);
void lbl_000002A8(void);
void lbl_000005CC(void);
void lbl_000056C4(void);
void lbl_00007F34(void);
void lbl_00008A44(void);
void lbl_00008C78(void);
void lbl_00008D34(void);
void lbl_00008F44(void);
void lbl_0000907C(void);
void lbl_00009178(void);
void lbl_000091BC(void);
void lbl_000092C4(void);
f32 lbl_000092D0(void);
void lbl_000092E0(void);
s16 lbl_000092F0(void);
void lbl_00009300(void);
void lbl_00009310(void);
void lbl_00009320(Vec *);
void lbl_00009340(Vec *);
void lbl_00009360(Vec *);
void lbl_00009384(s16 *);
void lbl_00009394(s16 *);
void lbl_000093A4(s16 *);
void lbl_000093B4(void);
void lbl_000093C4(void);
u8 lbl_000093D4(int a, int b);
void lbl_000093F0(void);
u8 lbl_00009404(void);
void lbl_00009414(void);
void lbl_00009424(void);
void lbl_00009438(void);
void lbl_00009448(void);
void lbl_00009458(void);
void lbl_00009478(void);
void lbl_00009488(void);
void lbl_00009538(void);
void lbl_000095C4(void);
void lbl_000097D8(void);
void lbl_00009800(void);
void lbl_0000982C(void);
void lbl_00009880(void);
void lbl_00009968(void);
void lbl_000099B4(void);
void lbl_000099E0(void);
void lbl_00009B68(void);
void lbl_00009C10(void);
void lbl_00009C50(void);
void lbl_0000B280(void);
void lbl_0000B36C(void);
void lbl_0000B754(void);
void lbl_0000B8A8(void);
void lbl_0000BDEC(void);
void lbl_0000C128(void);
void lbl_0000C230(void);
void lbl_0000C33C(void);
void lbl_0000D64C(void);
void lbl_0000E8AC(void);
void lbl_0000E998(void);
void lbl_0000E99C(void);
void lbl_0000F11C(void);
void lbl_0000F194(void);
void lbl_0000F290(struct Ball *ball);
void lbl_0000F7E8(struct Ball *ball);
void lbl_0000FA18(struct Ball *ball);
void lbl_0000FBC8(struct Ball *ball);
void lbl_0000FCE0(void);
void lbl_000100D4(void);
void lbl_00010304(struct Ball *ball, struct PhysicsBall *physBall, int c);
void lbl_000106B8(void);
void lbl_00010808(void);
void lbl_000109CC(void);
void lbl_00010E68(void);
void lbl_00010E74(void);
void lbl_00011254(void);
void lbl_000115F8(void);
void lbl_0001199C(void);
void lbl_00011A6C(void);
void lbl_00011DAC(void);
void lbl_00011FEC(void);
void lbl_000123B4(void);
void lbl_00012A14(void);
void lbl_00012C80(void);
void lbl_00012EEC(void);
void lbl_00013664(void);
void lbl_00015520(void);
void lbl_0001B5B8(void);
void lbl_00022524(void);
void lbl_00022610(void);
void lbl_00022904(void);
void lbl_00022D4C(void);
void lbl_000230E4(void);
void lbl_00023AB4(void);
void lbl_00023C68(void);
void lbl_00023DC4(void);
void lbl_00023DD4(void);
void lbl_000240C0(void);
void lbl_000245D4(void);
void lbl_000246E8(void);
void lbl_00024A40(void);
void lbl_00024E70(void);
void lbl_000252C0(void);
void lbl_0002544C(void);
void lbl_000255CC(void);
void lbl_00025928(void);
void lbl_00025A44(void);
void lbl_00025B10(void);
void lbl_00025B70(void);
void lbl_00025BD0(void);
void lbl_00025EA8(void);
void lbl_0002609C(void);
void lbl_000260C0(void);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
void lbl_0000F750(struct Ball *ball);

#pragma force_active on
void lbl_0000F290(struct Ball *ball)
{
    Vec sp34;
    s32 i;

    if (*(s16 *)lbl_00026DF0 != lbl_000092F0())
    {
        for (i = 0; i < modeCtrl.playerCount; i++)
        {
            ballInfo[i].pos = decodedStageLzPtr->startPos->pos;
            ballInfo[i].prevPos = decodedStageLzPtr->startPos->pos;
        }
        *(s16 *)lbl_00026DF0 = lbl_000092F0();
    }
    ball->pos.x = decodedStageLzPtr->startPos->pos.x;
    ball->pos.y = decodedStageLzPtr->startPos->pos.y +
                  0.5 * (24.0 * (24.0 * ball->accel));
    ball->pos.z = decodedStageLzPtr->startPos->pos.z;
    ball->prevPos = ball->pos;
    mathutil_mtxA_from_translate(&ball->pos);
    mathutil_mtxA_to_mtx(ball->unk30);
    ball->speed = ball->unkC4 = 0.0f;
    ball->unkB8 = (Vec){0.0f, 0.0f, 0.0f};
    ball->ape->flags &= ~0x4000;
    ball->unkA8 = (Quaternion){0.0f, 0.0f, 0.0f, 1.0f};
    ball->unk98 = ball->unkA8;
    ball->unk92 = decodedStageLzPtr->startPos->yrot;
    sp34.x = -mathutil_sin(ball->unk92);
    sp34.y = 0.0f;
    sp34.z = -mathutil_cos(ball->unk92);
    mot_ape_set_quat_from_vec(ball->ape, &sp34);
    lbl_00009340(&ball->prevPos);
    lbl_00009320(&ball->pos);
    lbl_000093A4(&ball->unk92);
    lbl_00009384(&ball->unk92);
    ball->colorId = modeCtrl.currPlayer;
    *(s32 *)lbl_10000170 = 0;
    *(u8 *)lbl_10000178 = 9;
    ball->state = 0x1A;
    ball->unk148 = 4;
}
void lbl_0000F750(struct Ball *ball)
{

    ball->unk92 = decodedStageLzPtr->startPos->yrot;
    lbl_00009340(&ball->prevPos);
    lbl_00009320(&ball->pos);
    lbl_000093A4(&ball->unk92);
    lbl_00009384(&ball->unk92);
    ball->vel.x = 0.0f;
    ball->vel.y = -1.0e-8f;
    ball->vel.z = 0.0f;
    ball->state = 0x1A;
    ball->unk148 = 4;
}
void lbl_0000F7E8(struct Ball *ball)
{
    struct PhysicsBall pb;
    u8 *st = (u8 *)lbl_10000170;
    s32 *cp;
    u32 limit;

    if (lbl_000093D4(*(cp = &modeCtrl.currPlayer), lbl_00009404()) == 1)
        limit = 0x21c;
    else if (lbl_000093D4(*cp, lbl_00009404()) == 2)
        limit = 0xf0;
    else if (lbl_000093D4(*cp, lbl_00009404()) == 3)
        limit = 0xf0;

    if (*(u32 *)(st + 0xc) >= 0 && *(u32 *)(st + 0xc) < limit) {
        ball->ape->flags &= ~0x4000;
        ball->prevPos.y = ball->pos.y;
        ball->pos.y = 2.0 + lbl_000092D0() +
                      0.5 * mathutil_sin(globalAnimTimer << 10);
        ball->vel.y = ball->pos.y - ball->prevPos.y;
        init_physball_from_ball(ball, &pb);
    } else if (*(u32 *)(st + 0xc) == limit) {
        ball->ape->flags |= 0x4000;
        ball->flags |= 0x40;
        cameraInfo[*cp].subState = 8;
        init_physball_from_ball(ball, &pb);
    } else {
        mathutil_mtxA_from_quat(&ball->ape->unk60);
        mathutil_mtxA_rotate_y(0x800);
        mathutil_mtxA_to_quat(&ball->ape->unk60);
        if (!(ball->flags & 0x200) && (ball->ape->flags & 0x4000)) {
            ball->flags &= ~0x500;
            ball->flags |= 0x200;
            u_play_sound_0(0x126);
        }
        lbl_00010304(ball, &pb, 0);
    }
    *(u32 *)(st + 0xc) += 1;
    handle_ball_rotational_kinematics(ball, &pb, 0);
    update_ball_ape_transform(ball, &pb, 0);
    ball->unk80 += 1;
}
#pragma peephole on
void lbl_0000FA18(struct Ball *ball)
{
    union { struct PhysicsBall pb; f64 a; } u;
    u8 *st = (u8 *)lbl_10000170;


    if (*(u32 *)(st + 0xc) >= 0 && *(u32 *)(st + 0xc) < 0x3c) {
        ball->ape->flags &= ~0x4000;
        ball->prevPos.y = ball->pos.y;
        ball->pos.y = 2.0 + lbl_000092D0() +
                      0.5 * mathutil_sin(globalAnimTimer << 10);
        ball->vel.y = ball->pos.y - ball->prevPos.y;
        init_physball_from_ball(ball, &u.pb);
    } else if (*(u32 *)(st + 0xc) == 0x3c) {
        ball->ape->flags |= 0x4000;
        ball->flags |= 0x40;
        cameraInfo[0].subState = 8;
        init_physball_from_ball(ball, &u.pb);
    } else {
        mathutil_mtxA_from_quat(&ball->ape->unk60);
        mathutil_mtxA_rotate_y(0x800);
        mathutil_mtxA_to_quat(&ball->ape->unk60);
        if (!(ball->flags & 0x200) && (ball->ape->flags & 0x4000)) {
            ball->flags &= ~0x500;
            ball->flags |= 0x200;
            u_play_sound_0(0x126);
        }
        lbl_00010304(ball, &u.pb, 0);
    }
    *(u32 *)(st + 0xc) += 1;
    handle_ball_rotational_kinematics(ball, &u.pb, 0);
    update_ball_ape_transform(ball, &u.pb, 0);
    ball->unk80 += 1;
}
#pragma peephole on
void lbl_0000FBC8(struct Ball *ball)
{
    Vec sp;

    ball->vel.x = 0.0f;
    ball->vel.y = -1.0e-7f;
    ball->vel.z = 0.0f;
    ball->unk80 = 0;
    ball->unk98.w = 1.0f;
    ball->unk98.x = 0.0f;
    ball->unk98.y = 0.0f;
    ball->unk98.z = 0.0f;
    lbl_00009360(&ball->pos);
    ball->pos.y = ball->pos.y + 0.5 * (24.0 * (24.0 * ball->accel));
    ball->prevPos = ball->pos;
    lbl_00009320(&ball->pos);
    lbl_00009394(&ball->unk92);
    sp.x = -mathutil_sin(ball->unk92);
    sp.y = 0.0f;
    sp.z = -mathutil_sin(ball->unk92 + 0x4000);
    mot_ape_set_quat_from_vec(ball->ape, &sp);
    ball->state = 0x1a;
    ball->unk148 = 4;
}
#pragma force_active reset
