/*
 * mini_pilot.c -- REL module: isolated function lbl_000008AC.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "game.h"
#include "input.h"
#include "item.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "ord_tbl.h"
#include "pause_menu.h"
#include "pool.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "stcoli.h"
#include "vibration.h"
#include "window.h"
#include "avdisp.h"
#include "background.h"
#include "effect.h"
#include "gxutil.h"
#include "hud.h"
#include "info.h"
#include "lens_flare.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "rend_efc.h"
#include "shadow.h"
#include "spline.h"
#include "stobj.h"
#include "world.h"
#include "stdlib.h"
#include "thread.h"

struct PilotRodata0
{
    /*0x00*/ u8 filler0[0x58];
    /*0x58*/ f32 randMax;    // 32767.0f
    /*0x5C*/ u8 filler5C[0xC];
    /*0x68*/ f64 half;       // 0.5
    /*0x70*/ f64 four;       // 4.0
    /*0x78*/ f64 forty;      // 40.0
};
struct PilotBananaSpawn
{
    /*0x00*/ f32 x;
    /*0x04*/ f32 y;
    /*0x08*/ f32 z;
    /*0x0C*/ f32 spread;
    /*0x10*/ s8 count;
    /*0x11*/ u8 pad[3];
};  // size = 0x14
// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_pilot.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000BE80[];
extern u8 lbl_0000BEB0[];
extern u8 lbl_0000BEB4[];
extern u8 lbl_0000BEE0[];
extern u8 lbl_0000BFD0[];
extern u8 lbl_0000BFE0[];
extern u8 lbl_0000BFE8[];
extern u8 lbl_0000C010[];
extern u8 lbl_0000C030[];
extern u8 lbl_0000C2A8[];
extern u8 lbl_0000C2C8[];
extern u8 lbl_0000C2F0[];
extern u8 lbl_0000C348[];
extern u8 lbl_0000C358[];
extern u8 lbl_0000C360[];
extern u8 lbl_0000C3C0[];
extern u8 lbl_0000C3C8[];
extern u8 lbl_0000C3CC[];
extern u8 lbl_0000C430[];
extern u8 lbl_0000C548[];
extern u8 lbl_0000C5B8[];
extern u8 lbl_0000C5C0[];
extern u8 lbl_0000C690[];
extern u8 lbl_0000C6D8[];
extern u8 lbl_0000C740[];
extern u8 lbl_0000C748[];
extern u8 lbl_0000C7BC[];
extern u8 lbl_0000C7CC[];
extern u8 lbl_0000C7EC[];
extern u8 lbl_0000C88C[];
extern u8 lbl_0000CB0C[];
extern u8 lbl_0000CBCC[];
extern u8 lbl_0000CCF8[];
extern u8 lbl_0000D1C8[];
extern u8 lbl_0000D218[];
extern u8 lbl_0000D2E8[];
extern u8 lbl_0000D300[];
extern u8 lbl_0000D314[];
extern u8 lbl_0000D320[];
extern u8 lbl_0000D324[];
extern u8 lbl_0000D328[];
extern u8 lbl_0000D338[];
extern u8 lbl_0000D360[];
extern u8 lbl_0000D368[];
extern u8 lbl_0000D3A0[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000018[];
extern u8 lbl_1000001E[];
extern u8 lbl_10000020[];
extern u8 lbl_10000034[];
extern u8 lbl_10000038[];
extern u8 lbl_1000003C[];
extern u8 lbl_10000040[];
extern s32 lbl_10000044[];
extern u8 lbl_10000054[];
extern u8 lbl_1000005C[];
extern u8 lbl_10000064[];
extern u8 lbl_10000066[];
extern u8 lbl_10000068[];
extern u8 lbl_10000074[];
extern u8 lbl_10000078[];
extern u8 lbl_10000087[];
extern u8 lbl_10000088[];
extern u8 lbl_1000008A[];
extern u8 lbl_1000008C[];
extern u8 lbl_10000090[];
extern u8 lbl_10000098[];
extern u8 lbl_100000A8[];
extern u8 lbl_100000B0[];
extern u8 lbl_100000B8[];
extern u8 neutralFaceTable[];
extern u8 smileFaceTable[];
extern u8 lbl_80285A58[];
extern u8 lbl_802F1F10[];
extern u32 lbl_802F1FD0;
extern u8 lbl_802F1FD8[];
extern u8 lbl_802F1FDC[];
extern u8 lbl_802F1FE0[];
extern u8 lbl_802F1FE4[];
extern s16 lbl_802F1FEC;
extern s16 lbl_802F1FF4;

// Imported functions the code calls that no included header declares.
extern void ball_8003BBF4();
extern void draw_test_camera_target();
extern void func_80042214();
extern void func_8009C5E4();
extern void func_8009CD5C();
extern void func_8009DB40();
extern void func_800AB2A0();
extern void func_800AB444();
extern void gxutil_draw_line_multicolor();
extern void item_create();
extern void mini_commend_free_data();
extern void qsort();
extern void set_shape_flags_in_model();
extern void stcoli_sub35();
extern void u_load_minigame_graphics();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_000001F8(void);
void lbl_000003B4(void);
void lbl_0000044C(void);
void lbl_000004E0(void);
void lbl_00000648(void);
void lbl_0000066C(void);
void lbl_00000698(void);
void lbl_000007B8(void);
void lbl_000008AC(void);
void lbl_00000A30(void);
void lbl_00000BFC(void);
void lbl_0000215C(void);
void lbl_000021B4(void);
void lbl_000022D8(void);
void lbl_00003B6C(void);
void lbl_00003BDC(void);
void lbl_00004024(void);
void lbl_000040EC(u8 *p);
void lbl_00004450(void);
void lbl_00004570(void);
void lbl_000048C0(void);
void lbl_00004A14(void);
void lbl_00004E84(void);
void lbl_0000580C(void);
void lbl_00006A94(void);
void lbl_00006B5C(void);
void lbl_00006B94(void);
void lbl_00006DFC(void);
void lbl_00007EF8(void);
void lbl_00008134(void);
void lbl_000082C0(void);
void lbl_00008568(void);
void lbl_000085B4(void);
void lbl_0000893C(void);
void lbl_000089F8(void);
void lbl_00008C40(void);
void lbl_000090A0(void);
void lbl_000091EC(void);
void lbl_00009440(void);
void lbl_000097AC(void);
void lbl_000097C8(void);
void lbl_000099A4(void);
void lbl_00009A98(void);
void lbl_00009B04(void);
void lbl_00009C18(void);
void lbl_00009F4C(void);
void lbl_00009FB0(void);
void lbl_0000A098(void);
void lbl_0000A69C(void);
void lbl_0000A754(void);
void lbl_0000AE94(void);
void lbl_0000AEE0(void);
void lbl_0000AF68(void);
void lbl_0000B130(void);
void lbl_0000B624(void);
void lbl_0000BACC(void);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
s32 lbl_00000DC8(struct PilotTgt *tgt, Vec *pos);
void lbl_0000101C(void);
void lbl_000011CC(void);
void lbl_000015D8(void);
void lbl_0000178C(void);
void lbl_00001B08(void);
void lbl_00001BB4(void);
void lbl_00001CE4(void);
void lbl_00001DE0(void);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
struct PilotPlayRec
{
    s16 s[3];
};
extern struct PilotPlayRec lbl_80285A68[];
void lbl_0000AD6C(u32 mulColor, u32 addColor, f32 x, f32 y, char *fmt, ...);
struct PilotTgtRow
{
    s16 unk0;
    s16 unk2;
    s16 unk4;
    s16 unk6;
    s16 unk8;
    s16 unkA;
};
extern struct PilotTgtRow lbl_80285A80[];
void lbl_0000B000(void);
union PilotV
{
    Vec v;
    f64 align;
};
void lbl_000023BC(void);
void lbl_00002408(void);
void lbl_000024D0(void);
void lbl_0000253C(void);
void lbl_000026BC(void);
void lbl_00002890(void);
void lbl_00002A2C(void);
void lbl_00002AE8(void);
void lbl_00002C18(void);
void lbl_00002D24(void);
void lbl_00002E04(void);
void lbl_00002E94(void);
void lbl_00002EB4(void);
void lbl_00002FF4(void);
void lbl_00003298(void);
void lbl_00003374(void);
void lbl_000035B8(void);
void lbl_00003860(void);
void lbl_000038D4(void);
void lbl_00003AD0(void);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
struct PilotResultRec
{
    u8 filler0[4];
    /*0x04*/ s16 unk4;
    /*0x06*/ u8 filler6[2];
    /*0x08*/ s16 unk8;
    /*0x0A*/ u8 fillerA[2];
};
void lbl_00006BF4(struct Ball *);
extern int func_800AC5E0();
int lbl_00006D14(void);
extern int func_8009D794();
extern int func_800AC43C(int, void *, int);
extern int func_800AB6F8();
void lbl_00006CCC(f32 *outU, f32 *outV, f32 dist, f32 x, f32 y, f32 fovScale);
void lbl_00004F68(struct Ball *ball);
void lbl_00004FA8(struct Ball *ball);
void lbl_00005008(struct Ball *ball);
void lbl_00005044(struct Ball *ball);
void lbl_00006124(struct Ball *, struct PhysicsBall *, int);
void lbl_0000509C(struct Ball *ball);
void lbl_00005824(struct Ball *ball);
void lbl_00006490(struct Ball *, struct PhysicsBall *, int);
void lbl_0000669C(struct Ball *, struct PhysicsBall *, int);
void lbl_000051A4(struct Ape *ape, int status);
void lbl_00005414(struct Ape *ape, f32 speed);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).

#pragma force_active on
void lbl_000008AC(void)
{
    struct PilotRodata0 *k = (struct PilotRodata0 *)lbl_0000BE80;
    struct Item item;
    struct PilotBananaSpawn *sp;
    int i;
    int j;
    // The original reserves one more 4-byte frame slot after `item` for a local
    // it never reads or writes.  Its name/type are unrecoverable; without it the
    // whole local block sits 4 bytes lower.
    s32 unused;

    memset(&item, 0, sizeof(item));
    item.type = 5;
    item.subType = 4;
    item.animGroupId = 0;

    sp = ((struct PilotBananaSpawn **)lbl_0000CBCC)[*(s16 *)lbl_10000040];
    for (i = 0; i < 3; i++, sp++)
    {
        for (j = 0; j < sp->count; j++)
        {
            item.pos.x = sp->x + sp->spread * (rand() / k->randMax - k->half);
            item.pos.y = k->four + sp->y + k->forty * (rand() / k->randMax);
            item.pos.z = sp->z + sp->spread * (rand() / k->randMax - k->half);
            item_create(&item);
        }
    }
}
struct PilotTgt
{
    /*0x00*/ Vec pos;
    /*0x0C*/ f32 unkC;
    /*0x10*/ f32 unk10;
    /*0x14*/ s8 unk14;
    /*0x15*/ u8 pad15[3];
};
struct PilotIdTbl3 { s16 v[3]; };
struct PilotIdTbl6 { s16 v[6]; };
// Each of the three per-stage tables at k+0x80.. is copied into its own local
// as a whole object, so each needs a struct type -- the same shape
// lbl_00000DC8 below already uses for PilotIdTbl3/6.  The three destinations
// sit at DESCENDING frame addresses for ASCENDING source offsets, which is
// what rules out a single 0x1C-byte copy of one combined struct.
struct PilotTgtTbl  { struct PilotTgt *v[3]; };
struct PilotPickTbl { s8 *v[3]; };
struct PilotCntTbl  { s8 v[3]; };

// The pilot target-item spawner, and its twin lbl_00000BFC below: same routine
// over the second table group (k+0x9C/0xA8/0xB4) with subType 1.
//
// Two spellings are load-bearing and were worth 40 aligned in 25 between them:
//   * `Vec *pp;` + `pp = &pos;` as a STATEMENT.  Without the pointer local the
//     call site recomputes `addi r4,r1,8` every iteration and the function is
//     one instruction (and one callee-saved GPR, and 8 frame bytes) short of
//     the original, which hoists `&pos` into r28.  As a declaration
//     INITIALISER the hoist happens but lands in the prologue instead of
//     after the memset, which is 2 aligned in 2.
//   * declaration order pp,i,tgt,base,spread,pick -- a middle permutation of
//     the 36 tried; every one of them is a byte-identical schedule and differs
//     only in callee-saved numbering.
#pragma peephole on
void lbl_00000A30(void)
{
    u8 *k = (u8 *)lbl_0000BE80;
    struct Item item;
    struct PilotTgtTbl tgts;
    struct PilotPickTbl picks;
    struct PilotCntTbl counts;
    Vec pos;
    Vec *pp;
    int i;
    struct PilotTgt *tgt;
    struct PilotTgt *base;
    f32 spread;
    s8 *pick;

    tgts = *(struct PilotTgtTbl *)(k + 0x80);
    picks = *(struct PilotPickTbl *)(k + 0x8C);
    counts = *(struct PilotCntTbl *)(k + 0x98);
    base = tgts.v[*(s16 *)lbl_10000040];
    pick = picks.v[*(s16 *)lbl_10000040];
    memset(&item, 0, sizeof(item));
    pp = &pos;
    item.type = 5;
    for (i = 0; i < counts.v[*(s16 *)lbl_10000040]; i++)
    {
        tgt = &base[pick[rand() & 0xF]];
        spread = tgt->unkC;
        item.pos.x = tgt->pos.x
            + (spread * (rand() / *(f32 *)(k + 0x58))
               - *(f64 *)(k + 0x68) * spread);
        item.pos.y = tgt->pos.y;
        spread = tgt->unk10;
        item.pos.z = tgt->pos.z
            + (spread * (rand() / *(f32 *)(k + 0x58))
               - *(f64 *)(k + 0x68) * spread);
        pos = item.pos;
        item.animGroupId = lbl_00000DC8(tgt, pp);
        item.subType = 3;
        item_create(&item);
    }
}

#pragma peephole on
void lbl_00000BFC(void)
{
    u8 *k = (u8 *)lbl_0000BE80;
    struct Item item;
    struct PilotTgtTbl tgts;
    struct PilotPickTbl picks;
    struct PilotCntTbl counts;
    Vec pos;
    Vec *pp;
    int i;
    struct PilotTgt *tgt;
    struct PilotTgt *base;
    f32 spread;
    s8 *pick;

    tgts = *(struct PilotTgtTbl *)(k + 0x9C);
    picks = *(struct PilotPickTbl *)(k + 0xA8);
    counts = *(struct PilotCntTbl *)(k + 0xB4);
    base = tgts.v[*(s16 *)lbl_10000040];
    pick = picks.v[*(s16 *)lbl_10000040];
    memset(&item, 0, sizeof(item));
    pp = &pos;
    item.type = 5;
    for (i = 0; i < counts.v[*(s16 *)lbl_10000040]; i++)
    {
        tgt = &base[pick[rand() & 0xF]];
        spread = tgt->unkC;
        item.pos.x = tgt->pos.x
            + (spread * (rand() / *(f32 *)(k + 0x58))
               - *(f64 *)(k + 0x68) * spread);
        item.pos.y = tgt->pos.y;
        spread = tgt->unk10;
        item.pos.z = tgt->pos.z
            + (spread * (rand() / *(f32 *)(k + 0x58))
               - *(f64 *)(k + 0x68) * spread);
        pos = item.pos;
        item.animGroupId = lbl_00000DC8(tgt, pp);
        item.subType = 1;
        item_create(&item);
    }
}

#pragma peephole on
s32 lbl_00000DC8(struct PilotTgt *tgt, Vec *pos)
{
    u8 *k = (u8 *)lbl_0000BE80;
    u8 *tgtTbl = (u8 *)lbl_0000C740;
    // The original reserves an 8-byte frame slot at 0x54..0x5B that it never
    // reads or writes (frame is 0x60 with only r31 saved; the live locals stop
    // at 0x54).  Its name/type are unrecoverable -- without it the whole local
    // block, and hence every stack offset below, moves.

    if (tgt == (struct PilotTgt *)(tgtTbl + 0x4B0))
    {
        f32 dist = mathutil_unk(tgt->pos.x, tgt->pos.z, pos->x, pos->z);

        if (dist < *(f64 *)(k + 0xD8))
            return 4;
        if (dist < *(f64 *)(k + 0xE0))
            return 3;
        return 2;
    }
    if (tgt == (struct PilotTgt *)(tgtTbl + 0x528))
    {
        Vec delta;
        struct PilotIdTbl3 ids = *(struct PilotIdTbl3 *)(k + 0xB8);

        delta.x = pos->x - tgt->pos.x;
        delta.y = pos->y - tgt->pos.y;
        delta.z = pos->z - tgt->pos.z;
        return ids.v[(u16)mathutil_atan2(-delta.x, -delta.z) / (0x10000 / 3)];
    }
    if (tgt == (struct PilotTgt *)(tgtTbl + 0x540))
    {
        Vec delta;
        struct PilotIdTbl6 ids = *(struct PilotIdTbl6 *)(k + 0xC0);

        delta.x = pos->x - tgt->pos.x;
        delta.y = pos->y - tgt->pos.y;
        delta.z = pos->z - tgt->pos.z;
        return ids.v[(u16)mathutil_atan2(-delta.x, -delta.z) / (0x10000 / 6)];
    }
    if (tgt == (struct PilotTgt *)(tgtTbl + 0x558))
    {
        Vec delta;
        struct PilotIdTbl6 ids = *(struct PilotIdTbl6 *)(k + 0xCC);

        delta.x = pos->x - tgt->pos.x;
        delta.y = pos->y - tgt->pos.y;
        delta.z = pos->z - tgt->pos.z;
        return ids.v[(u16)mathutil_atan2(-delta.z, delta.x) / (0x10000 / 6)];
    }
    return tgt->unk14;
}

#pragma peephole on
void lbl_0000101C(void)
{
    u8 *w = (u8 *)lbl_10000000;
    s32 p = modeCtrl.currPlayer;
    s32 pad[6];

    *(s32 *)(w + p * 4 + 0x44) += ((s32 *)lbl_80285A58)[p];
    ((s32 *)lbl_80285A58)[p] = 0;
    lbl_802F1FEC = 0;
    {
    s16 *a = (s16 *)((u8 *)lbl_80285A80 + p * 12);
    s16 *b = (s16 *)((u8 *)lbl_80285A68 + p * 6);
    a[0] = 0;
    a[1] = 0;
    a[2] = 0;
    a[3] = 0;
    a[4] = 0;
    a[5] = 0;
    b[0] = 0;
    b[1] = 0;
    b[2] = 0;
    }
    SoundOffID(0xef);
    SoundOffID(0xf9);
    SoundOffID(0xf3);
    u_play_music(100, 8);
    u_init_player_data_2();
    if (modeCtrl.currPlayer == 0)
    {
        if (*(s16 *)(w + 0x66) >= *(s16 *)(w + 0x64))
        {
            event_finish_all();
            lbl_802F1FF6 = 0x17;
            lbl_802F1FF4 = -1;
            ((void (**)(void))lbl_0000C748)[23]();
            return;
        }
        if (++*(s16 *)(w + 0x40) >= 3)
            *(s16 *)(w + 0x40) = 0;
        *(s16 *)(w + 0x66) += 1;
    }
    lbl_00000698();
    if (lbl_802F1FF4 != -1)
    {
        lbl_802F1FF6 = lbl_802F1FF4;
        lbl_802F1FF4 = -1;
    }
    ((void (**)(void))lbl_0000C748)[lbl_802F1FF6]();
}

asm void lbl_000011CC(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_pilot/lbl_000011CC.s"
}

#pragma peephole on
void lbl_00001538(void)
{
    struct Ball *ball = currentBall;

    if (lbl_802F1FF0++ == 0)
    {
        ball->state = BALL_STATE_23;
        ball->unk148 = 0;
        ball->flags &= ~BALL_FLAG_INVISIBLE;
        ball->ape->flags &= ~APE_FLAG_INVISIBLE;
        ball->flags |= BALL_FLAG_14;
        return;
    }
    if (lbl_802F1FF0 >= 0x78)
    {
        if (lbl_802F1FD0 & (1 << 4))
            lbl_802F1FF4 = 3;
        else
            lbl_802F1FF4 = 9;
    }
}

asm void lbl_000015D8(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_pilot/lbl_000015D8.s"
}

// The pilot intro state machine.  One spelling is load-bearing and cost four
// variants: the id-table read has to be `(s8)(w + i)[0x78]` -- a u8 subscript on
// the index-advanced base, narrowed afterwards.  `*(s8 *)(w + 0x78 + i)`,
// `*(s8 *)(w + i + 0x78)` and `((s8 *)(w + i))[0x78]` all fold the 0x78 into the
// INDEX and emit `addi`+`lbzx`, where the original keeps it as the load
// displacement (`add`+`lbz 0x78`).  6 aligned in 2 regions for each of those.
#pragma peephole on
void lbl_0000178C(void)
{
    u8 *w = (u8 *)lbl_10000000;
    struct Ball *ball = currentBall;
    u8 *k = (u8 *)lbl_0000BE80;
    s16 st;

    lbl_802F1FF0++;
    st = *(s16 *)(w + 0x88);
    if (st >= 2)
        *(s32 *)(w + 0x8C) += 1;

    switch (st)
    {
    case 0:
        if (((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button
              & PAD_BUTTON_A)
             && lbl_802F1FF0 > 15)
            || lbl_802F1FF0 > 0x4B0)
        {
            u_play_sound_0(0x10);
            *(s16 *)(w + 0x88) = 1;
        }
        break;
    case 1:
        *(f32 *)(w + 0x24) *= *(f64 *)(k + 0xF8)
            + *(f64 *)(k + 0x100) * (rand() / *(f32 *)(k + 0x58));
        if (*(f32 *)(w + 0x24) < *(f64 *)(k + 0x108))
        {
            *(s16 *)(w + 0x88) = 2;
            *(f32 *)(w + 0x24) = *(f32 *)(k + 0x30);
        }
        break;
    case 2:
        if (*(s32 *)(w + 0x8C) > 30)
        {
            if ((s8)(w + *(s8 *)(w + 0x90))[0x78] != -1)
            {
                lbl_802F1FD0 |= 0x800;
                u_play_sound_0(0x1A6);
                u_play_music(0, 8);
            }
            else
            {
                u_play_sound_0(0x1A8);
            }
            *(s16 *)(w + 0x88) = 3;
        }
        break;
    case 3:
        if (*(s32 *)(w + 0x8C) == 45)
        {
            if ((s8)(w + *(s8 *)(w + 0x90))[0x78] != -1)
                u_play_sound_0(0x392C);
            else
                u_play_sound_0(0x392E);
        }
        else if (*(s32 *)(w + 0x8C) == 60)
        {
            if (lbl_802F1FD0 & 0x800)
                u_play_sound_0(0x121);
        }
        if (*(s32 *)(w + 0x8C) > 160
            || (*(s32 *)(w + 0x8C) > 90
                && (controllerInfo[playerControllerIDs[ball->playerId]].pressed.button
                    & PAD_BUTTON_A)))
        {
            u_play_music(100, 8);
            *(s32 *)(w + 0x8C) = 160;
            *(s16 *)(w + 0x88) = 4;
        }
        break;
    case 4:
        if (*(s32 *)(w + 0x8C) > 180)
        {
            if (lbl_802F1FD0 & 0x800)
                lbl_802F1FF4 = 5;
            else
                lbl_802F1FF4 = 9;
        }
        break;
    }

    *(s16 *)(w + 0x8A) -= (s32)*(f32 *)(w + 0x24);
    *(s8 *)(w + 0x90) = *(u16 *)(w + 0x8A) * *(s8 *)(w + 0x87) / 0x10000;
    if (*(s8 *)(w + 0x90) != *(s8 *)(w + 0x22) && *(s8 *)(w + 0x23) == 0)
    {
        u_play_sound_0(0x3B136);
        *(s8 *)(w + 0x23) = 3;
    }
    if (*(s8 *)(w + 0x23) > 0)
        *(s8 *)(w + 0x23) -= 1;
    *(s8 *)(w + 0x22) = *(s8 *)(w + 0x90);
}

void lbl_00001B08(void)
{
    struct Ball *ball = currentBall;

    if (((s8 *)lbl_10000078)[*(s8 *)lbl_10000090] != 0)
        cameraInfo[ball->playerId].subState = 6;
    lbl_802F1FF0 = 0;
    lbl_802F1FF6 = 6;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[6]();
}

void lbl_00001BB4(void)
{
    struct Ball *ball = currentBall;
    s32 t;

    lbl_802F1FF0++;
    t = lbl_802F1FF0;
    if (t == 0x14)
    {
        lbl_000022D8();
    }
    else if (t == 0x50)
    {
        if (cameraInfo[ball->playerId].subState == 7)
            u_play_sound_0(0x122);
    }
    else if (t > 0x78
          && ((struct PilotPlayRec *)lbl_80285A68)[modeCtrl.currPlayer].s[0] != 0)
    {
        lbl_802F1FF4 = 9;
        return;
    }
    t = lbl_802F1FF0;
    if (t > 0x3c)
    {
        if ((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button & 0x100)
         || t > 0x21c)
        {
            SoundOffID(0x122);
            lbl_802F1FF4 = 9;
        }
    }
}

void lbl_00001CE4(void)
{
    s32 i = currentBall->playerId * sizeof(struct Camera);
    s8 *sub = &cameraInfo[0].subState;

    if (sub[i] != 1)
        sub[i] = 0;

    if (((s16 *)lbl_802F1FE4)[modeCtrl.currPlayer] == 0)
    {
        lbl_802F1FF6 = 7;
        lbl_802F1FF4 = -1;
        ((void (**)(void))lbl_0000C748)[7]();
    }
    else
    {
        *(s16 *)lbl_10000020 = 0;
        lbl_802F1FF0 = 0;
        *(s32 *)lbl_1000008C = -1;
        lbl_802F1FF6 = 10;
        lbl_802F1FF4 = -1;
        ((void (**)(void))lbl_0000C748)[10]();
    }
}

void lbl_00001DE0(void)
{
    u8 *m = (u8 *)lbl_10000000;
    struct Ball *ball = currentBall;
    u8 *k = (u8 *)lbl_0000BE80;
    char *s = (char *)lbl_0000C740;
    NLsprarg params;
    u32 c2;
    u32 c1;
    f32 x;
    f32 y;
    f64 ny;

    lbl_802F1FF0++;
    if (lbl_802F1FF0 < 20)
        return;

    x = *(f32 *)(k + 0x110);
    y = *(f32 *)(k + 0x114);

    if (*(s32 *)(m + 0x8C) < 30)
    {
        if (*(s16 *)(m + 0x20) != 0)
        {
            c1 = 0xFFFFFF80;
            c2 = 0xFF808080;
        }
        else
        {
            c1 = 0xFF808080;
            c2 = 0xFFFFFF80;
        }
        if (*(s32 *)(m + 0x8C) >= 0 && (globalAnimTimer & 4))
        {
            c1 &= 0xFF808080;
            c2 &= 0xFF808080;
        }

        params.zm_x = *(f32 *)(k + 0x34);
        params.zm_y = *(f32 *)(k + 0x34);
        params.u0 = params.v0 = *(f32 *)(k + 0x30);
        params.u1 = params.v1 = *(f32 *)(k + 0x34);
        params.ang = 0;
        params.listType = NLSPR_LISTTYPE_AUTO;
        params.attr = 5;
        params.trnsl = *(f32 *)(k + 0x34);
        params.base_color = 0x00FFFFFF;
        params.offset_color = 0;
        params.zm_x = *(f32 *)(k + 0x118);
        params.zm_y = *(f32 *)(k + 0x11C);
        params.sprno = 0xB31;
        params.x = *(f32 *)(k + 0x110);
        params.y = *(f32 *)(k + 0x114) - *(f64 *)(k + 0x120);
        params.z = *(f32 *)(k + 0x128);
        nlSprPut(&params);

        reset_text_draw_settings();
        set_text_font(0xB1);
        func_80071B50(0x200000);
        lbl_0000AD6C(0x00FFFFFF, 0, *(f64 *)(k + 0x130) + x, y, s + 0x5A0);
        lbl_0000AD6C(c1, 0, *(f64 *)(k + 0x138) + (*(f64 *)(k + 0x140) + x), ny = *(f64 *)(k + 0x130) + y, s + 0x5AC);
        lbl_0000AD6C(c2, 0, *(f64 *)(k + 0x138) + (*(f64 *)(k + 0x148) + x), ny, s + 0x5B0);
    }

    if (lbl_802F1FF0 < 30)
        return;

    if (*(s32 *)(m + 0x8C) == -1)
    {
        if ((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button
             & (PAD_BUTTON_LEFT | PAD_BUTTON_RIGHT))
         || (analogInputs[playerControllerIDs[ball->playerId]].pressed
             & (ANALOG_STICK_LEFT | ANALOG_STICK_RIGHT)))
        {
            u_play_sound_0(9);
            *(s16 *)(m + 0x20) ^= 1;
        }
        if ((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button & PAD_BUTTON_A)
         && lbl_802F1FF0 > 38)
        {
            if (*(s16 *)(m + 0x20) != 0)
            {
                lbl_802F1FD0 |= 0x400;
                lbl_0000215C();
                lbl_000021B4();
                u_play_sound_0(0x10);
                u_play_music(0, 8);
            }
            else
            {
                u_play_sound_0(0x36);
            }
            *(s32 *)(m + 0x8C) = 0;
        }
    }
    else
    {
        *(s32 *)(m + 0x8C) += 1;
        if (lbl_802F1FD0 & 0x400)
        {
            if (*(s32 *)(m + 0x8C) == 20)
                u_play_sound_0(0x11E);
            else if (*(s32 *)(m + 0x8C) >= 0x73)
                lbl_802F1FF4 = 7;
        }
        else
        {
            if (*(s32 *)(m + 0x8C) >= 30)
                lbl_802F1FF4 = 7;
        }
    }
}

void lbl_0000215C(void)
{
    s32 player = modeCtrl.currPlayer;
    s16 *p = &((s16 *)lbl_802F1FE4)[player];

    if (*p != 0)
        ((s16 *)((u8 *)lbl_80285A80 + player * 12))[*p]++;
    *p = 0;
}
void lbl_000021B4(void)
{
    if (lbl_80285A80[modeCtrl.currPlayer].unk2 != 0) {
    {
        union PilotV a;
        union PilotV b;

        a.v = *(Vec *)lbl_0000BFD0;
        b.v = *(Vec *)&a.v;
        *(Vec *)lbl_10000068 = b.v;
        *(Vec *)lbl_100000B8 = b.v;
        u_play_sound_0(0x1A2);
    }
    } else if (lbl_80285A80[modeCtrl.currPlayer].unk4 != 0) {
        u_play_sound_0(0x19D);
    } else if (lbl_80285A80[modeCtrl.currPlayer].unk8 != 0) {
        u_play_sound_0(0x1B6);
    } else if (lbl_80285A80[modeCtrl.currPlayer].unk6 != 0) {
        u_play_sound_0(0x19F);
    } else if (lbl_80285A80[modeCtrl.currPlayer].unkA != 0) {
        u_play_sound_0(0x1AC);
    }
}
void lbl_000022D8(void)
{
    s16 *c;
    struct PilotPlayRec *rec;

    rec = &lbl_80285A68[modeCtrl.currPlayer];
    c = &rec->s[((s8 *)lbl_10000078)[*(s8 *)lbl_10000090]];
    *c = *c + 1;
    if (rec->s[2] != 0)
    {
        u_play_sound_0(0x1b1);
        lbl_00000A30();
    }
    if (lbl_80285A68[modeCtrl.currPlayer].s[1] != 0)
    {
        u_play_sound_0(0x1aa);
        lbl_000008AC();
    }
    if (lbl_80285A68[modeCtrl.currPlayer].s[0] != 0)
        u_play_sound_0(0x1b3);
}

void lbl_000023BC(void)
{
    u_play_music(100, 8);
    hud_show_ready_banner(0x78);
    lbl_802F1FF0 = 0;
    lbl_802F1FF4 = 8;
}

void lbl_00002408(void)
{
    struct Ball *ball = currentBall;

    lbl_802F1FF0++;
    if (*(f64 *)lbl_0000BFE0 == lbl_802F1FF0)
    {
        u_somePlayerId = ball->playerId;
        lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
        u_play_sound_0(0x1E);
    }
    if (lbl_802F1FF0 > 0x78)
        lbl_802F1FF4 = 0xB;
}

void lbl_000024D0(void)
{
    event_resume(2);
    hud_show_go_banner(0x3c);
    lbl_802F1FF0 = 0;
    lbl_802F1FF6 = 12;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[12]();
}

void lbl_0000253C(void)
{
    struct Ball *ball = currentBall;

    lbl_802F1FF0++;
    if ((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button & 0x100)
     && !((ball->flags & BALL_FLAG_00)
       && mathutil_vec_len(&ball->vel) < *(f64 *)lbl_0000BFE8)
     && lbl_802F1FF0 > 60)
    {
        lbl_802F1FF4 = 0xd;
        return;
    }
    if (*(s16 *)lbl_10000018 == 0 && (ball->ape->flags & 2)
     && lbl_802F1FF0 % 30 == 1)
    {
        u_somePlayerId = ball->playerId;
        lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
        u_play_sound_0(((s16 *)lbl_0000BE80)[(rand() >> 12) & 7]);
    }
    lbl_00004A14();
}

void lbl_000026BC(void)
{
    u8 *k = (u8 *)lbl_0000BE80;
    u8 *w = (u8 *)lbl_10000000;
    struct Ball *ball = currentBall;
    Quaternion q;

    *(f32 *)(w + 4) = *(f32 *)(k + 0x180);
    q = *(Quaternion *)(k + 0x170);
    ball->unk98 = q;
    mathutil_mtxA_sq_from_identity();
    if (mathutil_sum_of_sq_2(ball->vel.x, ball->vel.z) > *(f64 *)(k + 0x188)
     || (ball->flags & BALL_FLAG_00))
        mathutil_mtxA_rotate_y(mathutil_atan2(-ball->vel.x, -ball->vel.z));
    mathutil_mtxA_sq_to_mtx(ball->unk30);
    ball->unk148 = 1;
    cameraInfo[ball->playerId].subState = 2;
    ball->flags |= 0x10;
    lbl_802F1FD0 |= 0x100;
    u_play_sound_0(0xf0);
    if (*(s16 *)(w + 0x18) == 0)
        *(s32 *)(w + 0x2c) = u_play_sound_2(0xef);
    vibration_control(playerControllerIDs[ball->playerId], 1, 10);
    lbl_802F1FF0 = 0;
    lbl_802F1FF4 = 0xe;
    if (lbl_802F1FF4 != -1)
    {
        lbl_802F1FF6 = lbl_802F1FF4;
        lbl_802F1FF4 = -1;
    }
    ((void (**)(void))lbl_0000C748)[lbl_802F1FF6]();
}

void lbl_00002890(void)
{
    struct Ball *ball = currentBall;

    lbl_802F1FF0++;
    if (lbl_802F1FF0 == 0x11)
    {
        u_somePlayerId = ball->playerId;
        lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
        u_play_sound_0(0x1f);
    }
    if ((lbl_802F1FD0 & 2) && (ball->ape->flags & 2)
     && lbl_802F1FF0 % 30 == 1)
    {
        u_somePlayerId = ball->playerId;
        lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
        u_play_sound_0(((s16 *)lbl_0000BE80)[(rand() >> 12) & 7]);
    }
    if ((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button & 0x100)
     && *(f32 *)lbl_802F1FDC >= *(f64 *)lbl_0000C010)
        lbl_802F1FF4 = 0x11;
    else
        lbl_00004A14();
}

void lbl_00002A2C(void)
{
    struct Ball *ball = currentBall;
    u8 *k = (u8 *)lbl_0000BE80;

    lbl_802F1FD0 |= 0x20;
    if (*(f32 *)lbl_802F1FDC >= *(f64 *)(k + 0x198))
        *(f32 *)lbl_802F1FDC = *(f32 *)(k + 0x1a0);
    ball->restitution = *(f32 *)(k + 0x1a4);
    SoundOffID(0xef);
    *(s16 *)lbl_1000001E = 0;
    lbl_802F1FF0 = 0;
    lbl_802F1FF6 = 0x10;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[16]();
}

void lbl_00002AE8(void)
{
    struct Ball *ball = currentBall;
    u8 *w = (u8 *)lbl_10000000;
    u16 t;

    lbl_802F1FF0++;
    if (ball->state == 0)
    {
        event_suspend(2);
        stageInfo.unk1C |= 1;
        *(u16 *)(w + 0x1e) += 1;
    }
    t = *(u16 *)(w + 0x1e);
    if (t == 0x1e)
    {
        lbl_000099A4();
        func_8002BFCC(0x16a, 0x16b);
        u_play_music(0, 8);
    }
    else if (t == 0x78)
    {
        u_play_sound_0(0x1af);
    }
    else if (t == 0xf0)
    {
        u_play_music(100, 8);
    }
    else if (t > 0xf0)
    {
        if ((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button & 0x100)
         || t > 0x1a4)
            lbl_802F1FF4 = 0;
    }
    lbl_00004A14();
}

void lbl_00002C18(void)
{
    u8 *w = (u8 *)lbl_10000000;
    struct Ball *ball = currentBall;
    u8 *k = (u8 *)lbl_0000BE80;
    struct PilotResultRec *tbl;
    s32 i;

    event_suspend(2);
    ball->unk148 = 3;
    tbl = (struct PilotResultRec *)lbl_80285A80;
    i = modeCtrl.currPlayer;
    if (tbl[i].unk8 != 0)
        ball->restitution = *(f32 *)(k + 0x1a8);
    else if (tbl[i].unk4 != 0)
        ball->restitution = *(f32 *)(k + 0x1ac);
    else
        ball->restitution = *(f32 *)(k + 0x1a4);

    if (*(s32 *)(w + 0x2c) != -1)
    {
        SoundOff(*(s32 *)(w + 0x2c));
        *(s32 *)(w + 0x2c) = -1;
    }
    lbl_802F1FF0 = 0;
    lbl_802F1FF6 = 0x12;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[18]();
}

void lbl_00002D24(void)
{
    lbl_802F1FF0++;
    if (*(s16 *)lbl_10000018 == 0
     && *(f64 *)lbl_0000C030 == *(f32 *)lbl_802F1FDC
     && lbl_802F1FF0 % 30 == 1)
    {
        u_somePlayerId = modeCtrl.currPlayer;
        lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
        u_play_sound_0(((s16 *)lbl_0000BE80)[(rand() >> 12) & 7]);
    }
    lbl_00004A14();
}

void lbl_00002E04(void)
{
    struct PilotResultRec *tbl = (struct PilotResultRec *)lbl_80285A80;
    s32 i = modeCtrl.currPlayer;

    if (tbl[i].unk4 != 0)
        u_play_sound_0(0x135);
    else if (tbl[i].unk8 != 0)
        u_play_sound_0(0x138);
    lbl_802F1FF6 = 0x14;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[20]();
}

void lbl_00002E94(void)
{
    lbl_00004A14();
}

void lbl_00002EB4(void)
{
    struct Ball *ball = currentBall;
    s32 t;

    stageInfo.unk1C |= 1;
    lbl_00006BF4(ball);
    lbl_00008568();
    t = *(s32 *)lbl_10000074;
    if (t >= 5 && !(lbl_802F1FD0 & 2))
        lbl_802F1FD0 |= 1;
    if (t >= 0x12c)
        u_play_sound_0(0x1ae);
    else if (t >= 0x64)
        u_play_sound_0(0x1ad);
    else if (t >= 0xa)
        u_play_sound_0(0x1a0);
    else
        u_play_sound_0(0x1a4);
    u_play_music(0, 8);
    SoundOffID(0xf9);
    cameraInfo[ball->playerId].subState = 3;
    ball->state = 0;
    lbl_802F1FF0 = 0;
    *(s32 *)lbl_1000008C = 0;
    lbl_802F1FF6 = 0x16;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[22]();
}

void lbl_00002FF4(void)
{
    struct Ball *ball = currentBall;
    u8 *w = (u8 *)lbl_10000000;

    lbl_802F1FF0++;
    if (lbl_802F1FF0 == 0xf)
    {
        if (!(lbl_802F1FD0 & 0x40))
        {
            u_somePlayerId = ball->playerId;
            lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
            if (*(s32 *)(w + 0x74) >= 0x1f4)
                u_play_sound_0(0x12d);
            else if (*(s32 *)(w + 0x74) >= 0x12c)
                u_play_sound_0(0x130);
            else if (*(s32 *)(w + 0x74) >= 0x64)
                u_play_sound_0(0x12f);
            else if (*(s32 *)(w + 0x74) >= 0xa)
                u_play_sound_0(0x12e);
            else
                u_play_sound_0(0x12c);
        }
    }
    else if (lbl_802F1FF0 == 0x1e)
    {
        if (*(s32 *)(w + 0x74) >= 0x12c)
        {
            func_8002BFCC(0x15f, 0x160);
            *(s32 *)(w + 0x94) = 0x1fe;
        }
        else if (*(s32 *)(w + 0x74) >= 0x64)
        {
            func_8002BFCC(0x163, 0x15c);
            *(s32 *)(w + 0x94) = 0x10e;
        }
        else if (*(s32 *)(w + 0x74) >= 0xa)
        {
            func_8002BFCC(0x15d, 0x15e);
            *(s32 *)(w + 0x94) = 0xf0;
        }
        else
        {
            func_8002BFCC(0x16a, 0x16b);
            *(s32 *)(w + 0x94) = 0xd2;
        }
    }
    if (lbl_802F1FF0 == *(s32 *)(w + 0x94))
        u_play_music(100, 8);

    {
        int cp = modeCtrl.currPlayer;

        if (((s32 *)lbl_80285A58)[cp] == 0)
        {
            *(s32 *)(w + 0x8c) += 1;
        }
        else if (controllerInfo[playerControllerIDs[ball->playerId]].pressed.button & 0x100)
        {
            ((s32 *)(w + 0x44))[cp] += ((s32 *)lbl_80285A58)[cp];
            ((s32 *)lbl_80285A58)[cp] = 0;
            lbl_802F1FEC = 0;
        }
    }

    if (*(s32 *)(w + 0x8c) > 0x14 && lbl_802F1FF0 > 0x78
     && ((controllerInfo[playerControllerIDs[ball->playerId]].pressed.button & 0x100)
      || lbl_802F1FF0 > 0x1e0))
        lbl_802F1FF4 = 0;
    else
        lbl_00004A14();
}

void lbl_00003298(void)
{
    u8 *w = (u8 *)lbl_10000000;
    s32 pa;
    s32 pb;
    s32 pc;
    s32 pd;

    event_finish_all();
    event_start(1);
    event_start(4);
    event_start(0xf);
    event_start(0x10);
    event_start(0x12);
    event_start(0x14);
    event_start(0x13);
    camera_set_state_all(0x43);
    cameraInfo[0].subState = 4;
    *(s16 *)(w + 0x18) = 0;
    *(s32 *)(w + 0x98) = 0;
    *(s32 *)(w + 0x9c) = 0;
    *(s32 *)(w + 0xa0) = 0;
    *(s32 *)(w + 0xa4) = 0;
    lbl_0000A69C();
    lbl_802F1FF0 = 0;
    *(s32 *)(w + 0x8c) = 0;
    lbl_802F1FF6 = 0x18;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[24]();
}

void lbl_00003374(void)
{
    u8 *w = (u8 *)lbl_10000000;
    s32 i;
    s32 sel;
    s32 flags;
    u8 rec[8];
    s32 dead[2];

    lbl_802F1FF0++;
    if (lbl_00006D14() && lbl_802F1FF0 > 50)
    {
        *(s32 *)(w + 0x98) = *(s32 *)(w + 0x44);
        *(s32 *)(w + 0x9c) = *(s32 *)(w + 0x48);
        *(s32 *)(w + 0xa0) = *(s32 *)(w + 0x4c);
        *(s32 *)(w + 0xa4) = *(s32 *)(w + 0x50);
    }
    for (i = 0; i < 4; i++)
    {
        if (g_poolInfo.playerPool.statusList[i] != 0
         && ((s32 *)(w + 0x98))[i] != ((s32 *)(w + 0x44))[i])
            break;
    }
    if (i == 4)
        *(s32 *)(w + 0x8c) += 1;
    if ((lbl_00006D14() && *(s32 *)(w + 0x8c) > 20) || lbl_802F1FF0 > 720)
    {
        *(s8 *)(w + 0x34) = -1;
        if (modeCtrl.playerCount == 1)
        {
            flags = 0;
            if (lbl_802F1FD0 & (1 << 3))
                flags |= 1;
            if (lbl_802F1FD0 & (1 << 4))
                flags |= 2;
            switch (*(s16 *)(w + 0x64))
            {
            case 5:
                sel = 6;
                break;
            case 10:
                sel = 7;
                break;
            default:
                sel = 8;
                break;
            }
            rec[3] = playerCharacterSelection[0];
            *(u16 *)(rec + 4) = *(s32 *)(w + 0x44);
            rec[6] = flags;
            *(s8 *)(w + 0x34) = (s8)func_800AC5E0(sel, rec);
            if (*(s8 *)(w + 0x34) < 0)
            {
                lbl_802F1FF4 = 0x1b;
                return;
            }
        }
        pauseMenuState.unk4 |= 2;
        lbl_802F1FF4 = 0x19;
    }
}

void lbl_000035B8(void)
{
    u8 *k = (u8 *)lbl_0000BE80;
    s8 spC[4];
    s8 sp8[4];
    int i;
    int j;
    int rank;

    u_free_minigame_graphics();
    lbl_802F1FD4 = NULL;
    event_finish_all();
    event_start(1);
    event_start(4);
    event_start(0x14);
    event_start(0x13);
    event_start(0x12);
    event_start(0xf);
    event_start(0xd);
    event_start(0x10);
    if (modeCtrl.playerCount == 1)
    {
        spC[0] = playerCharacterSelection[0];
        spC[1] = -1;
        spC[2] = -1;
        spC[3] = -1;
        sp8[0] = *(u8 *)lbl_10000034;
    }
    else
    {
        for (i = 0; i < 4; i++)
        {
            if (g_poolInfo.playerPool.statusList[i] == 0)
            {
                spC[i] = -1;
            }
            else
            {
                rank = 0;
                for (j = 0; j < 4; j++)
                {
                    if (i != j && g_poolInfo.playerPool.statusList[j] != 0
                     && lbl_10000044[j] > lbl_10000044[i])
                        rank++;
                }
                spC[i] = playerCharacterSelection[i];
                sp8[i] = rank;
            }
        }
    }
    func_8009C5E4(spC, sp8);
    lbl_802F1FD0 |= 4;
    camera_set_state_all(0x46);
    mathutil_mtxA_from_translate_xyz(*(f32 *)(k + 0x30), *(f32 *)(k + 0x1b8), *(f32 *)(k + 0x1bc));
    mathutil_mtxA_rotate_y(0x8000);
    func_8009DB40(mathutilData->mtxA);
    lbl_802F1FF0 = 0;
    lbl_802F1FF6 = 0x1a;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[26]();
}

void lbl_00003860(void)
{
    lbl_802F1FF0++;
    if (lbl_802F1FF0 >= 60 && func_8009D794()
     && (lbl_00006D14() || lbl_802F1FF0 > 0x708))
        lbl_802F1FF4 = 0x1b;
}

// UNVERIFIED: the 8-byte high-score record handed to func_800AC43C.  Games
// 6/7/8 use the 8-byte "pair" layout -- cf. struct MiniScoreU16Pair in
// src/mini_ranking.c, which is itself invented.
struct PilotRankRec
{
    u8 name[3];
    u8 chara;
    u16 score;
    u8 unk6;
    u8 unk7;
};

void lbl_000038D4(void)
{
    struct PilotRankRec recs[5];
    u8 flags = 0;
    int game;
    int i;

    u_free_minigame_graphics();
    lbl_802F1FD4 = NULL;
    mini_commend_free_data();
    lbl_802F1FD0 &= ~4;
    event_finish_all();
    event_start(0x10);
    event_start(0x12);
    if (lbl_802F1FD0 & 8)
        flags |= 1;
    if (lbl_802F1FD0 & 0x10)
        flags |= 2;
    switch (*(s16 *)lbl_10000064)
    {
    case 5:
        game = 6;
        break;
    case 10:
        game = 7;
        break;
    default:
        game = 8;
        break;
    }
    for (i = 0; i < 4; i++)
    {
        if (g_poolInfo.playerPool.statusList[i] == 0)
            break;
        recs[i].chara = playerCharacterSelection[i];
        recs[i].score = lbl_10000044[i];
        recs[i].unk6 = flags;
    }
    if (func_800AC43C(game, recs, modeCtrl.playerCount) != 0)
        func_800AB2A0(game, 1);
    else
        func_800AB2A0(game, 0);
    modeCtrl.submodeTimer = 0;
    lbl_802F1FF6 = 0x1c;
    lbl_802F1FF4 = -1;
    ((void (**)(void))lbl_0000C748)[28]();
}

void lbl_00003AD0(void)
{
    if (modeCtrl.submodeTimer == 0)
    {
        if (lbl_00006D14() && !func_800AB6F8())
        {
            u_play_sound_0(0xd1);
            modeCtrl.submodeTimer = 60;
            start_screen_fade(0x101, 0xFFFFFF, 60);
            u_play_music(60, 2);
        }
    }
    else if (--modeCtrl.submodeTimer == 0)
    {
        func_800AB444();
        func_80012434(modeCtrl.gameType);
    }
}

void lbl_00003B6C(void)
{
    switch (lbl_802F1FF6) {
    case 0x1c:
        break;
    case 0x1b:
    default:
        lbl_00003BDC();
        break;
    case 0x1a:
        lbl_00003BDC();
        func_8009CD5C();
        if (((s8 *)eventInfo)[0x138] == 2)
            effect_draw();
        break;
    }
}
asm void lbl_00003BDC(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_pilot/lbl_00003BDC.s"
}

#pragma peephole on
struct PilotDrawNode { struct OrdTblNode node; u32 lightGroup; int ballId; };

void lbl_00004024(void)
{
    struct Ball *ball = ballInfo;
    s8 *status = g_poolInfo.playerPool.statusList;
    int i;

    for (i = 0; i < g_poolInfo.playerPool.count; i++, ball++, status++) {
        struct PilotDrawNode *node;
        struct OrdTblNode *entry;

        if (*status == STAT_NULL || *status == STAT_FREEZE)
            continue;
        if (ball->unk148 != 2 && ball->unk148 != 3)
            continue;
        mathutil_mtxA_from_mtxB();
        entry = ord_tbl_get_entry_for_pos(&ball->pos);
        node = ord_tbl_alloc_node(sizeof(*node));
        node->node.drawFunc = (OrdTblDrawFunc)lbl_000040EC;
        node->lightGroup = peek_light_group();
        node->ballId = i;
        ord_tbl_insert_node(entry, &node->node);
    }
}
void lbl_000040EC(u8 *p)
{
    struct T10
    {
        s16 v[10];
    };
    s16 rot;
    u8 *k = (u8 *)lbl_0000BE80;
    struct T10 a = *(struct T10 *)(k + 0x1E0);
    struct T10 b = *(struct T10 *)(k + 0x1F4);
    struct T10 c = *(struct T10 *)(k + 0x208);
    f32 t;
    f32 sc2;
    f32 sc = *(f32 *)lbl_802F1FDC;
    struct Ball *ball = &ballInfo[*(s32 *)(p + 0xC)];
    s16 ang;

    load_light_group_cached(*(s32 *)(p + 8));
    ang = *(f64 *)(k + 0x220) * *(f32 *)lbl_10000000;
    if (ang > 0x600)
        ang = 0x600;
    else if (ang < -384)
        ang = -384;
    rot = *(f32 *)lbl_802F1FDC * (f64)(ang + 0x4A00) / ((f64 *)k)[0x33];
    if (lbl_802F1FD0 & 0x20)
        sc = *(f32 *)(k + 0x228);
    t = *(f64 *)(k + 0x230) * (*(f32 *)lbl_802F1FDC / *(f64 *)(k + 0x198));
    sc2 = ((f64 *)k)[13] - *(f64 *)(k + 0x238) * (sc / *(f64 *)(k + 0x198));
    polydisp_set_some_color_based_on_curr_mode(
        *(f64 *)(k + 0x68)
      + *(f64 *)(k + 0x68) * ball->u_opacity[*(s32 *)((u8 *)currentCamera + 0x204)]);
    avdisp_set_z_mode(1, 3, 0);
    mathutil_mtxA_from_mtxB();
    mathutil_mtxA_mult_right(ball->unk30);
    mathutil_mtxA_translate_xyz(*(f32 *)(k + 0x30), sc2, *(f32 *)(k + 0x30));
    mathutil_mtxA_push();
    mathutil_mtxA_translate_xyz(-t, *(f32 *)(k + 0x30), *(f32 *)(k + 0x30));
    mathutil_mtxA_rotate_z(-(s16)rot);
    gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
    avdisp_draw_model_unculled_sort_none(minigameGma->modelEntries[0].model);
    avdisp_draw_model_unculled_sort_none(minigameGma->modelEntries[1].model);
    if (*(f32 *)lbl_802F1FDC > *(f64 *)(k + 0x1B0))
    {
        mathutil_mtxA_rotate_y(0x8000);
        gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
        avdisp_draw_model_unculled_sort_none(minigameGma->modelEntries[0x1C].model);
    }
    mathutil_mtxA_pop();
    mathutil_mtxA_translate_xyz(t, *(f32 *)(k + 0x30), *(f32 *)(k + 0x30));
    mathutil_mtxA_rotate_z(rot);
    gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
    avdisp_draw_model_unculled_sort_none(minigameGma->modelEntries[b.v[ball->colorId]].model);
    avdisp_draw_model_unculled_sort_none(minigameGma->modelEntries[a.v[ball->colorId]].model);
    if (*(f32 *)lbl_802F1FDC > *(f64 *)(k + 0x1B0))
        avdisp_draw_model_unculled_sort_none(minigameGma->modelEntries[c.v[ball->colorId]].model);
    fade_color_base_default();
    avdisp_set_z_mode(1, 3, 1);
}

#pragma peephole on

void lbl_00004450(void)
{
    u8 *m = (u8 *)lbl_10000000;
    struct Ball *ball = currentBall;
    u8 *k = (u8 *)lbl_0000BE80;
    f32 u;
    f32 v;
    s16 ang;
    f32 scale;

    if (mathutil_vec_sq_len((Vec *)(m + 0x68)) < *(f64 *)(k + 0x240))
        return;
    ang = mathutil_atan2(*(f32 *)(m + 0x68), *(f32 *)(m + 0x70));
    lbl_00006CCC(&u, &v, *(f32 *)(k + 0x1CC), *(f32 *)(k + 0x248),
                 *(f32 *)(k + 0x24C), cameraInfo[ball->playerId].sub28.unk38);
    scale = *(f32 *)(k + 0x250);
    mathutil_mtxA_from_mtxB();
    mathutil_mtxA_set_translate_xyz(u, v, *(f32 *)(k + 0x254));
    mathutil_mtxA_rotate_y(ang);
    mathutil_mtxA_scale_s(scale);
    gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
    avdisp_set_bound_sphere_scale(scale);
    avdisp_draw_model_unculled_sort_translucent(minigameGma->modelEntries[9].model);
}
asm void lbl_00004570(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_pilot/lbl_00004570.s"
}

#pragma peephole on

void lbl_000048C0(void)
{
    u8 *k = (u8 *)lbl_0000BE80;
    struct Ball *ball = currentBall;
    struct RaycastHit hit;
    Vec up;
    Quaternion quat;
    Mtx mtx;
    u32 hit_;

    up = *(Vec *)(k + 0x2A8);
    avdisp_set_post_mult_color(*(f32 *)(k + 0x2B4), *(f32 *)(k + 0x2B4),
                               *(f32 *)(k + 0x2B4), *(f32 *)(k + 0x2B4));
    avdisp_set_z_mode(1, 3, 0);
    hit_ = raycast_stage_down(&ball->pos, &hit, NULL);
    if (hit_)
    {
        mathutil_mtxA_from_identity();
        mathutil_mtxA_scale_s(*(f32 *)(k + 0x2B8));
        mathutil_mtxA_to_mtx(mtx);
        mathutil_mtxA_from_mtxB_translate(&hit.pos);
        mathutil_mtxA_mult_left(mtx);
        mathutil_mtxA_to_mtx(mtx);
        mathutil_quat_from_dirs(&quat, &up, &hit.normal);
        mathutil_mtxA_from_quat(&quat);
        mathutil_mtxA_mult_left(mtx);
        if (*(f32 *)lbl_802F1FDC > *(f64 *)(k + 0x1B0))
            mathutil_mtxA_scale_s(*(f32 *)(k + 0x2BC));
        else
            mathutil_mtxA_scale_s(*(f32 *)(k + 0x2C0));
        gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
        avdisp_draw_model_culled_sort_none(commonGma->modelEntries[0x4E].model);
    }
    avdisp_set_post_mult_color(*(f32 *)(k + 0x34), *(f32 *)(k + 0x34),
                               *(f32 *)(k + 0x34), *(f32 *)(k + 0x34));
    avdisp_set_z_mode(1, 3, 1);
}
void lbl_00004A14(void)
{
    struct Ball *ball = currentBall;
    u8 *m = (u8 *)lbl_10000000;
    u8 *k = (u8 *)lbl_0000BE80;
    int id;

    if (ball->pos.y < *(f64 *)(k + 0x2C8) || (lbl_802F1FD0 & 0x200))
    {
        if (*(s16 *)(m + 0x18) == 0)
        {
            if (*(s32 *)(m + 0x2C) != -1)
            {
                SoundOff(*(s32 *)(m + 0x2C));
                *(s32 *)(m + 0x2C) = -1;
            }
            if (lbl_802F1FF6 == 0xE)
                u_play_sound_0(0xF6);
            else
                u_play_sound_0(0xF5);
            vibration_control(playerControllerIDs[ball->playerId], 1, 0x14);
        }
        else if (*(s16 *)(m + 0x18) == 0xA)
        {
            switch (ball->ape->charaId)
            {
            case 1:
                u_play_sound_0(0xEE);
                break;
            case 2:
                u_play_sound_0(0xEA);
                break;
            case 3:
                id = u_play_sound_1_dupe(0x161);
                SoundRev(id, 0x60);
                SoundCho(id, 0x40);
                break;
            default:
                u_play_sound_0(0xEC);
                break;
            }
        }

        (*(s16 *)(m + 0x18))++;
        if (!(lbl_802F1FD0 & 0x200)
         && ((mathutil_sqrt(mathutil_sum_of_sq_2(ball->vel.x, ball->vel.z)) < *(f64 *)(k + 0x2D0)
              && ball->pos.y < *(f64 *)(k + 0x2D8))
             || ball->pos.y < *(f64 *)(k + 0x2E0)))
        {
            lbl_802F1FD0 |= 0x200;
            hud_show_fallout_banner(0xB4);
            func_8002BFCC(0x16A, 0x16B);
            u_play_music(0, 8);
        }

        if (*(s16 *)(m + 0x1A) == 0x50)
            u_play_sound_0(0xC);
        else if (*(s16 *)(m + 0x1A) > 0xB4)
            lbl_802F1FF4 = 0;

        if (lbl_802F1FD0 & 0x200)
            (*(s16 *)(m + 0x1A))++;

        if (*(f32 *)lbl_802F1FDC > *(f64 *)(k + 0x1B0))
        {
            ball->vel.x = *(f64 *)(k + 0x2E8) * ball->vel.x;
            ball->vel.y = *(f64 *)(k + 0x2E8) * ball->vel.y;
            ball->vel.z = *(f64 *)(k + 0x2E8) * ball->vel.z;
        }
        else
        {
            ball->vel.x = *(f64 *)(k + 0x2F0) * ball->vel.x;
            ball->vel.y = *(f64 *)(k + 0x2F0) * ball->vel.y;
            ball->vel.z = *(f64 *)(k + 0x2F0) * ball->vel.z;
        }

        if (ball->vel.y < *(f64 *)(k + 0x1B0))
            ball->vel.y = ball->vel.y * *(f64 *)(k + 0x2F8);
    }
    else
    {
        if (*(s16 *)(m + 0x18) != 0)
        {
            SoundOffID(0xEE);
            SoundOffID(0xEA);
            SoundOffID(0x161);
            SoundOffID(0xEC);
            *(s16 *)(m + 0x18) = 0;
        }
        *(s16 *)(m + 0x1A) = 0;
    }

    if (ball->pos.y < *(f64 *)(k + 0x300) && *(s16 *)(m + 0x18) == 0
     && lbl_802F1FF6 != 0x16)
        u_play_sound_0(0xF9);
    else
        SoundOffID(0xF9);

    if (lbl_802F1FD0 & 0x1000)
    {
        if (*(s32 *)(m + 0x30) == -1)
            *(s32 *)(m + 0x30) = u_play_sound_2(0xF3);
    }
    else
    {
        if (*(s32 *)(m + 0x30) != -1)
        {
            SoundOff(*(s32 *)(m + 0x30));
            *(s32 *)(m + 0x30) = -1;
        }
    }

    if (((s32 *)lbl_80285A58)[modeCtrl.currPlayer] > 0)
    {
        int d = ((s32 *)lbl_80285A58)[modeCtrl.currPlayer] / lbl_802F1FEC;

        if (d < 1)
            d = 1;
        ((s32 *)lbl_80285A58)[modeCtrl.currPlayer] -= d;
        ((s32 *)(m + 0x44))[modeCtrl.currPlayer] += d;
    }

    if (lbl_802F1FEC > 0)
        lbl_802F1FEC--;
    if (*(s16 *)lbl_802F1FE0 > 0)
        (*(s16 *)lbl_802F1FE0)--;
}

void lbl_00004E84(void)
{
    struct Ball *ball = currentBall;

    if (lbl_802F1FF6 == 0x10 && *(s16 *)lbl_10000018 == 0
     && !(ball->flags & BALL_FLAG_00) && ball->state != 0
     && lbl_802F1FF0 % 30 == 1)
    {
        u_somePlayerId = ball->playerId;
        lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
        u_play_sound_0(((s16 *)lbl_0000BE80)[(rand() >> 12) & 7]);
    }
}
void lbl_00004F68(struct Ball *ball)
{
    ((void (**)(struct Ball *))lbl_0000C7BC)[ball->unk148](ball);
    lbl_00006B94();
}

void lbl_00004FA8(struct Ball *ball)
{
    struct PhysicsBall physBall;

    lbl_00006124(ball, &physBall, 0);
    handle_ball_rotational_kinematics(ball, &physBall, 0);
    update_ball_ape_transform(ball, &physBall, 0);
    ball->unk80++;
}

void lbl_00005008(struct Ball *ball)
{
    lbl_0000580C();
    ball->unk148 = 2;
    lbl_00005044(ball);
}
void lbl_00005044(struct Ball *ball)
{
    struct PhysicsBall physBall;

    lbl_00005824(ball);
    lbl_00006490(ball, &physBall, 0);
    update_ball_ape_transform(ball, &physBall, 0);
    ball->unk80++;
}

void lbl_0000509C(struct Ball *ball)
{
    u8 *k = (u8 *)lbl_0000BE80;
    struct PhysicsBall physBall;

    if (*(f32 *)lbl_802F1FDC > *(f64 *)(k + 0x1B0))
    {
        if (*(s16 *)lbl_10000018 == 0)
            *(f32 *)lbl_802F1FDC = *(f32 *)lbl_802F1FDC - *(f64 *)(k + 0x2A0);
        else
            *(f32 *)lbl_802F1FDC = *(f32 *)lbl_802F1FDC - *(f64 *)(k + 0x308);
        if (*(f32 *)lbl_802F1FDC <= *(f64 *)(k + 0x1B0))
        {
            *(f32 *)lbl_802F1FDC = *(f32 *)(k + 0x30);
            u_play_sound_0(0xF1);
            vibration_control(playerControllerIDs[ball->playerId], VIBRATION_STATE_1,
                              0xA);
        }
    }
    lbl_0000669C(ball, &physBall, 0);
    handle_ball_rotational_kinematics(ball, &physBall, 0);
    update_ball_ape_transform(ball, &physBall, 0);
    ball->unk80++;
}
void lbl_000051A4(struct Ape *ape, int status)
{
    u8 *k = (u8 *)lbl_0000BE80;
    struct Ball *ball = &ballInfo[ape->ballId];
    struct RaycastHit hit;
    int r28;
    float speed;

    switch (status)
    {
    case THREAD_STATUS_KILLED:
        ape_destroy(ape);
        return;
    }

    if (debugFlags & 0xA)
        return;
    if (ball != currentBall)
        return;

    raycast_stage_down(&ball->pos, &hit, NULL);
    ape->flags &= -20;
    if ((!(hit.flags & 1) && ball->vel.y < *(f32 *)(k + 0x310))
        || (*(f64 *)(k + 0x1B0) == *(f32 *)lbl_802F1FDC && *(s16 *)lbl_10000018 != 0))
        ape->flags |= 2;
    else if (mathutil_vec_len(&ball->unkB8) < *(f32 *)(k + 0x314))
        ape->flags |= 1;

    if (*(f32 *)lbl_802F1FDC > *(f64 *)(k + 0x1B0))
    {
        mathutil_mtxA_from_mtx(ball->unk30);
        mathutil_mtxA_rotate_y(-0x4000);
        mathutil_mtxA_to_quat(&ape->unk60);
    }
    else
    {
        r28 = !(ape->flags & 3);
        u_ball_something_with_ape_rotation(ape);
        if (r28)
        {
            speed = u_ball_something_with_walking_speed(ape);
        }
        else
        {
            speed = *(f32 *)(k + 0x30);
            mathutil_mtxA_from_quat(&ape->unk60);
            mathutil_mtxA_normalize_basis();
            if (ape->flags & (1 << 1))
                func_80037718(ape);
        }
    }

    if (ball->flags & BALL_FLAG_05)
        speed = mathutil_vec_len(&ball->vel);

    if (lbl_802F1FF6 == 12)
        check_ball_teeter(ape);
    else
        ball->flags &= ~BALL_FLAG_TEETER;

    mathutil_mtxA_to_quat(&ape->unk60);
    lbl_00005414(ape, speed);
    ape_skel_anim_main(ape);
    if (!(ape->flags & (1 << 3)))
        func_8003765C(ape);
    ape_face_dir(ape, &ball->lookPoint);
    ball->unk100 = 0;
    ball->lookPointPrio = *(f32 *)(k + 0x30);
}

void lbl_00005414(struct Ape *ape, f32 speed)
{
    u8 *m = (u8 *)lbl_10000000;
    struct Ball *ball = &ballInfo[ape->ballId];
    s32 stat;
    s32 mot = 0;
    s32 arg = 0;
    u32 fl;
    u32 bf;
    s32 t;

    if (*(f32 *)lbl_802F1FDC > *(f64 *)lbl_0000C030)
    {
        if (lbl_802F1FD0 & 0x20)
        {
            stat = 0xC;
            if ((ball->flags & 1) || ball->state == 0)
                mot = 6;
            else
                mot = 2;
        }
        else if (*(s16 *)(m + 0x18) != 0 || (lbl_802F1FD0 & 0x22))
        {
            stat = 0xC;
            mot = 2;
        }
        else
        {
            stat = 0xC;
            t = controllerInfo[playerControllerIDs[ball->playerId]].held.stickX;
            if (t < -30)
                mot = 8;
            else if (t > 30)
                mot = 9;
            else
                mot = 0;
        }
    }
    else if ((lbl_802F1FD0 & 0x40) && *(s16 *)(m + 0x18) == 0)
    {
        stat = 0xC;
        if ((ball->flags & 1) || ball->state == 0)
            mot = 7;
        else
            mot = 3;
    }
    else if (lbl_802F1FF6 == 0x16 && (lbl_802F1FD0 & 1))
    {
        t = *(s32 *)(m + 0x74);
        stat = 5;
        if (t >= 0x1F4)
            mot = 0xC;
        else if (t >= 0x12C)
            mot = 0xA;
        else if (t >= 0xC8)
            mot = 8;
        else if (t >= 0x64)
            mot = 6;
        else if (t >= 0x32)
            mot = 4;
        else if (t >= 0x28)
            mot = 2;
        else
            mot = 0;
    }
    else
    {
        fl = ape->flags;
        if (fl & 0x100)
        {
            stat = 1;
            arg = 6;
            set_ape_model_lod(ape, 0);
        }
        else if (fl & 0x800)
        {
            stat = 2;
            mot = 0xD;
        }
        else if (fl & 0x40000)
        {
            stat = 2;
            mot = 0x10;
        }
        else if (gameSubmode == 0x4B)
        {
            stat = 5;
            mot = 0xC;
        }
        else
        {
            bf = ball->flags;
            if (bf & 0x4000)
            {
                if (lbl_802F1FF0 < 0x18)
                    return;
                ape->flags = fl | 0x1000;
                stat = 2;
                mot = 0xC;
                if (ape->flags & 0x2000)
                    ball->flags &= ~0x4000;
            }
            else if (fl & 2)
            {
                stat = 3;
            }
            else if (bf & 0x8000)
            {
                if (!(infoWork.flags & 0x40))
                {
                    stat = 9;
                    mot = (infoWork.currFloor & 1) + 1;
                }
                else
                {
                    stat = 9;
                    mot = 0;
                }
            }
            else if (bf & 0x20)
            {
                ball->flags = bf & ~0x20;
                stat = 4;
                speed = mathutil_vec_len(&ball->vel);
            }
            else if (bf & 2)
            {
                mot = ape->unk54;
                stat = 2;
            }
            else if (fl & 1)
            {
                stat = 1;
                if (bf & 1)
                    speed = ape->unk54++;
                else
                    speed = *(f32 *)lbl_0000BEB0;
            }
            else
            {
                stat = 0;
            }
        }
    }
    if (stat != 1 || gameSubmode == 0x31)
        ape->unk54 = 0;
    new_ape_stat_motion(ape, stat, mot, arg, speed);
}

#pragma peephole on

void lbl_0000580C(void)
{
    *(f32 *)lbl_802F1FDC = *(f32 *)lbl_0000BEB4;
}
void lbl_00005824(struct Ball *ball)
{
    u8 *m = (u8 *)lbl_10000000;
    u8 *k = (u8 *)lbl_0000BE80;
    Vec a1;
    Vec a2;
    Vec a3;
    Vec a4;
    Vec acc;
    Vec t4;
    Vec vloc;
    Vec t2;
    Vec t1;
    Vec dv;
    Vec w;
    Quaternion q;
    Quaternion qt;
    Vec cvec;
    Vec dir;
    Vec imp;
    f32 sx;
    f32 sy;
    f32 len;
    f32 tq;
    f32 d;
    s16 ang;
    f32 dp;

    a1 = *(Vec *)(k + 0x318);
    a2 = *(Vec *)(k + 0x324);
    a3 = *(Vec *)(k + 0x330);
    a4 = *(Vec *)(k + 0x33C);
    if (!(lbl_802F1FD0 & 0x20)
     && *(f32 *)lbl_802F1FDC < *(f64 *)(k + 0x198))
        *(f32 *)lbl_802F1FDC = *(f32 *)lbl_802F1FDC + *(f64 *)(k + 0x2A0);
    mathutil_mtxA_from_mtx(ball->unk30);
    mathutil_mtxA_tf_vec(&a4, &t4);
    mathutil_mtxA_tf_vec(&a2, &t2);
    mathutil_mtxA_tf_vec(&a1, &t1);
    mathutil_mtxA_rigid_inv_tf_vec(&ball->vel, &vloc);
    dv.x = ball->vel.x - *(f32 *)(m + 0x68);
    dv.y = ball->vel.y - *(f32 *)(m + 0x6C);
    dv.z = ball->vel.z - *(f32 *)(m + 0x70);
    *(f32 *)(m + 4) = mathutil_vec_dot_prod(&dv, &t4);
    len = mathutil_sqrt(*(f32 *)(m + 4));
    if (lbl_802F1FD0 & 0x20)
    {
        sy = sx = *(f32 *)(k + 0x30);
    }
    else
    {
        sx = controllerInfo[playerControllerIDs[ball->playerId]].held.stickX;
        sy = controllerInfo[playerControllerIDs[ball->playerId]].held.stickY;
    }
    sy = sy * len;
    sx = sx * len;
    mathutil_quat_from_axis_angle(&q, &a1, *(f64 *)(k + 0x358) * sy);
    mathutil_quat_from_axis_angle(&qt, &a3, *(f64 *)(k + 0x360) * sx);
    mathutil_quat_mult(&q, &q, &qt);
    mathutil_quat_from_axis_angle(&qt, &a2, *(f64 *)(k + 0x368) * sx);
    mathutil_quat_mult(&q, &q, &qt);
    mathutil_mtxA_from_quat(&q);
    mathutil_mtxA_mult_left(ball->unk30);
    mathutil_mtxA_sq_to_mtx(ball->unk30);
    if (*(f32 *)lbl_802F1FD8 > *(f64 *)(k + 0x1B0))
    {
        cvec = *(Vec *)(k + 0x348);
        *(f32 *)lbl_802F1FD8 = *(f32 *)lbl_802F1FD8 * *(f64 *)(k + 0x370);
        u_math_unk9_smth_w_quats(&q, &cvec, *(f32 *)lbl_802F1FD8);
        mathutil_mtxA_from_quat(&q);
        mathutil_mtxA_mult_left(ball->unk30);
        mathutil_mtxA_sq_to_mtx(ball->unk30);
    }
    dp = mathutil_vec_dot_prod(&vloc, &a1);
    dp = -dp;
    mathutil_quat_from_axis_angle(&q, &a2,
        *(f64 *)(k + 0x378) * dp);
    dp = mathutil_vec_dot_prod(&vloc, &a2);
    tq = dp
       * (*(f64 *)(k + 0x230) * (*(f64 *)(k + 0x380) - *(f32 *)lbl_802F1FDC));
    mathutil_quat_from_axis_angle(&qt, &a1, *(f64 *)(k + 0x388) * tq);
    mathutil_quat_mult(&q, &q, &qt);
    dp = mathutil_vec_dot_prod(&a2, &t1);
    dp = -dp;
    mathutil_quat_from_axis_angle(&qt, &a3,
        *(f64 *)(k + 0x390) * dp);
    mathutil_quat_mult(&q, &q, &qt);
    dp = mathutil_vec_dot_prod(&a2, &t4);
    dp = -dp;
    mathutil_quat_from_axis_angle(&qt, &a1,
        *(f64 *)(k + 0x398) * dp);
    mathutil_quat_mult(&q, &q, &qt);
    mathutil_mtxA_from_quat(&q);
    mathutil_mtxA_mult_left(ball->unk30);
    mathutil_mtxA_sq_to_mtx(ball->unk30);
    mathutil_mtxA_from_mtx(ball->unk30);
    mathutil_mtxA_rigid_inv_tf_vec(&dv, &w);
    ang = mathutil_atan2(w.y, -w.z);
    *(f32 *)m = -mathutil_sin(ang * 2);
    if (ang > 0x4000 || ang < -0x4000)
        *(f32 *)m = *(f32 *)m * *(f32 *)(k + 0x3A0);
    *(f32 *)m = *(f64 *)(k + 0x3A8)
              * ((*(f32 *)lbl_802F1FDC / *(f64 *)(k + 0x198))
                 * (*(f32 *)m * (*(f32 *)(m + 4) * *(f32 *)(m + 4))));
    t2.x = t2.x * *(f32 *)m;
    t2.y = t2.y * *(f32 *)m;
    t2.z = t2.z * *(f32 *)m;
    ball->prevPos.x = ball->pos.x;
    ball->prevPos.y = ball->pos.y;
    ball->prevPos.z = ball->pos.z;
    ball->speed = mathutil_vec_len(&ball->vel);
    ball->flags &= ~0x20;
    acc.x = *(f32 *)(k + 0x30);
    acc.y = *(f32 *)(k + 0x3B0);
    acc.z = *(f32 *)(k + 0x30);
    if (ball->flags & 0x200)
        acc.y = -acc.y;
    else if (ball->flags & 0x100)
        acc.y = *(f32 *)(k + 0x30);
    if (!(lbl_802F1FD0 & 0x20))
    {
        w.x = *(f32 *)(m + 0x68) - ball->vel.x;
        w.y = *(f32 *)(m + 0x6C) - ball->vel.y;
        w.z = *(f32 *)(m + 0x70) - ball->vel.z;
        mathutil_mtxA_from_mtx(ball->unk30);
        mathutil_mtxA_rigid_inv_tf_vec(&w, &w);
        w.y = w.y * *(f64 *)(k + 0x3B8);
        w.z = w.z * *(f64 *)(k + 0x3B8);
        mathutil_mtxA_tf_vec(&w, &w);
        w.x = *(f64 *)(k + 0x3C0) * w.x;
        w.y = *(f64 *)(k + 0x3C0) * w.y;
        w.z = *(f64 *)(k + 0x3C0) * w.z;
        acc.x = acc.x + w.x;
        acc.y = acc.y + w.y;
        acc.z = acc.z + w.z;
        acc.x = acc.x + t2.x;
        acc.y = acc.y + t2.y;
        acc.z = acc.z + t2.z;
    }
    dir = ball->pos;
    dir.y = *(f32 *)(k + 0x30);
    d = mathutil_vec_len(&dir) - *(f64 *)(k + 0x3C8);
    if (d > *(f64 *)(k + 0x1B0))
    {
        if (mathutil_vec_dot_prod(&ball->pos, &ball->vel) < *(f64 *)(k + 0x1B0))
            d = d * *(f64 *)(k + 0x3D0);
        mathutil_vec_normalize_len(&dir);
        imp.x = dir.x * (*(f64 *)(k + 0x3D8) * -d);
        imp.y = dir.y * (*(f64 *)(k + 0x3D8) * -d);
        imp.z = dir.z * (*(f64 *)(k + 0x3D8) * -d);
        ball->vel.x = ball->vel.x + imp.x;
        ball->vel.y = ball->vel.y + imp.y;
        ball->vel.z = ball->vel.z + imp.z;
        *(f32 *)(m + 0x68) = dir.x * -*(f32 *)(m + 0x28);
        *(f32 *)(m + 0x6C) = dir.y * -*(f32 *)(m + 0x28);
        *(f32 *)(m + 0x70) = dir.z * -*(f32 *)(m + 0x28);
        *(Vec *)lbl_100000B8 = *(Vec *)(m + 0x68);
    }
    if (lbl_802F1FD0 & 0x20)
    {
        ball->vel.x = ball->vel.x * *(f64 *)(k + 0x3E0);
        ball->vel.z = ball->vel.z * *(f64 *)(k + 0x3E0);
        acc.y = -ball->accel;
    }
    ball->vel.x = ball->vel.x + acc.x;
    ball->vel.y = ball->vel.y + acc.y;
    ball->vel.z = ball->vel.z + acc.z;
}

#pragma peephole on

#pragma force_active reset
