/*
 * mini_pilot.c -- REL module, structurally split for per-function
 * byte-matching (part 50 of 50; contiguous .text range).  Each function
 * below is an asm-include of its body in asm/nonmatchings/mini_pilot/.
 * To convert one to C, isolate it into its own pure-C file (see the
 * --isolate option of tools/rel_split.py) -- an asm sibling in the same
 * TU disables mwcc's optimizer for the C function.  Keep the Makefile
 * SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "game.h"
#include "input.h"
#include "item.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "ord_tbl.h"
#include "pause_menu.h"
#include "pool.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "stcoli.h"
#include "vibration.h"
#include "window.h"
#include "avdisp.h"
#include "background.h"
#include "effect.h"
#include "gxutil.h"
#include "hud.h"
#include "info.h"
#include "lens_flare.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "rend_efc.h"
#include "shadow.h"
#include "spline.h"
#include "stobj.h"
#include "world.h"
#include "stdlib.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_pilot.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000BE80[];
extern u8 lbl_0000BEB0[];
extern u8 lbl_0000BEB4[];
extern u8 lbl_0000BEE0[];
extern u8 lbl_0000BFD0[];
extern u8 lbl_0000BFE0[];
extern u8 lbl_0000BFE8[];
extern u8 lbl_0000C010[];
extern u8 lbl_0000C030[];
extern u8 lbl_0000C2A8[];
extern u8 lbl_0000C2C8[];
extern u8 lbl_0000C2F0[];
extern u8 lbl_0000C348[];
extern u8 lbl_0000C358[];
extern u8 lbl_0000C360[];
extern u8 lbl_0000C3C0[];
extern u8 lbl_0000C3C8[];
extern u8 lbl_0000C3CC[];
extern u8 lbl_0000C430[];
extern u8 lbl_0000C548[];
extern u8 lbl_0000C5B8[];
extern u8 lbl_0000C5C0[];
extern u8 lbl_0000C690[];
extern u8 lbl_0000C6D8[];
extern u8 lbl_0000C740[];
extern u8 lbl_0000C748[];
extern u8 lbl_0000C7BC[];
extern u8 lbl_0000C7CC[];
extern u8 lbl_0000C7EC[];
extern u8 lbl_0000C88C[];
extern u8 lbl_0000CB0C[];
extern u8 lbl_0000CBCC[];
extern u8 lbl_0000CCF8[];
extern u8 lbl_0000D1C8[];
extern u8 lbl_0000D218[];
extern u8 lbl_0000D2E8[];
extern u8 lbl_0000D300[];
extern u8 lbl_0000D314[];
extern u8 lbl_0000D320[];
extern u8 lbl_0000D324[];
extern u8 lbl_0000D328[];
extern u8 lbl_0000D338[];
extern u8 lbl_0000D360[];
extern u8 lbl_0000D368[];
extern u8 lbl_0000D3A0[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000018[];
extern u8 lbl_1000001E[];
extern u8 lbl_10000020[];
extern u8 lbl_10000034[];
extern u8 lbl_10000038[];
extern u8 lbl_1000003C[];
extern u8 lbl_10000040[];
extern u8 lbl_10000044[];
extern u8 lbl_10000054[];
extern u8 lbl_1000005C[];
extern u8 lbl_10000064[];
extern u8 lbl_10000066[];
extern u8 lbl_10000068[];
extern u8 lbl_10000074[];
extern u8 lbl_10000078[];
extern u8 lbl_10000087[];
extern u8 lbl_10000088[];
extern u8 lbl_1000008A[];
extern u8 lbl_1000008C[];
extern u8 lbl_10000090[];
extern u8 lbl_10000098[];
extern u8 lbl_100000A8[];
extern u8 lbl_100000B0[];
extern u8 lbl_100000B8[];
extern u8 neutralFaceTable[];
extern u8 smileFaceTable[];
extern u8 lbl_80285A58[];
extern u8 lbl_80285A68[];
extern u8 lbl_80285A80[];
extern u8 lbl_802F1F10[];
extern u8 lbl_802F1FD0[];
extern u8 lbl_802F1FD8[];
extern u8 lbl_802F1FDC[];
extern u8 lbl_802F1FE0[];
extern u8 lbl_802F1FE4[];
extern u8 lbl_802F1FEC[];
extern u8 lbl_802F1FF4[];

// Imported functions the code calls that no included header declares.
extern void ball_8003BBF4();
extern void draw_test_camera_target();
extern void func_80042214();
extern void func_8009C5E4();
extern void func_8009CD5C();
extern void func_8009D794();
extern void func_8009DB40();
extern void func_800AB2A0();
extern void func_800AB444();
extern void func_800AB6F8();
extern void func_800AC43C();
extern void func_800AC5E0();
extern void item_create();
extern void mini_commend_free_data();
extern void qsort();
extern void set_shape_flags_in_model();
extern void stcoli_sub35();
extern void u_load_minigame_graphics();
extern void thread_create();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_000001F8(void);
void lbl_000003B4(void);
void lbl_0000044C(void);
void lbl_000004E0(void);
void lbl_00000648(void);
void lbl_0000066C(void);
void lbl_00000698(void);
void lbl_000007B8(void);
void lbl_000008AC(void);
void lbl_00000A30(void);
void lbl_00000BFC(void);
void lbl_0000215C(void);
void lbl_000021B4(void);
void lbl_000022D8(void);
void lbl_00003B6C(void);
void lbl_00003BDC(void);
void lbl_00004024(void);
void lbl_000040EC(void);
void lbl_00004450(void);
void lbl_00004570(void);
void lbl_000048C0(void);
void lbl_00004A14(void);
void lbl_00004E84(void);
void lbl_00004F68(void);
void lbl_00005044(void);
void lbl_000051A4(void);
void lbl_0000580C(void);
void lbl_00005824(void);
void lbl_00006124(void);
void lbl_00006490(void);
void lbl_0000669C(void);
void lbl_00006A94(void);
void lbl_00006B5C(void);
void lbl_00006B94(void);
void lbl_00006BF4(void);
void lbl_00006CCC(void);
void lbl_00006D14(void);
void lbl_00006DFC(void);
void lbl_00007EF8(void);
void lbl_00008134(void);
void lbl_000082C0(void);
void lbl_00008568(void);
void lbl_000085B4(void);
void lbl_0000893C(void);
void lbl_000089F8(void);
void lbl_00008C40(void);
void lbl_000090A0(void);
void lbl_000091EC(void);
void lbl_00009440(void);
void lbl_000097AC(void);
void lbl_000097C8(void);
void lbl_000099A4(void);
void lbl_00009A98(void);
void lbl_00009B04(void);
void lbl_00009C18(void);
void lbl_00009F4C(void);
void lbl_00009FB0(void);
void lbl_0000A098(void);
void lbl_0000A69C(void);
void lbl_0000A754(void);
void lbl_0000AD6C(void);
void lbl_0000AE94(void);
void lbl_0000AEE0(void);
void lbl_0000AF68(void);
struct PilotB000;
struct PilotSpray;
void lbl_0000B000(struct PilotB000 *p);
void lbl_0000B130(Vec *pos, Vec *vel, struct PilotSpray *e);
void lbl_0000B624(Vec *pos, Vec *vel, struct PilotSpray *e);
void lbl_0000BACC(void);

struct PilotB000
{
    /*0x00*/ f32 x;
    /*0x04*/ f32 y;
    /*0x08*/ f32 z;
    /*0x0C*/ f32 vx;
    /*0x10*/ f32 vy;
    /*0x14*/ f32 vz;
    /*0x18*/ f32 scale;
    /*0x1C*/ f32 unk1C;
    /*0x20*/ f32 unk20;
    /*0x24*/ u32 flags;
};

struct PilotSpray
{
    /*0x00*/ u32 count;
    /*0x04*/ u32 unk4;
    /*0x08*/ f32 unk8;
    /*0x0C*/ struct PilotB000 parts[1];
};

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
struct PilotSmoke
{
    /*0x00*/ Vec pos;
    /*0x0C*/ Vec vel;
    /*0x18*/ f32 scale;
    /*0x1C*/ f32 unk1C;
    /*0x20*/ f32 unk20;
};
void gxutil_draw_line_multicolor(struct PointWithColor *start, struct PointWithColor *end);
void lbl_0000B454(struct PilotSmoke *p);

#pragma force_active on
void lbl_0000B130(Vec *pos, Vec *vel, struct PilotSpray *e)
{
    u8 *k = (u8 *)lbl_0000C690;
    struct PilotB000 *p;
    struct PilotB000 *parts = e->parts;
    u32 i;
    struct GMAModel *model;
    f32 t;
    f32 sc;
    f32 u;
    f32 r;

    model = minigameGma->modelEntries[137].model;

    if (pos->y > *(f32 *)(k + 0))
    {
        t = *(f32 *)(k + 0);
    }
    else
    {
        u = (*(f32 *)(k + 0x24) + pos->y) / *(f32 *)(k + 0x24);
        t = u;
        if (u < *(f32 *)(k + 0))
            t = *(f32 *)(k + 0);
    }

    if (!(debugFlags & 0xA))
        e->unk8 += *(f32 *)(k + 0x28) * t;

    sc = *(f32 *)(k + 0x2C) * t;

    p = parts;
    for (i = 0; i < e->count; p++, i++)
    {
        if (p->unk20 > *(f32 *)(k + 0))
        {
            lbl_0000B000(p);
            avdisp_set_alpha(p->unk1C);
            gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
            avdisp_draw_model_unculled_sort_none(model);
        }
        else if (!(debugFlags & 0xA) && e->unk8 > *(f32 *)(k + 0x20))
        {
            p->unk20 = *(f32 *)(k + 0x18) + *(f32 *)(k + 0x30) * (((f32 *)k)[6] * (rand() / *(f32 *)(k + 0x34)));
            p->scale = sc * (*(f32 *)(k + 0x38) + (rand() / *(f32 *)(k + 0x34)));
            p->flags = 0;
            if ((rand() / *(f32 *)(k + 0x34)) < *(f32 *)(k + 0x3C))
            {
                if ((rand() / *(f32 *)(k + 0x34)) < *(f32 *)(k + 0x40))
                    p->flags |= 1;
                else
                    p->flags |= 2;
            }
            *(Vec *)p = *pos;
            p->vx = *(f32 *)(k + 0x44) * vel->x;
            p->vy = vel->y;
            p->vz = *(f32 *)(k + 0x44) * vel->z;
            p->vx += *(f32 *)(k + 0x38) * ((rand() / *(f32 *)(k + 0x34)) - *(f32 *)(k + 0x40));
            p->vz += *(f32 *)(k + 0x38) * ((rand() / *(f32 *)(k + 0x34)) - *(f32 *)(k + 0x40));
            p->unk1C = *(f32 *)(k + 0x20);
            e->unk8 -= *(f32 *)(k + 0x20);
        }
    }
}

void lbl_0000B454(struct PilotSmoke *p)
{
    Vec *g = (Vec *)lbl_100000B8;
    u8 *k = (u8 *)lbl_0000C690;
    f32 *kf;
    struct PointWithColor start;
    struct PointWithColor end;
    Vec v;

    if (!(debugFlags & 0xa))
    {
        p->pos.x += p->vel.x + *(f32 *)(k + 0x3C) * g->x;
        p->pos.y += p->vel.y + *(f32 *)(k + 0x3C) * g->y;
        p->pos.z += p->vel.z + *(f32 *)(k + 0x3C) * g->z;
    }
    start.color.r = start.color.g = start.color.b = 0xFF;
    start.color.a = *(f32 *)(k + 0x50) * p->unk1C;
    start.pos = p->pos;
    end.color.r = end.color.g = end.color.b = 0xFF;
    end.color.a = 0;
    mathutil_vec_set_len(&p->vel, &v, *(f32 *)(k + 0x2C));
    end.pos.x = p->pos.x - v.x;
    end.pos.y = p->pos.y - v.y;
    end.pos.z = p->pos.z - v.z;
    if (!(debugFlags & 0xa))
    {
        p->vel.x *= *(f32 *)(k + 0x54);
        p->vel.z *= *(f32 *)(k + 0x54);
        p->vel.y -= *(f32 *)(k + 0x58);
        p->unk1C *= *(f32 *)(k + 0x44);
        kf = (f32 *)k;
        if (p->pos.y < *kf)
            p->unk20 = *kf;
        else
            p->unk20 -= kf[8];
    }
    mathutil_mtxA_from_mtxB();
    gxutil_draw_line_multicolor(&start, &end);
}
void lbl_0000B624(Vec *pos, Vec *vel, struct PilotSpray *e)
{
    u8 *k = (u8 *)lbl_0000C690;
    u32 i;
    struct PilotB000 *parts = e->parts;
    s32 flag;
    f32 a;
    Vec up;
    Vec dir;
    Quaternion q;
    Vec v;

    up = *(Vec *)(k + 0x5C);
    dir = *vel;
    mathutil_vec_normalize_len(&dir);
    mathutil_quat_from_dirs(&q, &up, &dir);
    mathutil_mtxA_from_quat(&q);
    mathutil_mtxA_normalize_basis();
    e->unk8 += *(f32 *)(k + 0x68) * mathutil_sqrt(mathutil_vec_sq_len(vel));
    gxutil_set_line_width(0x14);
    gxutil_set_line_blend_params(1, 2, 1, 0xF);

    for (i = 0; i < e->count; i++)
    {
        if (parts[i].unk20 > *(f32 *)(k + 0))
        {
            mathutil_mtxA_push();
            lbl_0000B454((struct PilotSmoke *)&parts[i]);
            mathutil_mtxA_pop();
        }
        else if (e->unk8 > *(f32 *)(k + 0x20))
        {
            a = rand() / *(f32 *)(k + 0x34) - *(f32 *)(k + 0x40);
            parts[i].flags = 0;
            if (!(debugFlags & 0xA))
                parts[i].unk20 = *(f32 *)(k + 0x18) + *(f32 *)(k + 0x30) * (((f32 *)k)[6] * (rand() / *(f32 *)(k + 0x34)));
            parts[i].scale = *(f32 *)(k + 0x38);
            flag = (rand() / *(f32 *)(k + 0x34)) > *(f32 *)(k + 0x38);
            if (flag)
            {
                if (a < *(f32 *)(k + 0))
                    a -= *(f32 *)(k + 0x6C);
                else
                    a += *(f32 *)(k + 0x6C);
                v.x = a;
                v.y = *(f32 *)(k + 0);
                v.z = *(f32 *)(k + 0x70) * ((rand() / *(f32 *)(k + 0x34)) - *(f32 *)(k + 0x3C));
            }
            else
            {
                v.x = (rand() / *(f32 *)(k + 0x34)) - *(f32 *)(k + 0x40);
                v.y = *(f32 *)(k + 0);
                v.z = *(f32 *)(k + 0x6C) * a - *(f32 *)(k + 0x74);
            }
            mathutil_mtxA_tf_vec(&v, &v);
            parts[i].x = pos->x + v.x;
            parts[i].y = *(f32 *)(k + 0);
            parts[i].z = pos->z + v.z;
            if (flag)
            {
                parts[i].vx = a * (*(f32 *)(k + 0x78) * (rand() / *(f32 *)(k + 0x34)));
                parts[i].vy = *(f32 *)(k + 0x7C) * (rand() / *(f32 *)(k + 0x34));
                parts[i].vz = *(f32 *)(k + 0x80) * mathutil_vec_len(vel);
            }
            else
            {
                parts[i].vx = *(f32 *)(k + 0x38) * (rand() / *(f32 *)(k + 0x34)) - *(f32 *)(k + 0x3C);
                parts[i].vy = *(f32 *)(k + 0x84) * (rand() / *(f32 *)(k + 0x34));
                a = mathutil_vec_len(vel);
                parts[i].vz = a * (*(f32 *)(k + 0x88) * (rand() / *(f32 *)(k + 0x34)) - *(f32 *)(k + 0x74));
            }
            mathutil_mtxA_tf_vec((Vec *)&parts[i].vx, (Vec *)&parts[i].vx);
            parts[i].unk1C = *(f32 *)(k + 0x20);
            e->unk8 -= *(f32 *)(k + 0x20);
        }
    }
}

asm void lbl_0000BACC(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_pilot/lbl_0000BACC.s"
}

#pragma force_active reset
