/*
 * mini_pilot.c -- REL module: isolated function lbl_00007EF8.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "game.h"
#include "input.h"
#include "item.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "ord_tbl.h"
#include "pause_menu.h"
#include "pool.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "stcoli.h"
#include "vibration.h"
#include "window.h"
#include "avdisp.h"
#include "background.h"
#include "effect.h"
#include "gxutil.h"
#include "hud.h"
#include "info.h"
#include "lens_flare.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "rend_efc.h"
#include "shadow.h"
#include "spline.h"
#include "stobj.h"
#include "world.h"
#include "stdlib.h"

// The fly-in camera TU's .rodata pool, reached through one hoisted base
// register in the original.  Only the constants this function reads are named;
// everything else in the run belongs to its siblings, still in asm.
struct PilotCamConsts
{
    /*0x00*/ u8 filler0[0x8];
    /*0x08*/ f32 zeroF;        // 0.0f
    /*0x0C*/ u8 filler0C[0x58 - 0x0C];
    /*0x58*/ f64 startFrame;   // 50.0
    /*0x60*/ f64 zero;         // 0.0
    /*0x68*/ f64 endFrame;     // 480.0
    /*0x70*/ f32 endFrameF;    // 480.0f
    /*0x74*/ u8 filler74[4];
    /*0x78*/ f64 pullBack;     // 1.2
};

// Tail of lbl_0000CCF8: the per-difficulty spline tables the fly-in camera
// samples.  eye[i]/lookAt[i] each point at a 3-entry array of `struct Spline *`
// (x, y, z); zoom is a spline segment list read directly.  Field names are
// reconstructed from the uses below -- the originals are unknown.
struct PilotCamSplines
{
    /*0x000*/ u8 filler0[0x488];
    /*0x488*/ struct Spline **eye[3];
    /*0x494*/ struct Spline **lookAt[3];
    /*0x4A0*/ struct Spline zoom[3];
};

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_pilot.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000BE80[];
extern u8 lbl_0000BEB0[];
extern u8 lbl_0000BEB4[];
extern u8 lbl_0000BEE0[];
extern u8 lbl_0000BFD0[];
extern u8 lbl_0000BFE0[];
extern u8 lbl_0000BFE8[];
extern u8 lbl_0000C010[];
extern u8 lbl_0000C030[];
extern u8 lbl_0000C2A8[];
extern u8 lbl_0000C2C8[];
extern u8 lbl_0000C2F0[];
extern u8 lbl_0000C348[];
extern u8 lbl_0000C358[];
extern u8 lbl_0000C360[];
extern u8 lbl_0000C3C0[];
extern u8 lbl_0000C3C8[];
extern u8 lbl_0000C3CC[];
extern u8 lbl_0000C430[];
extern u8 lbl_0000C548[];
extern u8 lbl_0000C5B8[];
extern u8 lbl_0000C5C0[];
extern u8 lbl_0000C690[];
extern u8 lbl_0000C6D8[];
extern u8 lbl_0000C740[];
extern u8 lbl_0000C748[];
extern u8 lbl_0000C7BC[];
extern u8 lbl_0000C7CC[];
extern u8 lbl_0000C7EC[];
extern u8 lbl_0000C88C[];
extern u8 lbl_0000CB0C[];
extern u8 lbl_0000CBCC[];
extern u8 lbl_0000CCF8[];
extern u8 lbl_0000D1C8[];
extern u8 lbl_0000D218[];
extern u8 lbl_0000D2E8[];
extern u8 lbl_0000D300[];
extern u8 lbl_0000D314[];
extern u8 lbl_0000D320[];
extern u8 lbl_0000D324[];
extern u8 lbl_0000D328[];
extern u8 lbl_0000D338[];
extern u8 lbl_0000D360[];
extern u8 lbl_0000D368[];
extern u8 lbl_0000D3A0[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000018[];
extern u8 lbl_1000001E[];
extern u8 lbl_10000020[];
extern u8 lbl_10000034[];
extern u8 lbl_10000038[];
extern u8 lbl_1000003C[];
extern u8 lbl_10000040[];
extern u8 lbl_10000044[];
extern u8 lbl_10000054[];
extern u8 lbl_1000005C[];
extern u8 lbl_10000064[];
extern u8 lbl_10000066[];
extern u8 lbl_10000068[];
extern u8 lbl_10000074[];
extern u8 lbl_10000078[];
extern u8 lbl_10000087[];
extern u8 lbl_10000088[];
extern u8 lbl_1000008A[];
extern u8 lbl_1000008C[];
extern u8 lbl_10000090[];
extern u8 lbl_10000098[];
extern u8 lbl_100000A8[];
extern u8 lbl_100000B0[];
extern u8 lbl_100000B8[];
extern u8 neutralFaceTable[];
extern u8 smileFaceTable[];
extern u8 lbl_80285A58[];
extern u8 lbl_80285A68[];
extern u8 lbl_80285A80[];
extern u8 lbl_802F1F10[];
extern u8 lbl_802F1FD0[];
extern u8 lbl_802F1FD8[];
extern u8 lbl_802F1FDC[];
extern u8 lbl_802F1FE0[];
extern u8 lbl_802F1FE4[];
extern u8 lbl_802F1FEC[];
extern u8 lbl_802F1FF4[];

// Imported functions the code calls that no included header declares.
extern void ball_8003BBF4();
extern void draw_test_camera_target();
extern void func_80042214();
extern void func_8009C5E4();
extern void func_8009CD5C();
extern void func_8009D794();
extern void func_8009DB40();
extern void func_800AB2A0();
extern void func_800AB444();
extern void func_800AB6F8();
extern void func_800AC43C();
extern void func_800AC5E0();
extern void gxutil_draw_line_multicolor();
extern void item_create();
extern void mini_commend_free_data();
extern void qsort();
extern void set_shape_flags_in_model();
extern void stcoli_sub35();
extern void u_load_minigame_graphics();
extern void thread_create();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_000003B4(void);
void lbl_0000044C(void);
void lbl_000004E0(void);
void lbl_00000648(void);
void lbl_0000066C(void);
void lbl_00000698(void);
void lbl_000007B8(void);
void lbl_000008AC(void);
void lbl_00000A30(void);
void lbl_00000BFC(void);
void lbl_0000215C(void);
void lbl_000021B4(void);
void lbl_000022D8(void);
void lbl_00003B6C(void);
void lbl_00003BDC(void);
void lbl_00004024(void);
void lbl_000040EC(void);
void lbl_00004450(void);
void lbl_00004570(void);
void lbl_000048C0(void);
void lbl_00004A14(void);
void lbl_00004E84(void);
void lbl_00004F68(void);
void lbl_00005044(void);
void lbl_000051A4(void);
void lbl_0000580C(void);
void lbl_00005824(void);
void lbl_00006124(void);
void lbl_00006490(void);
void lbl_0000669C(void);
void lbl_00006B5C(void);
void lbl_00006B94(void);
void lbl_00006BF4(void);
void lbl_00006CCC(void);
void lbl_00006D14(void);
void lbl_00006DFC(void);
void lbl_00007EF8(struct Camera *camera);
void lbl_00008134(void);
void lbl_000082C0(void);
void lbl_00008568(void);
void lbl_000085B4(void);
void lbl_0000893C(void);
void lbl_000089F8(void);
void lbl_00008C40(void);
void lbl_000090A0(void);
void lbl_000091EC(void);
void lbl_00009440(void);
void lbl_000097AC(void);
void lbl_000097C8(void);
void lbl_000099A4(void);
void lbl_00009A98(void);
void lbl_00009B04(void);
void lbl_00009C18(void);
void lbl_00009F4C(void);
void lbl_00009FB0(void);
void lbl_0000A098(void);
void lbl_0000A69C(void);
void lbl_0000A754(void);
void lbl_0000AD6C(void);
void lbl_0000AE94(void);
void lbl_0000AEE0(void);
void lbl_0000AF68(void);
void lbl_0000B000(void);
void lbl_0000B130(void);
void lbl_0000B624(void);
void lbl_0000BACC(void);

#pragma force_active on
void lbl_00007EF8(struct Camera *camera)
{
    struct PilotCamSplines *tbl = (struct PilotCamSplines *)lbl_0000CCF8;
    struct PilotCamConsts *k = (struct PilotCamConsts *)lbl_0000C2C8;
    struct Spline **eyeSpline;
    struct Spline **lookAtSpline;
    Vec delta;
    f32 scale;
    f32 t;
    s32 unused;

    t = (f32)lbl_802F1FF0 - k->startFrame;
    eyeSpline = tbl->eye[*(s16 *)lbl_10000040];
    lookAtSpline = tbl->lookAt[*(s16 *)lbl_10000040];
    if (t < k->zero)
        t = k->zeroF;
    if (t > k->endFrame)
        t = k->endFrameF;

    camera->eye.x = calc_spline(t, eyeSpline[0]);
    camera->eye.y = calc_spline(t, eyeSpline[1]);
    camera->eye.z = calc_spline(t, eyeSpline[2]);
    camera->lookAt.x = calc_spline(t, lookAtSpline[0]);
    camera->lookAt.y = calc_spline(t, lookAtSpline[1]);
    camera->lookAt.z = calc_spline(t, lookAtSpline[2]);

    if ((s32)((u8 *)lbl_10000078)[*(s8 *)lbl_10000090] == 1)
    {
        scale = calc_spline(t, tbl->zoom);
        scale *= k->pullBack;
        delta.x = camera->eye.x - camera->lookAt.x;
        delta.y = camera->eye.y - camera->lookAt.y;
        delta.z = camera->eye.z - camera->lookAt.z;
        delta.x *= scale;
        delta.y *= scale;
        delta.z *= scale;
        camera->eye.x += delta.x;
        camera->eye.y += delta.y;
        camera->eye.z += delta.z;
    }

    delta.x = camera->lookAt.x - camera->eye.x;
    delta.y = camera->lookAt.y - camera->eye.y;
    delta.z = camera->lookAt.z - camera->eye.z;
    camera->rotY = mathutil_atan2(delta.x, delta.z) - 0x8000;
    camera->rotX =
        mathutil_atan2(delta.y, mathutil_sqrt(mathutil_sum_of_sq_2(delta.x, delta.z)));
    camera->rotZ = 0;
}
#pragma force_active reset
