/*
 * mini_bowling.c -- REL module: isolated function lbl_000097B4.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "pool.h"
#include "rend_efc.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "pause_menu.h"
#include "string.h"
#include "avdisp.h"
#include "background.h"
#include "obj_collision.h"
#include "ord_tbl.h"
#include "stcoli.h"
#include "shadow.h"
#include "vibration.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_bowling.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000F020[];
extern u8 lbl_00010C40[];
extern u8 lbl_00010CC0[];
extern u8 lbl_00010CC8[];
extern u8 lbl_00010D58[];
extern u8 lbl_00010D60[];
extern u8 lbl_00010EE0[];
extern u8 lbl_00010EE8[];
extern u8 lbl_00010EF0[];
extern u8 lbl_00010F24[];
extern u8 lbl_00010F94[];
extern u8 lbl_00011250[];
extern u8 lbl_00011258[];
extern u8 lbl_000112C0[];
extern u8 lbl_000112C8[];
extern u8 lbl_00011338[];
extern u8 lbl_00011340[];
extern u8 lbl_00011490[];
extern u8 lbl_000146A0[];
extern u8 lbl_000147F8[];
extern u8 lbl_00014800[];
extern u8 lbl_00014B78[];
extern u8 lbl_00014BE8[];
extern u8 lbl_00014C00[];
extern u8 lbl_00014C08[];
extern u8 lbl_00014CB8[];
extern u8 lbl_00014D70[];
extern u8 lbl_00014D90[];
extern u8 lbl_00014E10[];
extern u8 lbl_00014F20[];
extern u8 lbl_00014F24[];
extern u8 lbl_00015020[];
extern u8 lbl_00015024[];
extern u8 lbl_00015040[];
extern u8 lbl_00015380[];
extern u8 lbl_00015388[];
extern u8 lbl_000153E0[];
extern u8 lbl_000153E4[];
extern u8 lbl_000153E8[];
extern u8 lbl_000153F4[];
extern u8 lbl_00015428[];
extern u8 lbl_00015434[];
extern u8 lbl_0001543C[];
extern u8 lbl_00015444[];
extern u8 lbl_00015454[];
extern u8 lbl_00015460[];
extern u8 lbl_0001546C[];
extern u8 lbl_00015480[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_1000000C[];
extern u8 lbl_1000013C[];
extern u8 lbl_1000013E[];
extern u8 lbl_1000013F[];
extern u8 lbl_10000154[];
extern u8 lbl_10000178[];
extern u8 lbl_100004C0[];
extern u8 lbl_100004E0[];
extern u8 lbl_10012140[];
extern u8 lbl_10012180[];
extern u8 lbl_10018510[];

// Imported functions the code calls that no included header declares.
extern void draw_test_camera_target();
extern void func_80071B08();
extern void func_8009C5E4();
extern void func_8009CD5C();
extern void func_8009D794();
extern void func_8009DB40();
extern void func_8009DDC4();
extern void func_800AB2A0();
extern void func_800AB444();
extern void func_800AB6F8();
extern void func_800AC43C();
extern void func_800AC5E0();
extern void mini_commend_free_data();
extern void u_load_minigame_graphics();
extern void u_set_minigame_callbacks_2();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_0000020C(void);
void lbl_00000718(void);
void lbl_000009EC(void);
void lbl_00000F98(void);
void lbl_00001888(void);
void lbl_00001908(void);
void lbl_00001B14(void);
void lbl_00001C84(void);
void lbl_00001F1C(void);
void lbl_000021B4(void);
void lbl_00002454(void);
void lbl_000027B0(void);
void lbl_000029A8(void);
void lbl_00002DE0(void);
void lbl_00003574(void);
void lbl_00003A10(void);
void lbl_00003D24(void);
void lbl_00003DC0(void);
void lbl_000042A4(void);
void lbl_00004410(void);
void lbl_000045E8(void);
void lbl_00004A80(void);
void lbl_00004BD8(void);
void lbl_00004D10(void);
void lbl_00004DF8(void);
void lbl_00005128(void);
void lbl_000051E0(void);
void lbl_000054BC(void);
void lbl_00005564(void);
void lbl_00005B0C(void);
void lbl_000066C4(void);
void lbl_000068C4(void);
void lbl_00006E64(void);
void lbl_00006F0C(void);
void lbl_00007518(void);
void lbl_00007650(void);
void lbl_000076D0(void);
void lbl_00007740(void);
void lbl_00007778(void);
void lbl_00007878(void);
void lbl_00007964(void);
void lbl_000079E8(void);
void lbl_00007A6C(void);
void lbl_00007C54(void);
void lbl_00007E74(void);
void lbl_00007FE0(void);
void lbl_000080E0(void);
void lbl_000082E4(void);
void lbl_000086E4(void);
void lbl_0000871C(void);
void lbl_000087CC(void);
void lbl_000089FC(void);
void lbl_00008B8C(void);
void lbl_00008C68(void);
void lbl_00008D2C(void);
void lbl_00008DF0(void);
void lbl_00008EC0(void);
void lbl_00008FB0(void);
void lbl_00009048(void);
void lbl_000090CC(void);
void lbl_00009134(void);
void lbl_0000919C(void);
void lbl_00009230(void);
void lbl_000096B4(void);
void lbl_000097B4(void);
void lbl_00009AA8(void);
void lbl_00009D18(void);
void lbl_00009F60(int idx);
void lbl_0000A23C(int kind, Vec *pos);
void lbl_0000A778(int sndId, f32 *pos, int vol, int pitch);
void lbl_0000A808(void);
void lbl_0000A878(void);
void lbl_0000AAAC(void);
void lbl_0000AB98(void);
void lbl_0000AC60(void);
void lbl_0000AD8C(void);
void lbl_0000AF18(void);
void lbl_0000AFEC(void);
void lbl_0000B0AC(void);
void lbl_0000B1BC(void);
void lbl_0000B344(void);
void lbl_0000B460(void);
void lbl_0000B654(void);
void lbl_0000B848(void);
void lbl_0000B914(void);
void lbl_0000BDE0(void);
void lbl_0000BEB8(void);
void lbl_0000C0D0(void);
void lbl_0000C1D0(void);
void lbl_0000CAA8(void);
void lbl_0000D4D4(void);
void lbl_0000D598(void);
void lbl_0000D650(void);
void lbl_0000D7F8(void);
void lbl_0000D8CC(void);
void lbl_0000D90C(void);
void lbl_0000DA0C(void);
void lbl_0000DAF4(void);
void lbl_0000DD4C(void);
void lbl_0000DFA4(void);
void lbl_0000E22C(void);
void lbl_0000E3A0(void);
void lbl_0000E510(void);
void lbl_0000E5D4(void);
void lbl_0000E7B0(void);
void lbl_0000E870(void);
void lbl_0000E894(void);
void lbl_0000EC38(void);
void lbl_0000EDB0(void);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
int lbl_0000A138(void);
struct BowlSpark
{
    Vec pos;    // 0x00
    s16 timer;  // 0x0C
    s8 kind;    // 0x0E
    u8 pad;     // 0x0F
};
void lbl_0000A610(int kind, Vec *pos);

// ---- lbl_00009D18 support declarations ------------------------------------
// UNVERIFIED types: neither struct below is confirmed against a symbol file.
// BowlSparkCol is inferred purely from the load displacements 0x00/0x04/0x08
// and 0x0c/0x10/0x14 off a base stepped by `mulli rN,rKind,0x18`, and
// BowlSparkPal from the 21-iteration 8-byte `lwzu/stwu` copy loop (168 bytes)
// out of lbl_00011490 + 0x3238.
struct BowlSparkCol
{
    Vec a;  // 0x00
    Vec b;  // 0x0C
};
struct BowlSparkPal
{
    struct BowlSparkCol c[7];  // 7 * 0x18 == 0xA8 == the 21 x 8 bytes copied
};
#pragma force_active on
// lbl_000097B4 (0x97B4): reset the whole particle bank and both spark banks,
// then compile five stages of a 40x64 ASCII pin bitmap at lbl_00011490 into
// per-stage x/y float arrays plus a live count.
// Four things this needed, each measured against the original in run 19:
//   - tp: a SECOND symbol-valued local seeding the modified walker rowsrc.
//     Without it mwcc stages lbl_00011490 through r0 and the function is one
//     instruction long.
//   - the declaration order src,out,rowbase,q,rowsrc,stage -- it decides which
//     of r6/r7 and r10/r11 carries the inner and the outer walker pair.
//   - f64 y, not f32 y: as f32 the whole volatile FPR pool rotates one slot
//     and n++ schedules two instructions early inside the 4x unrolled loop.
//   - src++ BEFORE col++ in the for-increment: the last unrolled copy emits
//     the two addi in source order.
struct BwlPart { u8 pad[0x18]; s16 timer; u8 pad2[2]; };

void lbl_000097B4(void)
{
    u8 *tp;
    u8 *t;
    u8 *work = lbl_100004E0;
    s8 *src;
    f32 *out;
    s8 *rowbase;
    f32 *q;
    s8 *rowsrc;
    f32 *stage;
    long i;
    int k;
    int row;
    int s;
    int col;
    int n;
    f64 y;

    tp = lbl_00011490;
    t = lbl_00011490;
    *(s16 *)(work + 0x11c6c) = 0;
    *(s16 *)(work + 0x11cac) = 0;
    *(s16 *)(work + 0x11c7c) = 0;
    *(s16 *)(work + 0x11cbc) = 0;
    *(s16 *)(work + 0x11c8c) = 0;
    *(s16 *)(work + 0x11ccc) = 0;
    *(s16 *)(work + 0x11c9c) = 0;
    *(s16 *)(work + 0x11cdc) = 0;
    for (i = 0; i < 0xa28; i++)
        ((struct BwlPart *)work)[i].timer = 0;
    *(s32 *)(work + 0x11ce0) = 0;

    rowsrc = (s8 *)tp;
    stage = (f32 *)(work + 0x11ce4);
    for (s = 0; s < 5; s++)
    {
        rowbase = rowsrc;
        q = stage;
        n = 0;
        for (row = 0; row < 0x28; row++)
        {
            y = *(f64 *)(t + 0x3200) - row;
            src = rowbase;
            out = q;
            for (col = 0; col < 64; src++, col++)
            {
                if (*src == 0x30)
                {
                    out[0] = -(*(f64 *)(t + 0x3208) - col);
                    out[635] = y;
                    out++;
                    q++;
                    n++;
                }
            }
            rowbase += 0x40;
        }
        *(s32 *)&stage[1270] = n;
        rowsrc += 0xa00;
        stage += 1271;
    }
}
#pragma peephole on
void lbl_00009AA8(void)
{
    u8 *pp = lbl_100004E0;
    u8 *work = lbl_100004E0;
    u8 *t = lbl_00011490;
    struct BowlSpark *s;
    struct BowlSpark *b;
    u8 *p;
    int i;
    int n;
    Vec sp8;

    n = 0;
    if (debugFlags & 0xa)
        return;

    b = (struct BowlSpark *)(work + 0x11ca0);
    for (i = 0; i < 4; i++, b++)
        if (b->timer > 0)
            b->timer--;

    s = (struct BowlSpark *)(work + 0x11c60);
    for (i = 0; i < 4; i++, s++)
    {
        if (s->timer <= 0)
            continue;
        s->timer--;
        if (s->timer <= 0)
        {
            s->timer = 0;
            lbl_0000A23C(s->kind, &s->pos);
            lbl_0000A778(0xac, (f32 *)s, 0x1b, 0x2000);
        }
        else if (s->timer & 1)
        {
            sp8.x = s->pos.x;
            sp8.y = s->pos.y
                  * (*(f64 *)(t + 0x3218) - *(f32 *)(t + 0x3220) * s->timer);
            sp8.z = s->pos.z;
            lbl_0000A610(6, &sp8);
        }
    }

    if (*(s32 *)(work + 0x11ce0) <= 0)
        return;

    p = pp;
    for (i = 0; i < 0xa28; i++, p += 0x1c)
    {
        if (n >= *(s32 *)(work + 0x11ce0))
            return;
        if (*(s16 *)(p + 0x18) <= 0)
            continue;
        *(f32 *)(p + 0xc) = *(f64 *)(t + 0x3228) * *(f32 *)(p + 0xc);
        *(f32 *)(p + 0x10) = *(f64 *)(t + 0x3228) * *(f32 *)(p + 0x10);
        *(f32 *)(p + 0x14) = *(f64 *)(t + 0x3228) * *(f32 *)(p + 0x14);
        *(f32 *)(p + 0x10) = *(f32 *)(p + 0x10) + *(f64 *)(t + 0x3230);
        *(f32 *)(p + 0) = *(f32 *)(p + 0xc) + *(f32 *)(p + 0);
        *(f32 *)(p + 4) = *(f32 *)(p + 0x10) + *(f32 *)(p + 4);
        *(f32 *)(p + 8) = *(f32 *)(p + 0x14) + *(f32 *)(p + 8);
        *(s16 *)(p + 0x18) = *(s16 *)(p + 0x18) - 1;
        if (*(s16 *)(p + 0x18) <= 0)
        {
            *(s16 *)(p + 0x18) = 0;
            *(s32 *)(work + 0x11ce0) -= 1;
        }
        else
            n++;
    }
}
// lbl_00009D18 (0x9D18): draw every live particle in the 0xA28-slot bank --
// the render half of lbl_00009AA8's update.  Each particle fades its scale in
// over the first 60 ticks and out over the last 30, and particles of kind 0..6
// additionally get a post-multiply colour lerped between two palette rows by
// the square of the remaining lifetime.
//
// The pre-loop count guard and the in-loop count test read the same address,
// work + 0x11ce0.  The original computes work + 0x10000 ONCE (addis r31,r6,1)
// and uses a 0x1ce0 displacement off it for both.  With propagation on, mwcc
// rewrites the guard's `work` back to the bare symbol and re-materialises it,
// costing three instructions; no source spelling found in runs 15-19 prevents
// that.  The pragma pair below is the fix and is balanced with a reset.
#pragma peephole on
#pragma opt_propagation off
void lbl_00009D18(void)
{
    u8 *t = lbl_00011490;
    u8 *pp = lbl_100004E0;
    u8 *work = lbl_100004E0;
    struct BowlSparkPal pal = *(struct BowlSparkPal *)(t + 0x3238);
    int i;
    u8 *p;
    int n;
    s16 tim;
    s16 tv;
    s8 kind;
    f32 scale;
    f32 s;
    f32 s2;
    f32 inv;

    n = 0;
    if (!(*(s32 *)(work + 0x11ce0) > 0))
        return;

    p = pp;
    for (i = 0; i < 0xa28; i++, p += 0x1c)
    {
        if (n >= *(s32 *)(work + 0x11ce0))
            return;
        tim = *(s16 *)(p + 0x18);
        if (tim <= 0)
            continue;
        n++;
        if (*(s8 *)(p + 0x1a) != 6 && tim < 0x3f
            && *(s16 *)(p + 0x18) < (rand() & 0x3f))
            continue;

        tv = *(s16 *)(p + 0x18);
        if (tv < 0x3c)
            scale = (f32)(*(f64 *)(t + 0x32e0) * (*(f64 *)(t + 0x32e8) * tv));
        else if (tv > 0x5a)
            scale = (f32)(*(f64 *)(t + 0x32f0)
                          * (*(f64 *)(t + 0x32e0) * (0x78 - tv)));
        else
            scale = *(f32 *)(t + 0x32f8);

        kind = *(s8 *)(p + 0x1a);
        if (kind > -1 && kind < 7)
        {
            s = *(f32 *)(t + 0x3220) * tv;
            s2 = s * s;
            inv = (f32)(*(f64 *)(t + 0x3218) - s2);
            avdisp_set_post_mult_color(s2 * pal.c[kind].a.x + inv * pal.c[kind].b.x,
                                       s2 * pal.c[kind].a.y + inv * pal.c[kind].b.y,
                                       s2 * pal.c[kind].a.z + inv * pal.c[kind].b.z,
                                       *(f32 *)(t + 0x32fc));
        }
        mathutil_mtxA_from_mtxB_translate((Vec *)p);
        mathutil_mtxA_sq_from_identity();
        mathutil_mtxA_scale_xyz(scale, scale, *(f32 *)(t + 0x32fc));
        GXLoadPosMtxImm(mathutilData->mtxA, 0);
        GXLoadNrmMtxImm(mathutilData->mtxA, 0);
        avdisp_draw_model_culled_sort_translucent(commonGma->modelEntries[0x1b].model);
    }
}
#pragma opt_propagation reset
// lbl_00009F60 (0x9F60): spawn one "spark" of the given kind in the first free
// slot of the four-slot bank, then fire its one-shot sound with a randomised
// volume and pitch.  Kinds 0..3 take a fixed offset from the parameter table;
// kinds 4..6 take a randomised one.
#pragma peephole on
void lbl_00009F60(int idx)
{
    u8 *t = lbl_00011490;
    struct BowlSpark *p;
    int i;
    int vol;
    int pitch;

    if (idx > -1 && idx < 7)
    {
        p = (struct BowlSpark *)lbl_10012140;
        for (i = 0; i < 4; i++, p++)
        {
            if (p->timer > 0)
                continue;
            p->timer = 120;
            p->kind = (s8)idx;
            switch (idx)
            {
            case 0:
            case 1:
            case 2:
            case 3:
                p->pos.x = *(f32 *)(t + 0x3300);
                p->pos.y = *(f32 *)(t + 0x3304);
                p->pos.z = *(f32 *)(t + 0x3308);
                goto tail;
            case 4:
            case 5:
            case 6:
                goto rnd;
            }
        rnd:
            p->pos.x = *(f64 *)(t + 0x3310)
                     + *(f64 *)(t + 0x3318) * (rand() / *(f32 *)(t + 0x3320));
            if (rand() & 1)
                p->pos.x = -p->pos.x;
            if (lbl_0000A138())
                p->pos.y = *(f64 *)(t + 0x3328)
                         + *(f64 *)(t + 0x3310) * (rand() / *(f32 *)(t + 0x3320));
            else
                p->pos.y = *(f64 *)(t + 0x3330)
                         + *(f64 *)(t + 0x3338) * (rand() / *(f32 *)(t + 0x3320));
            p->pos.z = *(f32 *)(t + 0x3308);
        tail:
            vol = (rand() & 0xf) - 50;
            pitch = (rand() & 0x1fff) + 0x1000;
            lbl_0000A778(0xab, (f32 *)p, vol, pitch);
            return;
        }
    }
}
// lbl_0000A138 (0xA138): is any of the four spark slots (in either bank) alive
// and of a "blocking" kind?
#pragma peephole on
int lbl_0000A138(void)
{
    struct BowlSpark *b;
    struct BowlSpark *a;
    int ret;
    int i;

    a = (struct BowlSpark *)lbl_10012140;
    b = (struct BowlSpark *)lbl_10012180;
    ret = 0;

    for (i = 0; i < 4; i++, a++, b++)
    {
        if (a->timer > 0)
        {
            switch (a->kind)
            {
            case 0:
            case 1:
            case 2:
            case 3:
                ret = 1;
                break;
            }
        }
        if (b->timer > 0)
        {
            switch (b->kind)
            {
            case 0:
            case 1:
            case 2:
            case 3:
                ret = 1;
                break;
            }
        }
        if (ret != 0)
            return ret;
    }
    return ret;
}
asm void lbl_0000A23C(int kind, Vec *pos)
{
    nofralloc
#include "../asm/nonmatchings/mini_bowling/lbl_0000A23C.s"
}
#pragma peephole on
void lbl_0000A610(int kind, Vec *pos)
{
    u8 *work = lbl_100004E0;
    u8 *t = lbl_00011490;
    u8 *p;
    int i;
    if (*(s32 *)(work + 0x11ce0) >= 0xa28)
        return;

    for (p = lbl_100004E0,  i = 0; i < 0xa28; i++) {
        if (*(s16 *)(p + 0x18) <= 0) {
            *(s16 *)(p + 0x18) = 30;
            *(Vec *)p = *pos;
            *(f32 *)(p + 0xc) =
                *(f64 *)(t + 0x32e0) - *(f64 *)(t + 0x3360) * (rand() / *(f32 *)(t + 0x3320));
            *(f32 *)(p + 0x10) =
                *(f64 *)(t + 0x32e0) - *(f64 *)(t + 0x3360) * (rand() / *(f32 *)(t + 0x3320));
            *(f32 *)(p + 0x14) =
                *(f64 *)(t + 0x32e0) - *(f64 *)(t + 0x3360) * (rand() / *(f32 *)(t + 0x3320));
            *(s8 *)(p + 0x1a) = (s8)kind;
            *(s32 *)(work + 0x11ce0) += 1;
            return;
        }
        p += 0x1c;
    }
}
#pragma force_active reset
