/*
 * mini_golf.c -- REL module: isolated function lbl_00007F34.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <dolphin.h>
#include "global.h"
#include "avdisp.h"
#include "ball.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "pool.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "stcoli.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "input.h"
#include "background.h"
#include "light.h"
#include "polydisp.h"
#include "gxcache.h"
#include "stdlib.h"
#include "effect.h"
#include "vibration.h"
#include "lens_flare.h"
#include "nl2ngc.h"
#include "shadow.h"
#include "ord_tbl.h"
#include "stobj.h"
#include "item.h"
#include "gxutil.h"
#include "rend_efc.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_golf.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_000260F0[];
extern u8 lbl_00026118[];
extern u8 lbl_00026158[];
extern u8 lbl_000261E8[];
extern u8 lbl_000261F0[];
extern u8 lbl_000262F0[];
extern u8 lbl_00026378[];
extern u8 lbl_00026380[];
extern u8 lbl_00026390[];
extern u8 lbl_000263B0[];
extern u8 lbl_000264A8[];
extern u8 lbl_000264C8[];
extern u8 lbl_000264E0[];
extern u8 lbl_00026510[];
extern u8 lbl_00026538[];
extern u8 lbl_00026550[];
extern u8 lbl_000266A0[];
extern u8 lbl_000266F8[];
extern u8 lbl_00026A38[];
extern u8 lbl_00026A44[];
extern u8 lbl_00026A60[];
extern u8 lbl_00026A98[];
extern u8 lbl_00026AA0[];
extern u8 lbl_00026AB0[];
extern u8 lbl_00026AC4[];
extern u8 lbl_00026AEC[];
extern u8 lbl_00026AF0[];
extern u8 lbl_00026AF4[];
extern u8 lbl_00026AF8[];
extern u8 lbl_00026B40[];
extern u8 lbl_00026BCC[];
extern u8 lbl_00026BE8[];
extern u8 lbl_00026D08[];
extern u8 lbl_00026D50[];
extern u8 lbl_00026DA0[];
extern u8 lbl_00026DF0[];
extern u8 lbl_00026DF4[];
extern u8 lbl_00026E10[];
extern u8 lbl_00026E28[];
extern u8 lbl_00026FB8[];
extern u8 lbl_0002A4D8[];
extern u8 lbl_0002A9E8[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000010[];
extern u8 lbl_1000003A[];
extern u8 lbl_1000003E[];
extern u8 lbl_10000046[];
extern u8 lbl_10000048[];
extern u8 lbl_1000005C[];
extern u8 lbl_100000C8[];
extern u8 lbl_100000D0[];
extern u8 lbl_100000EB[];
extern u8 lbl_100000ED[];
extern u8 lbl_100000F6[];
extern u8 lbl_100000F8[];
extern u8 lbl_100000FB[];
extern u8 lbl_10000100[];
extern u8 lbl_10000130[];
extern u8 lbl_10000170[];
extern u8 lbl_10000178[];
extern u8 lbl_10000190[];
extern u8 lbl_100001C8[];
extern u8 lbl_100001CA[];
extern u8 lbl_100001D4[];
extern u8 lbl_10000204[];
extern u8 lbl_10000210[];
extern u8 lbl_10000248[];

// Imported functions the code calls that no included header declares.
extern void u_load_minigame_graphics();
extern void u_set_minigame_callbacks_2();
extern void __cvt_fp2unsigned();
extern void draw_test_camera_target();
extern void func_800AB444();
extern void func_8009CD5C();
extern void func_800AB6F8();
extern void func_800AB2A0();
extern void func_800AC43C();
extern void func_8009C5E4();
extern void func_8009D794();
extern void func_800AC5E0();
extern void alloc_pool_light();
extern void mini_commend_free_data();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void lbl_000000C8(void);
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_0000027C(void);
void lbl_000002A8(void);
void lbl_000005CC(void);
void lbl_000056C4(void);
void lbl_00007F34(void);
void lbl_00008A44(void);
void lbl_00008C78(void);
void lbl_00008D34(void);
void lbl_00008F44(void);
void lbl_0000907C(void);
u8 lbl_00009178(void);
u8 lbl_000091BC(void);
void lbl_000092C4(void);
void lbl_000092D0(void);
void lbl_000092E0(void);
void lbl_000092F0(void);
void lbl_00009300(void);
void lbl_00009310(void);
void lbl_00009320(void);
void lbl_00009340(void);
void lbl_00009360(void);
void lbl_00009384(void);
void lbl_00009394(void);
void lbl_000093A4(void);
void lbl_000093B4(void);
void lbl_000093C4(void);
void lbl_000093D4(void);
void lbl_000093F0(void);
void lbl_00009404(void);
void lbl_00009414(void);
void lbl_00009424(void);
void lbl_00009438(void);
void lbl_00009448(void);
void lbl_00009458(void);
void lbl_00009478(void);
void lbl_00009488(void);
void lbl_00009538(void);
void lbl_000095C4(void);
void lbl_000097D8(void);
void lbl_00009800(void);
void lbl_0000982C(void);
void lbl_00009880(void);
void lbl_00009968(void);
void lbl_000099B4(void);
void lbl_000099E0(void);
f32 lbl_00009B68(Vec *arg);
void lbl_00009C10(void);
void lbl_00009C50(void);
void lbl_0000B280(void);
void lbl_0000B36C(void);
void lbl_0000B754(void);
void lbl_0000B8A8(void);
void lbl_0000BDEC(void);
void lbl_0000C128(void);
void lbl_0000C230(void);
void lbl_0000C33C(void);
void lbl_0000D64C(void);
void lbl_0000E8AC(void);
void lbl_0000E998(void);
void lbl_0000E99C(void);
void lbl_0000F11C(void);
void lbl_0000F194(void);
void lbl_0000F290(void);
void lbl_0000F750(void);
void lbl_0000F7E8(void);
void lbl_0000FA18(void);
void lbl_0000FBC8(void);
void lbl_0000FCE0(void);
void lbl_000100D4(void);
void lbl_00010304(void);
void lbl_000106B8(void);
void lbl_00010808(void);
void lbl_000109CC(void);
void lbl_00010E68(void);
void lbl_00010E74(void);
void lbl_00011254(void);
void lbl_000115F8(void);
void lbl_0001199C(void);
void lbl_00011A6C(void);
void lbl_00011DAC(void);
void lbl_00011FEC(void);
void lbl_000123B4(void);
void lbl_00012A14(void);
void lbl_00012C80(void);
void lbl_00012EEC(void);
void lbl_00013664(void);
void lbl_00015520(void);
void lbl_0001B5B8(void);
void lbl_00022524(void);
void lbl_00022610(void);
void lbl_00022904(void);
void lbl_00022D4C(void);
void lbl_000230E4(void);
void lbl_00023AB4(void);
void lbl_00023C68(void);
void lbl_00023DC4(void);
void lbl_00023DD4(void);
void lbl_000240C0(void);
void lbl_000245D4(void);
void lbl_000246E8(void);
void lbl_00024A40(void);
void lbl_00024E70(void);
void lbl_000252C0(void);
void lbl_0002544C(void);
void lbl_000255CC(void);
void lbl_00025928(void);
void lbl_00025A44(void);
void lbl_00025B10(void);
void lbl_00025B70(void);
void lbl_00025BD0(void);
void lbl_00025EA8(void);
void lbl_0002609C(void);
void lbl_000260C0(void);

#pragma force_active on
void lbl_00007F34(void)
{
    u32 scores[4];
    u8 ranks[4];
    u8 order[4];
    u16 scores2[4];
    u8 ranks2[4];
    u8 order2[4];
    u8 *st = (u8 *)lbl_10000000;
    u8 *k = (u8 *)lbl_000260F0;
    u8 *base = (u8 *)lbl_00026AB0;
    s8 *status;
    u32 sel;
    u32 q;
    int i;
    int j;
    int i2;
    int j2;
    int bestScore;
    int rank;
    int same;
    int rank2;
    int same2;
    s8 best2;
    u32 tmp;
    u8 tmp8;
    u8 tmp8b;
    u16 tmp16;
    f32 bestDist;

    status = &g_poolInfo.playerPool.statusList[modeCtrl.currPlayer];
    if (*status == 2)
        *status = 4;

    playerInfos[modeCtrl.currPlayer] = infoWork;
    sel = 0x63;
    lbl_801F3A8C[modeCtrl.currPlayer] = modeCtrl.courseFlags;
    bestDist = *(f32 *)k;

    if (lbl_000091BC()) {
        if ((s32)lbl_802F1BE8.unk0 == 1) {
            if (modeCtrl.currPlayer == 0)
                sel = 1;
            else
                sel = 0;
            if (mathutil_sqrt(mathutil_sum_of_sq_3(
                    ballInfo[sel].pos.x - decodedStageLzPtr->startPos->pos.x,
                    *(f32 *)k,
                    ballInfo[sel].pos.z - decodedStageLzPtr->startPos->pos.z)) >
                *(f64 *)(k + 0x68)) {
                if ((base + sel * 0x12)[*(s16 *)(st + 0x3a) + 0x48] != 0)
                    sel = (sel + 1) & 1;
            }
        } else if ((s32)lbl_802F1BE8.unk0 == 0) {
            for (i = 0; i < modeCtrl.playerCount; i++) {
                scores[i] = 0;
                order[i] = i;
                if (*(s16 *)(st + 0x3a) > 0)
                    scores[i] = (base + i * 0x12)[*(s16 *)(st + 0x3a) + 0x47];
                else
                    scores[i] = 0;
                if (mathutil_sqrt(mathutil_sum_of_sq_3(
                        ballInfo[i].pos.x - decodedStageLzPtr->startPos->pos.x,
                        *(f32 *)k,
                        ballInfo[i].pos.z - decodedStageLzPtr->startPos->pos.z)) >
                        *(f64 *)(k + 0x68) ||
                    base[0x40 + i] != 0)
                    scores[i] += 1000;
            }
            j = 0;
            for (i = 0; i < modeCtrl.playerCount; i++) {
                if ((base + i * 0x12)[*(s16 *)(st + 0x3a) + 0x48] == 0)
                    j = 1;
            }
            if (j == 0) {
                for (i = 0; i < modeCtrl.playerCount; i++) {
                    if (scores[i] < 1000)
                        scores[i] = (base + i * 0x12)[*(s16 *)(st + 0x3a) + 0x48];
                }
            } else {
                for (i = 0; i < modeCtrl.playerCount; i++) {
                    if ((base + i * 0x12)[*(s16 *)(st + 0x3a) + 0x48] != 0)
                        scores[i] += 1000;
                }
            }
            bestScore = 1000;
            for (i = 0; i < modeCtrl.playerCount; i++) {
                if (scores[i] < 1000 && scores[i] < bestScore)
                    bestScore = scores[i];
            }
            for (i = 0; i < modeCtrl.playerCount; i++) {
                if (bestScore == scores[i])
                    scores[i] = (base + i * 0x12)[*(s16 *)(st + 0x3a) + 0x47];
                else
                    scores[i] = 1000;
            }
            for (i = 0; i < modeCtrl.playerCount; i++) {
                for (j = i; j < modeCtrl.playerCount; j++) {
                    if (scores[i] > scores[j]) {
                        tmp = scores[i];
                        scores[i] = scores[j];
                        scores[j] = tmp;
                        tmp8 = order[i];
                        order[i] = order[j];
                        order[j] = tmp8;
                    }
                }
            }
            rank = 0;
            same = 1;
            for (i = 0; i < modeCtrl.playerCount; i++) {
                ranks[order[i]] = rank;
                if (scores[i] != scores[i + 1]) {
                    rank += same;
                    same = 1;
                } else {
                    same += 1;
                }
            }
            bestScore = 9;
            for (i = 0; i < modeCtrl.playerCount; i++) {
                if (ranks[i] == 0 && bestScore > i) {
                    sel = i;
                    bestScore = i;
                }
            }
        }
    } else {
        for (q = 0; q < modeCtrl.playerCount; q++) {
            if (mathutil_sqrt(mathutil_sum_of_sq_3(
                    ballInfo[q].pos.x - decodedStageLzPtr->startPos->pos.x,
                    *(f32 *)k,
                    ballInfo[q].pos.z - decodedStageLzPtr->startPos->pos.z)) <
                *(f64 *)(k + 0x68)) {
                ballInfo[q].pos.x = decodedStageLzPtr->startPos->pos.x;
                ballInfo[q].pos.z = decodedStageLzPtr->startPos->pos.z;
            }
            if (lbl_00009B68(&ballInfo[q].pos) - bestDist > *(f64 *)(k + 0x68)) {
                if (base[0x40 + q] == 0) {
                    bestDist = lbl_00009B68(&ballInfo[q].pos);
                    sel = q;
                }
            }
        }
    }

    if (sel == 0x63)
        sel = 0;

    if (lbl_00009178() == 0 && sel != modeCtrl.currPlayer) {
        modeCtrl.currPlayer = sel;
        u_somePlayerId = modeCtrl.currPlayer;
        lbl_802F1DFC = playerCharacterSelection[u_somePlayerId];
        u_play_sound_0(0x1e);
    } else {
        modeCtrl.currPlayer = sel;
    }

    infoWork = playerInfos[modeCtrl.currPlayer];
    modeCtrl.courseFlags = lbl_801F3A8C[modeCtrl.currPlayer];

    if (lbl_00009178()) {
        for (q = 0; q < modeCtrl.playerCount; q++)
            base[0x40 + q] = 0;
        *(s16 *)(st + 0x3a) = *(s16 *)(st + 0x3a) + 1;
        if ((s32)lbl_802F1BE8.unk0 == 1) {
            if (*(s16 *)(st + 0x3a) == 0) {
                modeCtrl.currPlayer = 0;
            } else {
                for (i2 = *(s16 *)(st + 0x3a) - 1; i2 >= 0; i2--) {
                    if (base[i2 + 0x48] > base[i2 + 0x5a]) {
                        modeCtrl.currPlayer = 1;
                        break;
                    } else if (base[i2 + 0x48] < base[i2 + 0x5a]) {
                        modeCtrl.currPlayer = 0;
                        break;
                    } else if (i2 == 0) {
                        modeCtrl.currPlayer = 0;
                        break;
                    }
                }
            }
        } else if ((s32)lbl_802F1BE8.unk0 == 0) {
            for (i2 = 0; i2 < modeCtrl.playerCount; i2++) {
                scores2[i2] = 0;
                order2[i2] = i2;
                if (*(s16 *)(st + 0x3a) > 0)
                    scores2[i2] = (base + i2 * 0x12)[*(s16 *)(st + 0x3a) + 0x47];
                else
                    scores2[i2] = 0;
            }
            for (i2 = 0; i2 < modeCtrl.playerCount; i2++) {
                for (j2 = i2; j2 < modeCtrl.playerCount; j2++) {
                    if (scores2[i2] > scores2[j2]) {
                        tmp16 = scores2[i2];
                        scores2[i2] = scores2[j2];
                        scores2[j2] = tmp16;
                        tmp8b = order2[i2];
                        order2[i2] = order2[j2];
                        order2[j2] = tmp8b;
                    }
                }
            }
            rank2 = 0;
            same2 = 1;
            for (i2 = 0; i2 < modeCtrl.playerCount; i2++) {
                ranks2[order2[i2]] = rank2;
                if (scores2[i2] != scores2[i2 + 1]) {
                    rank2 += same2;
                    same2 = 1;
                } else {
                    same2 += 1;
                }
            }
            best2 = 9;
            for (i2 = 0; i2 < modeCtrl.playerCount; i2++) {
                if (ranks2[i2] == 0 && best2 > i2) {
                    modeCtrl.currPlayer = i2;
                    best2 = i2;
                }
            }
        }
        *(s16 *)(st + 0x3a) = *(s16 *)(st + 0x3a) - 1;
        lbl_00008C78();
        for (q = 0; q < modeCtrl.playerCount; q++) {
            ballInfo[q].pos = decodedStageLzPtr->startPos->pos;
            ballInfo[q].prevPos = decodedStageLzPtr->startPos->pos;
        }
    }

    for (q = 0; q < modeCtrl.playerCount; q++)
        g_poolInfo.playerPool.statusList[q] = 4;
    g_poolInfo.playerPool.statusList[modeCtrl.currPlayer] = 2;
}
#pragma force_active reset
