/*
 * mini_billiards.c -- REL module, structurally split for per-function
 * byte-matching (part 7 of 55; contiguous .text range).  Each function
 * below is an asm-include of its body in asm/nonmatchings/mini_billiards/.
 * To convert one to C, isolate it into its own pure-C file (see the
 * --isolate option of tools/rel_split.py) -- an asm sibling in the same
 * TU disables mwcc's optimizer for the C function.  Keep the Makefile
 * SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <dolphin.h>
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "pause_menu.h"
#include "pool.h"
#include "recplay.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "mot_ape.h"
#include "avdisp.h"
#include "vibration.h"
#include "ord_tbl.h"
#include "background.h"
#include "effect.h"
#include "nl2ngc.h"
#include "string.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/mini_billiards.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0001C2B8[];
extern u8 lbl_0001CAD8[];
extern u8 lbl_0001CBD0[];
extern u8 lbl_0001CC88[];
extern u8 lbl_0001CE18[];
extern u8 lbl_0001CF00[];
extern u8 lbl_0001CF50[];
extern u8 lbl_0001CFD0[];
extern u8 lbl_00020840[];
extern u8 lbl_00020848[];
extern u8 lbl_00020AF0[];
extern u8 lbl_00020B10[];
extern u8 lbl_00020B30[];
extern u8 lbl_00020B58[];
extern u8 lbl_00020B68[];
extern u8 lbl_00020B78[];
extern u8 lbl_00020C20[];
extern u8 lbl_00020C40[];
extern u8 lbl_00020CA0[];
extern u8 lbl_00020DA0[];
extern u8 lbl_00020E30[];
extern u8 lbl_00020E38[];
extern u8 lbl_00020E40[];
extern u8 lbl_00020EC0[];
extern u8 lbl_00020EE0[];
extern u8 lbl_00020F00[];
extern u8 lbl_00020F70[];
extern u8 lbl_00020FC0[];
extern u8 lbl_00021080[];
extern u8 lbl_000210A8[];
extern u8 lbl_00021204[];
extern u8 lbl_0002157C[];
extern u8 lbl_000215B0[];
extern u8 lbl_10000000[];
extern u8 lbl_10000002[];
extern u8 lbl_10000003[];
extern u8 lbl_10000004[];
extern u8 lbl_10000006[];
extern u8 lbl_10000008[];
extern u8 lbl_1000000A[];
extern u8 lbl_1000000B[];
extern u8 lbl_1000000C[];
extern u8 lbl_1000000D[];
extern u8 lbl_1000000E[];
extern u8 lbl_1000000F[];
extern u8 lbl_10000010[];
extern u8 lbl_10000011[];
extern u8 lbl_10000012[];
extern u8 lbl_10000013[];
extern u8 lbl_10000014[];
extern u8 lbl_10000015[];
extern u8 lbl_10000016[];
extern u8 lbl_10000017[];
extern u8 lbl_10000018[];
extern u8 lbl_1000001A[];
extern u8 lbl_1000001C[];
extern u8 lbl_1000001E[];
extern u8 lbl_1000001F[];
extern u8 lbl_10000020[];
extern u8 lbl_10000024[];
extern u8 lbl_10000028[];
extern u8 lbl_1000002C[];
extern u8 lbl_10000030[];
extern u8 lbl_10000034[];
extern u8 lbl_10000038[];
extern u8 lbl_1000003C[];
extern u8 lbl_10000048[];
extern u8 lbl_10000049[];
extern u8 lbl_1000004A[];
extern u8 lbl_1000004C[];
extern u8 lbl_1000004E[];
extern u8 lbl_10000050[];
extern u8 lbl_10000054[];
extern u8 lbl_10000058[];
extern u8 lbl_1000005C[];
extern u8 lbl_10000060[];
extern u8 lbl_10000061[];
extern u8 lbl_10000062[];
extern u8 lbl_10000064[];
extern u8 lbl_100000A4[];
extern u8 lbl_10000A64[];
extern u8 lbl_10000A70[];
extern u8 lbl_10009710[];
extern u8 lbl_10009878[];
extern u8 lbl_10009C88[];
extern u8 lbl_10009C8C[];
extern u8 lbl_10009CA0[];
extern u8 lbl_10009CBC[];
extern u8 lbl_1000A5BC[];
extern u8 lbl_1000AA38[];
extern u8 lbl_1000B340[];
extern u8 lbl_1000B360[];
extern u8 lbl_1000B361[];
extern u8 lbl_1000B390[];
extern u8 lbl_1000B418[];
extern u8 s_somethingLightRelated[];

// Imported functions the code calls that no included header declares.
extern void __cvt_fp2unsigned();
extern void func_8009C5E4();
extern void func_8009CAE0();
extern void func_8009CD5C();
extern void func_8009DB40();
extern void func_8009DB9C();
extern void func_8009DDC4();
extern void mini_commend_free_data();
extern void sqrt();
extern void u_load_minigame_graphics();
extern void window_printf_1();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_000001E0(void);
void lbl_00000614(void);
void lbl_00000754(void);
void lbl_00000800(void);
void lbl_00000E68(void);
void lbl_00000F34(void);
void lbl_00000F5C(void);
void lbl_000023B0(void);
void lbl_000025B0(void);
void lbl_00002B4C(void);
void lbl_00002C80(void);
void lbl_0000341C(void);
void lbl_0000367C(void);
void lbl_00003CC8(void);
void lbl_00003F4C(void);
void lbl_00004634(void);
void lbl_000055FC(void);
void lbl_00005654(void);
void lbl_000059A8(void);
void lbl_00005DD0(void);
void lbl_00006DC0(void);
void lbl_000077D8(void);
void lbl_00007974(void);
void lbl_00007C74(void);
void lbl_00007D80(void);
void lbl_00009540(void);
void lbl_00009788(void);
void lbl_00009E34(void);
void lbl_00009EC4(void);
void lbl_00009F0C(void);
void lbl_00009F3C(void);
void lbl_0000A054(void);
void lbl_0000C85C(void);
void lbl_0000D7E8(void);
void lbl_0000E8D0(void);
void lbl_00010FD0(void);
void lbl_000111B4(void);
void lbl_000115F4(void);
void lbl_00016D24(void);
void lbl_00016D9C(void);
void lbl_0001723C(void);
void lbl_00017408(void);
void lbl_00017A00(void);
void lbl_00018008(void);
void lbl_00018474(void);
f32 lbl_00018608(f64, f64, f64, f64, f64, f64);
void lbl_000186EC(void);
void lbl_000189B4(void);
void lbl_00018A98(void);
void lbl_00018C78(void);
void lbl_00018F4C(void);
void lbl_00019264(void);
void lbl_0001968C(void);
void lbl_00019F5C(void);
void lbl_00019FD4(void);
void lbl_0001A074(void);
void lbl_0001A0B0(void);
void lbl_0001A18C(void);
void lbl_0001B880(void);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
s8 lbl_0000D0A4(void);
s8 lbl_0000D330(void);
void lbl_00008EC0(int, int);
s8 lbl_0000939C(int);
extern u8 lbl_0001C2B8[4]; /* TYPED-TEST */
void lbl_00007D18(s16 arg0, s32 arg1);
struct Rec7D18 {
    s16 unk0;
    s16 unk2;
    s32 unk4;
    s32 unk8;
    s32 unkC;
};
struct Work7D18 {
    u8 pad[0xA5BC];
    struct Rec7D18 recs[64];
};

struct BB7974 {
    s8 state;            /* +0x00 */
    u8 filler1[0xF];
    f32 x;               /* +0x10 */
    f32 y;               /* +0x14 */
    f32 z;               /* +0x18 */
    u8 filler1C[0x38];
    f32 unk54;           /* +0x54 */
    f32 unk58;
    f32 unk5C;
    f32 unk60;
    u8 filler64[4];
};                       /* 0x68 */
struct BB800 {
    s32 w[0x1a];
};                       /* 0x68 */
struct BQ800 {
    u8 filler0[0x44];
    Quaternion q44;      /* +0x44 */
    Quaternion q54;      /* +0x54 */
    u8 filler64[4];
};                       /* 0x68 */
struct BilliardsPlayerA {
    s8 unk0;
    s8 chara;
    u8 filler2[4];
};
#pragma force_active on
/* lbl_00007974 slot -- run 19 draft a for lbl_00000800, decoded from a blank
   page.  Reachable TODAY: src/mini_billiards_7.c.o emits the SIGNED magic and
   the link map puts it at 0x1CBD0, the address this function loads.
   Byte-offset addressing style copied from the MATCHED sibling lbl_00005654.  */
void lbl_00000800(void)
{
    u8 *p = lbl_0001C2B8;
    u8 *b = lbl_10000000;
    int i;
    int j;
    int a;
    int e;
    f32 d;
    s8 retry;
    Vec axis;
    struct BB800 tmp;

    axis = *(Vec *)(p + 0x8c4);

    for (i = 0; i < 10; i++) {
        *(s8 *)&((u8 *)(b + 0x9878))[i * 0x68] = 1;
        *(f32 *)&((u8 *)(b + 0x9880))[i * 0x68] = *(f32 *)(p + 0x8b4);
        *(f32 *)&((u8 *)(b + 0x9884))[i * 0x68] = *(f32 *)(p + 0x8b4);
        *(s8 *)&((u8 *)(b + 0x987a))[i * 0x68] = 0;
        *(s8 *)&((u8 *)(b + 0x987c))[i * 0x68] = -1;
        *(s8 *)&((u8 *)(b + 0x987d))[i * 0x68] = -1;
        *(s8 *)&((u8 *)(b + 0x987e))[i * 0x68] = -1;
        *(s8 *)&((u8 *)(b + 0x987b))[i * 0x68] = 0;
        do {
            retry = 0;
            *(f32 *)&((u8 *)(b + 0x9888))[i * 0x68] =
                *(f32 *)(p + 0x8d0)
                    * (*(f32 *)(p + 0x8d4)
                       * ((f32)rand() / *(f32 *)(p + 0x8d8)))
                - *(f32 *)(p + 0x8dc) - *(f32 *)(p + 0x8c0);
            *(f32 *)&((u8 *)(b + 0x988c))[i * 0x68] = *(f32 *)(p + 0x8c0);
            *(f32 *)&((u8 *)(b + 0x9890))[i * 0x68] =
                *(f32 *)(p + 0x8d0)
                    * (*(f32 *)(p + 0x8e0)
                       * ((f32)rand() / *(f32 *)(p + 0x8d8)))
                - *(f32 *)(p + 0x8e4) - *(f32 *)(p + 0x8c0);
            for (j = 0; j < i; j++) {
                if (mathutil_sum_of_sq_2(
                        *(f32 *)&((u8 *)(b + 0x9888))[i * 0x68]
                            - *(f32 *)&((u8 *)(b + 0x9888))[j * 0x68],
                        *(f32 *)&((u8 *)(b + 0x9890))[i * 0x68]
                            - *(f32 *)&((u8 *)(b + 0x9890))[j * 0x68])
                    < *(f32 *)(p + 0x8b8)) {
                    retry = 1;
                    break;
                }
            }
        } while (retry == 1);
        *(f32 *)&((u8 *)(b + 0x9894))[i * 0x68] =
            *(f32 *)&((u8 *)(b + 0x9888))[i * 0x68];
        *(f32 *)&((u8 *)(b + 0x9898))[i * 0x68] =
            *(f32 *)&((u8 *)(b + 0x988c))[i * 0x68];
        *(f32 *)&((u8 *)(b + 0x989c))[i * 0x68] =
            *(f32 *)&((u8 *)(b + 0x9890))[i * 0x68];
        *(f32 *)&((u8 *)(b + 0x98ac))[i * 0x68] =
            *(f32 *)&((u8 *)(b + 0x98b0))[i * 0x68] =
                *(f32 *)&((u8 *)(b + 0x98b4))[i * 0x68] = *(f32 *)(p + 0x8b4);
        mathutil_quat_from_axis_angle(
            &((struct BQ800 *)(b + 0x9878))[i].q44, &axis, 0);
        mathutil_quat_from_axis_angle(
            &((struct BQ800 *)(b + 0x9878))[i].q54, &axis, 0);
    }

    *(f32 *)(b + 0x98ac) = *(f32 *)(p + 0x8e8);
    *(f32 *)(b + 0x98b4) = *(f32 *)(p + 0x8b4);
    mathutil_quat_from_axis_angle(&((struct BQ800 *)(b + 0x9878))[0].q54, &axis, 0);
    *(f32 *)(b + 0x9888) = *(f32 *)(p + 0x8ec);
    *(f32 *)(b + 0x9890) = *(f32 *)(p + 0x8b4);

    *(f32 *)(b + 0x98f0) =
        *(f64 *)(p + 0x8f0)
        + *(f32 *)(p + 0x8f8) * ((f32)rand() / *(f32 *)(p + 0x8d8))
        - *(f64 *)(p + 0x900);
    *(f32 *)(b + 0x98f8) =
        *(f32 *)(p + 0x8f8) * ((f32)rand() / *(f32 *)(p + 0x8d8))
        - *(f32 *)(p + 0x908);

    d = *(f32 *)(p + 0x90c)
        + *(f32 *)(p + 0x908) * ((f32)rand() / *(f32 *)(p + 0x8d8));

    *(f32 *)(b + 0x9b00) = *(f32 *)(b + 0x98f8) + *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x9af8) = *(f32 *)(b + 0x98f0) + *(f32 *)(p + 0x914) * d;
    *(f32 *)(b + 0x9a98) = *(f32 *)(b + 0x98f8) - *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x9a90) = *(f32 *)(b + 0x98f0) + *(f32 *)(p + 0x914) * d;
    *(f32 *)(b + 0x9a30) = *(f32 *)(b + 0x9b00) + *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x9a28) = *(f32 *)(b + 0x9af8) + *(f32 *)(p + 0x914) * d;
    *(f32 *)(b + 0x9c38) = *(f32 *)(b + 0x9b00) - *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x9c30) = *(f32 *)(b + 0x9af8) + *(f32 *)(p + 0x914) * d;
    *(f32 *)(b + 0x9960) = *(f32 *)(b + 0x9a98) - *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x9958) = *(f32 *)(b + 0x9a90) + *(f32 *)(p + 0x914) * d;
    *(f32 *)(b + 0x9bd0) = *(f32 *)(b + 0x9a30) - *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x9bc8) = *(f32 *)(b + 0x9a28) + *(f32 *)(p + 0x914) * d;
    *(f32 *)(b + 0x9b68) = *(f32 *)(b + 0x9c38) - *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x9b60) = *(f32 *)(b + 0x9c30) + *(f32 *)(p + 0x914) * d;
    *(f32 *)(b + 0x99c8) = *(f32 *)(b + 0x9bd0) - *(f32 *)(p + 0x910) * d;
    *(f32 *)(b + 0x99c0) = *(f32 *)(b + 0x9bc8) + *(f32 *)(p + 0x914) * d;

    for (j = 0; j < 10; j++) {
        *(f32 *)&((u8 *)(b + 0x9894))[j * 0x68] =
            *(f32 *)&((u8 *)(b + 0x9888))[j * 0x68]
            - *(f32 *)&((u8 *)(b + 0x98ac))[j * 0x68];
        *(f32 *)&((u8 *)(b + 0x9898))[j * 0x68] =
            *(f32 *)&((u8 *)(b + 0x988c))[j * 0x68]
            - *(f32 *)&((u8 *)(b + 0x98b0))[j * 0x68];
        *(f32 *)&((u8 *)(b + 0x989c))[j * 0x68] =
            *(f32 *)&((u8 *)(b + 0x9890))[j * 0x68]
            - *(f32 *)&((u8 *)(b + 0x98b4))[j * 0x68];
    }

    *(s32 *)(b + 0x28) = 0;
    *(s32 *)(b + 0x30) = 0;
    for (i = 0; i < 100; i++) {
        a = (rand() & 0x7fff) % 7 + 2;
        e = (rand() & 0x7fff) % 7 + 2;
        tmp = ((struct BB800 *)(b + 0x9878))[a];
        ((struct BB800 *)(b + 0x9878))[a] = ((struct BB800 *)(b + 0x9878))[e];
        ((struct BB800 *)(b + 0x9878))[e] = tmp;
    }
    *(s16 *)(b + 0x1a) = 0;
    *(s16 *)(b + 0x1c) = 0;
    *(s8 *)(b + 0x48) = 1;
    lbl_00000E68();
}
#pragma peephole on
void lbl_00000E68(void)
{
    if (((s8 *)lbl_10000000)[lbl_802F1C32 * 6 + 0xa66] != 0) {
        if ((s32) * (u8 *)(lbl_10000000 + 0xa) == 0x19) {
            *(struct ControllerInfo **)(lbl_10000000 + 0x9c88) =
                &controllerInfo[playerControllerIDs[1 - lbl_802F1C32]];
        } else {
            lbl_0001968C();
            *(struct ControllerInfo **)(lbl_10000000 + 0x9c88) =
                (struct ControllerInfo *)(lbl_10000000 + 0x9c8c);
        }
    } else {
        *(struct ControllerInfo **)(lbl_10000000 + 0x9c88) =
            &controllerInfo[playerControllerIDs[lbl_802F1C32]];
    }
}
void lbl_00000F34(void)
{
    lbl_00009F0C();
    lbl_00000F5C();
    lbl_00009F3C();
}
asm void lbl_00000F5C(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_billiards/lbl_00000F5C.s"
}
#pragma peephole on
asm void lbl_000023B0(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_billiards/lbl_000023B0.s"
}
#pragma peephole on
asm void lbl_000025B0(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_billiards/lbl_000025B0.s"
}
#pragma peephole on
void lbl_00002B4C(void)
{
    u8 *q = lbl_10000000;
    u8 *p = lbl_0001C2B8;
    int i;

    for (i = 0; i < 8; i++) {
        *(u8 *)(q + 0x9948 + i * 0x68) = 0;
        *(f32 *)(q + 0x9950 + i * 0x68) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x9954 + i * 0x68) = *(f32 *)(p + 0x8B4);
    }

    *(f32 *)(q + 0x9888) = *(f32 *)(p + 0x8EC);
    *(f32 *)(q + 0x9890) = *(f32 *)(p + 0x960);
    *(f32 *)(q + 0x98AC) = *(f32 *)(p + 0x8B8);
    *(f32 *)(q + 0x98B4) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x98F0) = *(f32 *)(p + 0x8EC);
    *(f32 *)(q + 0x98F8) = *(f32 *)(p + 0x964);
    *(f32 *)(q + 0x9914) = *(f32 *)(p + 0x8B8);
    *(f32 *)(q + 0x991C) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x38) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x3C) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x40) = *(f32 *)(p + 0x968);
    *(f32 *)(q + 0x44) = *(f32 *)(p + 0x968);
    *(u8 *)(q + 0x9879) = 0;
    *(u8 *)(q + 0x98E1) = 0;
    *(u8 *)(q + 0xC) = 3;
    *(u8 *)(q + 0xD) = 1;
}
asm void lbl_00002C80(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_billiards/lbl_00002C80.s"
}
#pragma peephole on
void lbl_0000341C(void)
{
    u8 *q = lbl_10000000;
    u8 *p = lbl_0001C2B8;
    f32 *w;
    u8 *in;
    u16 btn;
    f32 sc[6];
    f32 k1, hf;
    f32 sx, sy;

    mathutil_sin_cos_v(*(s16 *)(q + 0x4C) + *(s16 *)(q + 0x4E), sc);

    in = *(u8 **)(q + 0x9C88);
    btn = *(u16 *)in;

    k1 = *(f32 *)(p + 0x968);
    hf = *(f32 *)(p + 0x8C0);
    sx = hf * (hf * (k1 * (f32)*(s8 *)(in + 2)));
    sy = -(hf * (hf * (k1 * (f32)*(s8 *)(in + 3))));

    if (btn & 2)
        sx = *(f32 *)(p + 0x948);
    else if (btn & 1)
        sx = *(f32 *)(p + 0x9D8);

    if (btn & 4)
        sy = *(f32 *)(p + 0x948);
    else if (btn & 8)
        sy = *(f32 *)(p + 0x9D8);

    w = (f32 *)(q + 0x9894) - 1;
    *w += sy * sc[1] - sx * sc[0];
    if (*w > *(f32 *)(p + 0x95C))
        *w = *(f32 *)(p + 0x95C);
    else if (*w < *(f32 *)(p + 0x9DC))
        *w = *(f32 *)(p + 0x9DC);

    if (*(s8 *)(q + 0x10) == 0) {
        if (lbl_0000D330()) {
            *(s8 *)(q + 0x10) = 1;
            *(s32 *)(q + 0x20) = 0;
        }
    } else if (lbl_0000D0A4()) {
        *(s8 *)(q + 0x10) = 0;
        *(s32 *)(q + 0x20) = 0;
    }

    *(Vec *)(q + 0x9894) = *(Vec *)(q + 0x9888);

    *(f32 *)(q + 0x98BC) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x98C0) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x98C4) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x98C8) = *(f32 *)(p + 0x8B8);
    *(f32 *)(q + 0x98CC) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x98D0) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x98D4) = *(f32 *)(p + 0x8B4);
    *(f32 *)(q + 0x98D8) = *(f32 *)(p + 0x8B8);

    if ((**(u16 **)(q + 0x9C88) & 0x100) && *(s8 *)(q + 0xC) == 0 &&
        *(s32 *)(q + 0x20) > 0x1E) {
        *(s8 *)(q + 0xC) = 1;
        *(s32 *)(q + 0x20) = 0;
        *(s8 *)(q + 0xB) = *(s8 *)(q + 0xA);
        lbl_00003F4C();
        *(s8 *)(q + 0xA) = 0xE;
        *(s32 *)(q + 0x2C) = 0;
        lbl_802F1DFC = 0;
        u_somePlayerId = 0;
        u_play_sound_0(0x175);
    }
}
/* lbl_0000367C -- run 20 draft a.  Cloned from the MATCHED sibling
   lbl_0000341C in the same TU (same stick-read / btn-mask / D330-D0A4 shape).  */
void lbl_0000367C(void)
{
    u8 *q = lbl_10000000;
    u8 *p = lbl_0001C2B8;
    u8 *t = lbl_00020DA0;
    int i;
    int k;
    s8 flag;
    f32 e;
    Vec v;
    f32 sc[2];
    Vec d;

    if (__fabs(*(f32 *)(q + 0x988c) - *(f32 *)(p + 0x8c0)) < *(f64 *)(p + 0x9e0))
        *(Vec *)(t + 0x110) = *(Vec *)(q + 0x9888);

    mathutil_sin_cos_v(*(s16 *)(q + 0x4c) + *(s16 *)(q + 0x4e), sc);

    v.x = *(f32 *)(p + 0x8c0)
          * (*(f32 *)(p + 0x8c0)
             * (*(f32 *)(p + 0x968) * (f32)((s8 *)*(void **)(q + 0x9c88))[2]));
    v.y = *(f32 *)(p + 0x8b4);
    v.z = -(*(f32 *)(p + 0x8c0)
            * (*(f32 *)(p + 0x8c0)
               * (*(f32 *)(p + 0x968) * (f32)((s8 *)*(void **)(q + 0x9c88))[3])));

    if (**(u16 **)(q + 0x9c88) & 2)
        v.x = *(f32 *)(p + 0x948);
    else if (**(u16 **)(q + 0x9c88) & 1)
        v.x = *(f32 *)(p + 0x9d8);

    if (**(u16 **)(q + 0x9c88) & 4)
        v.z = *(f32 *)(p + 0x948);
    else if (**(u16 **)(q + 0x9c88) & 8)
        v.z = *(f32 *)(p + 0x9d8);

    if (mathutil_vec_sq_len(&v) < *(f32 *)(p + 0x944)) {
        v.x = *(f32 *)(t + 0x110) - *(f32 *)(q + 0x9888);
        v.z = *(f32 *)(t + 0x118) - *(f32 *)(q + 0x9890);
        e = v.x * v.x + v.z * v.z;
        if (e > *(f32 *)(p + 0x9e8)) {
            e = *(f32 *)(p + 0x9ec) * mathutil_rsqrt(e);
            v.x = v.x * e;
            v.z = v.z * e;
        }
        *(f32 *)(q + 0x9888) = *(f32 *)(q + 0x9888) + v.x;
        *(f32 *)(q + 0x9890) = *(f32 *)(q + 0x9890) + v.z;
    } else {
        *(f32 *)(q + 0x9888) =
            *(f32 *)(q + 0x9888) + (v.x * sc[1] + v.z * sc[0]);
        *(f32 *)(q + 0x9890) =
            *(f32 *)(q + 0x9890) + (v.z * sc[1] - v.x * sc[0]);
    }

    i = 0;
    do {
        flag = 0;
        d.x = *(f32 *)(q + 0x9888)
              - *(f32 *)&((u8 *)(q + 0x9888))[*(s8 *)(q + 0x49) * 0x68];
        d.y = *(f32 *)(p + 0x8b4);
        d.z = *(f32 *)(q + 0x9890)
              - *(f32 *)&((u8 *)(q + 0x9890))[*(s8 *)(q + 0x49) * 0x68];
        e = d.x * d.x + d.z * d.z;
        if (e < *(f32 *)(p + 0x9f0)) {
            e = *(f32 *)(p + 0x9f4) * mathutil_rsqrt(e);
            flag = 1;
            *(f32 *)(q + 0x9888) =
                *(f32 *)&((u8 *)(q + 0x9888))[*(s8 *)(q + 0x49) * 0x68]
                + d.x * e;
            *(f32 *)(q + 0x9890) =
                *(f32 *)&((u8 *)(q + 0x9890))[*(s8 *)(q + 0x49) * 0x68]
                + d.z * e;
        }
        if (*(f32 *)(q + 0x9890) > *(f32 *)(p + 0x95c)) {
            *(f32 *)(q + 0x9890) = *(f32 *)(p + 0x95c);
            flag |= 2;
        } else if (*(f32 *)(q + 0x9890) < *(f32 *)(p + 0x9dc)) {
            flag |= 2;
            *(f32 *)(q + 0x9890) = *(f32 *)(p + 0x9dc);
        }
        if (*(f32 *)(q + 0x9888) > *(f32 *)(p + 0x9f8)) {
            *(f32 *)(q + 0x9888) = *(f32 *)(p + 0x9f8);
            flag |= 2;
        } else if (*(f32 *)(q + 0x9888) < *(f32 *)(p + 0x9fc)) {
            flag |= 2;
            *(f32 *)(q + 0x9888) = *(f32 *)(p + 0x9fc);
        }
        i++;
    } while (flag >= 2 && i <= 1000);

    if (i > 1000)
        *(Vec *)(q + 0x9888) = *(Vec *)(t + 0x110);

    *(f32 *)(q + 0x988c) = *(f32 *)(p + 0x8c0);
    for (k = *(s8 *)(q + 0x49) + 1; k < 10; k++) {
        if (*(s8 *)&((u8 *)(q + 0x9878))[k * 0x68] == 1) {
            d.x = *(f32 *)(q + 0x9888)
                  - *(f32 *)&((u8 *)(q + 0x9888))[k * 0x68];
            d.y = *(f32 *)(q + 0x988c)
                  - *(f32 *)&((u8 *)(q + 0x988c))[k * 0x68];
            d.z = *(f32 *)(q + 0x9890)
                  - *(f32 *)&((u8 *)(q + 0x9890))[k * 0x68];
            if (d.x * d.x + d.y * d.y + d.z * d.z < *(f32 *)(p + 0x9f0))
                *(f32 *)(q + 0x988c) =
                    *(f32 *)(p + 0x8c0)
                    + mathutil_sqrt(*(f32 *)(p + 0x9f0) - d.x * d.x
                                    - d.z * d.z);
        }
    }

    *(f32 *)(q + 0x98ac) =
        *(f32 *)&((u8 *)(q + 0x9888))[*(s8 *)(q + 0x49) * 0x68]
        - *(f32 *)(q + 0x9888);
    *(f32 *)(q + 0x98b4) =
        *(f32 *)&((u8 *)(q + 0x9890))[*(s8 *)(q + 0x49) * 0x68]
        - *(f32 *)(q + 0x9890);
    mathutil_vec_normalize_len((Vec *)&((u8 *)(q + 0x9878))[0x34]);
    *(f32 *)(q + 0x98ac) = *(f32 *)(q + 0x98ac) * *(f32 *)(p + 0x8e8);
    *(f32 *)(q + 0x98b4) = *(f32 *)(q + 0x98b4) * *(f32 *)(p + 0x8e8);

    if (*(s8 *)(q + 0x10) == 1) {
        if (lbl_0000D330()) {
            *(s8 *)(q + 0x10) = 0;
            *(s32 *)(q + 0x20) = 0;
        }
    } else if (lbl_0000D0A4()) {
        *(s8 *)(q + 0x10) = 1;
        *(s32 *)(q + 0x20) = 0;
    }

    *(Vec *)(q + 0x9894) = *(Vec *)(q + 0x9888);
    *(f32 *)(q + 0x98bc) = *(f32 *)(p + 0x8b4);
    *(f32 *)(q + 0x98c0) = *(f32 *)(p + 0x8b4);
    *(f32 *)(q + 0x98c4) = *(f32 *)(p + 0x8b4);
    *(f32 *)(q + 0x98c8) = *(f32 *)(p + 0x8b8);
    *(f32 *)(q + 0x98cc) = *(f32 *)(p + 0x8b4);
    *(f32 *)(q + 0x98d0) = *(f32 *)(p + 0x8b4);
    *(f32 *)(q + 0x98d4) = *(f32 *)(p + 0x8b4);
    *(f32 *)(q + 0x98d8) = *(f32 *)(p + 0x8b8);

    if ((**(u16 **)(q + 0x9c88) & 0x100) && *(s8 *)(q + 0xc) == 0) {
        lbl_802F1DFC = ((struct BilliardsPlayerA *)(q + 0xa64))[lbl_802F1C32].chara;
        u_somePlayerId = lbl_802F1C32;
        u_play_sound_0(0x1e);
        *(Vec *)(q + 0x9888) = *(Vec *)(t + 0x110);
        *(s8 *)(q + 0xc) = 1;
        *(s32 *)(q + 0x20) = 0;
        *(s8 *)(q + 0xb) = *(s8 *)(q + 0xa);
        lbl_00003F4C();
        *(s8 *)(q + 0xa) = 0xe;
        *(s32 *)(q + 0x2c) = 0;
    }
}
#pragma peephole on
struct BilliardsPlayer
{
    s8 unk0;
    s8 chara;
    u8 filler2[4];
};

struct BilliardsApe
{
    u8 filler0[0x64];
    struct Ape *ape;
};

void lbl_00003CC8(void)
{
    u8 *q = lbl_10000000;
    int i;
    int k;
    int id;
    int cnt[4];

    for (i = 15; i >= 0; i--) {
        if (((int *)(q + 0x64))[i] != -1) {
            thread_kill(((int *)(q + 0x64))[i]);
            ((int *)(q + 0x64))[i] = -1;
        }
    }
    if (*(s8 *)(q + 0xA) != 8 && *(s8 *)(q + 0xA) != 9 && *(s8 *)(q + 0xA) != 0xA) {
        cnt[3] = 0;
        cnt[2] = 0;
        cnt[1] = 0;
        cnt[0] = 0;
        k = 0;
        for (i = 0; i < 9; i++) {
            if ((u32)i <= 1 && *(s8 *)(q + 0xA) == 7) {
                id = ((struct BilliardsPlayer *)(q + 0xA64))[i].chara;
            } else if (i == 0 || i == 9) {
                id = ((struct BilliardsPlayer *)(q + 0xA64))[lbl_802F1C32].chara;
            } else {
                int a = ((struct BilliardsPlayer *)(q + 0xA64))[lbl_802F1C32].chara;
                int b =
                    ((struct BilliardsPlayer *)(q + 0xA64))[1 - lbl_802F1C32].chara;
                do {
                    k = (k + 1) & 3;
                    cnt[k]++;
                } while (k == a || k == b);
                id = k;
            }
            ((struct BilliardsApe *)(q + 0x9878))[i].ape = u_make_ape(id);
            u_start_indexed_anim(((struct BilliardsApe *)(q + 0x9878))[i].ape, 1, 0);
            ((struct BilliardsApe *)(q + 0x9878))[i].ape->ballId = i;
            if ((u32)i <= 1 && *(s8 *)(q + 0xA) == 7)
                ((struct BilliardsApe *)(q + 0x9878))[i].ape->colorId = i;
            else if (i == 0)
                ((struct BilliardsApe *)(q + 0x9878))[i].ape->colorId = lbl_802F1C32;
            else
                ((struct BilliardsApe *)(q + 0x9878))[i].ape->colorId = cnt[id] - 1;
            ((int *)(q + 0x64))[i] = thread_create(
                (ThreadCallback)lbl_00019264,
                ((struct BilliardsApe *)(q + 0x9878))[i].ape, THREAD_GROUP_5);
        }
    } else {
        for (i = 0; i < 2; i++) {
            id = ((struct BilliardsPlayer *)(q + 0xA64))[i].chara;
            ((struct BilliardsApe *)(q + 0x9878))[i].ape =
                u_make_ape(id);
            u_start_indexed_anim(((struct BilliardsApe *)(q + 0x9878))[i].ape, 1, 0);
            ((struct BilliardsApe *)(q + 0x9878))[i].ape->ballId = i;
            ((struct BilliardsApe *)(q + 0x9878))[i].ape->colorId = i;
            ((int *)(q + 0x64))[i] = thread_create(
                (ThreadCallback)lbl_00019264,
                ((struct BilliardsApe *)(q + 0x9878))[i].ape, THREAD_GROUP_5);
        }
    }
    *(u8 *)(q + 0x1F) = 1;
}
/* lbl_00003F4C -- run 20 draft a.  Same TU, same idioms as the MATCHED
   lbl_00002B4C (unrolled 3-store loop), lbl_00000800 (sum_of_sq_2 collision
   test) and this run's lbl_0000367C (normalize_len argument spelling).  */
void lbl_00003F4C(void)
{
    u8 *q = lbl_10000000;
    u8 *p = lbl_0001C2B8;
    u8 *t = lbl_00020DA0;
    int j;
    int i;
    int n;
    s8 flag;
    f32 e;
    f32 hx;
    f32 hz;
    Vec d;

    if (dipSwitches & 1)
        u_clear_buffers_2_and_5();
    lbl_00003CC8();

    for (i = 0; i < 10; i++) {
        *(f32 *)&((u8 *)(q + 0x9880))[i * 0x68] = *(f32 *)(p + 0x8b4);
        *(f32 *)&((u8 *)(q + 0x9884))[i * 0x68] = *(f32 *)(p + 0x8b4);
        *(s8 *)&((u8 *)(q + 0x987b))[i * 0x68] = 0;
    }
    lbl_00009788();

    if (*(s8 *)(q + 0x9878) != 1) {
        *(s8 *)(q + 0x9878) = 1;
        do {
            *(f32 *)(q + 0x9888) =
                *(f32 *)(p + 0x8d0)
                    * (*(f32 *)(p + 0x8d4)
                       * ((f32)rand() / *(f32 *)(p + 0x8d8)))
                - *(f32 *)(p + 0x8dc) - *(f32 *)(p + 0x8c0);
            *(f32 *)(q + 0x9890) =
                *(f32 *)(p + 0x8d0)
                    * (*(f32 *)(p + 0x8e0)
                       * ((f32)rand() / *(f32 *)(p + 0x8d8)))
                - *(f32 *)(p + 0x8e4) - *(f32 *)(p + 0x8c0);
            for (j = 1; j < 10; j++) {
                if (*(s8 *)&((u8 *)(q + 0x9878))[j * 0x68] == 1) {
                    if (mathutil_sum_of_sq_2(
                            *(f32 *)(q + 0x9888)
                                - *(f32 *)&((u8 *)(q + 0x9888))[j * 0x68],
                            *(f32 *)(q + 0x9890)
                                - *(f32 *)&((u8 *)(q + 0x9890))[j * 0x68])
                        < *(f32 *)(p + 0x8b8))
                        break;
                }
            }
        } while (j < 10);
    }

    n = 0;
    do {
        flag = 0;
        for (i = 0; i < 9; i++) {
            if (*(s8 *)&((u8 *)(q + 0x9878))[i * 0x68] != 1)
                continue;
            for (j = i + 1; j < 10; j++) {
                if (*(s8 *)&((u8 *)(q + 0x9878))[j * 0x68] != 1)
                    continue;
                d.x = *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68]
                      - *(f32 *)&((u8 *)(q + 0x9888))[j * 0x68];
                d.y = *(f32 *)(p + 0x8b4);
                d.z = *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68]
                      - *(f32 *)&((u8 *)(q + 0x9890))[j * 0x68];
                e = d.x * d.x + d.z * d.z;
                if (e < *(f32 *)(p + 0xa00)) {
                    e = *(f32 *)(p + 0xa04) * mathutil_rsqrt(e);
                    flag |= 1;
                    hx = *(f32 *)(p + 0x8c0)
                         * (*(f32 *)&((u8 *)(q + 0x9888))[j * 0x68]
                            + *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68]);
                    hz = *(f32 *)(p + 0x8c0)
                         * (*(f32 *)&((u8 *)(q + 0x9890))[j * 0x68]
                            + *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68]);
                    *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68] = hx + d.x * e;
                    *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68] = hz + d.z * e;
                    *(f32 *)&((u8 *)(q + 0x9888))[j * 0x68] = hx - d.x * e;
                    *(f32 *)&((u8 *)(q + 0x9890))[j * 0x68] = hz - d.z * e;

                    if (*(f32 *)&((u8 *)(q + 0x9890))[i * 0x68]
                        > *(f32 *)(p + 0x95c)) {
                        *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68] =
                            *(f32 *)(p + 0x95c);
                        flag |= 2;
                    } else if (*(f32 *)&((u8 *)(q + 0x9890))[i * 0x68]
                               < *(f32 *)(p + 0x9dc)) {
                        flag |= 2;
                        *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68] =
                            *(f32 *)(p + 0x9dc);
                    }
                    if (*(f32 *)&((u8 *)(q + 0x9888))[i * 0x68]
                        > *(f32 *)(p + 0x9f8)) {
                        *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68] =
                            *(f32 *)(p + 0x9f8);
                        flag |= 2;
                    } else if (*(f32 *)&((u8 *)(q + 0x9888))[i * 0x68]
                               < *(f32 *)(p + 0x9fc)) {
                        flag |= 2;
                        *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68] =
                            *(f32 *)(p + 0x9fc);
                    }
                    if (*(f32 *)&((u8 *)(q + 0x9890))[j * 0x68]
                        > *(f32 *)(p + 0x95c)) {
                        *(f32 *)&((u8 *)(q + 0x9890))[j * 0x68] =
                            *(f32 *)(p + 0x95c);
                        flag |= 2;
                    } else if (*(f32 *)&((u8 *)(q + 0x9890))[j * 0x68]
                               < *(f32 *)(p + 0x9dc)) {
                        flag |= 2;
                        *(f32 *)&((u8 *)(q + 0x9890))[j * 0x68] =
                            *(f32 *)(p + 0x9dc);
                    }
                    if (*(f32 *)&((u8 *)(q + 0x9888))[j * 0x68]
                        > *(f32 *)(p + 0x9f8)) {
                        *(f32 *)&((u8 *)(q + 0x9888))[j * 0x68] =
                            *(f32 *)(p + 0x9f8);
                        flag |= 2;
                    } else if (*(f32 *)&((u8 *)(q + 0x9888))[j * 0x68]
                               < *(f32 *)(p + 0x9fc)) {
                        flag |= 2;
                        *(f32 *)&((u8 *)(q + 0x9888))[j * 0x68] =
                            *(f32 *)(p + 0x9fc);
                    }
                }
            }
        }
        n++;
    } while (flag >= 1 && n <= 1000);

    for (j = 1; j < 10; j++) {
        if (*(s8 *)&((u8 *)(q + 0x9878))[j * 0x68] == 1)
            break;
        *(s8 *)&((u8 *)(q + 0x9878))[j * 0x68] = 0;
    }

    if (j == 10) {
        *(s8 *)(q + 0x49) = 0;
        lbl_00000800();
        lbl_00003F4C();
    } else {
        *(s8 *)(q + 0x49) = (s8)j;
        *(f32 *)(q + 0x98ac) =
            *(f32 *)&((u8 *)(q + 0x9888))[j * 0x68] - *(f32 *)(q + 0x9888);
        *(f32 *)(q + 0x98b4) =
            *(f32 *)&((u8 *)(q + 0x9890))[j * 0x68] - *(f32 *)(q + 0x9890);
        mathutil_vec_normalize_len((Vec *)&((u8 *)(q + 0x9878))[0x34]);
        *(f32 *)(q + 0x98ac) = *(f32 *)(q + 0x98ac) * *(f32 *)(p + 0x8e8);
        *(f32 *)(q + 0x98b4) = *(f32 *)(q + 0x98b4) * *(f32 *)(p + 0x8e8);

        *(f32 *)&((u8 *)(q + 0x9880))[*(s8 *)(q + 0x49) * 0x68] =
            *(f32 *)(p + 0x8b8);
        *(f32 *)&((u8 *)(q + 0x9884))[*(s8 *)(q + 0x49) * 0x68] =
            *(f32 *)(p + 0x8b4);

        *(Vec *)(q + 0x9ca0) = *(Vec *)(q + 0x9888);
        *(Vec *)(q + 0x9cac) = *(Vec *)(q + 0x9888);

        *(f32 *)(q + 0x38) = *(f32 *)(p + 0x8b4);
        *(f32 *)(q + 0x40) = *(f32 *)(p + 0xa08);
        *(f32 *)(q + 0x58) = *(f32 *)(q + 0x5c) = *(f32 *)(p + 0x8b4);

        *(f32 *)(t + 0x0) = *(f32 *)(q + 0x9888);
        *(f32 *)(t + 0x4) = *(f32 *)(p + 0x8b8) + *(f32 *)(q + 0x988c);
        *(f32 *)(t + 0x8) = *(f32 *)(q + 0x9890);

        *(s16 *)(q + 0x4c) = mathutil_atan2(-*(f32 *)(q + 0x98ac),
                                            -*(f32 *)(q + 0x98b4));
        *(s16 *)(q + 0x4e) = 0;
        *(s16 *)(q + 0x4a) = -2048;
        *(f32 *)(q + 0x50) = *(f32 *)(p + 0x9c8);
        lbl_00007C74();
    }
}
#pragma peephole on
asm void lbl_00004634(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_billiards/lbl_00004634.s"
}
#pragma peephole on
struct W55FC {
    u8 _0[0xa];
    s8 fA;      /* 0xa */
    s8 fB;      /* 0xb */
    u8 _c[0x20 - 0xc];
    s32 f20;    /* 0x20 */
    u8 _24[0x2c - 0x24];
    s32 f2C;    /* 0x2c */
};

void lbl_000055FC(void)
{
    struct W55FC *w = (struct W55FC *)lbl_10000000;
    lbl_00000800();
    w->f20 = 0;
    w->fB = w->fA;
    lbl_00003F4C();
    w->fA = 0xe;
    w->f2C = 0;
}
struct BilliardsPlayerB
{
    s8 unk0;
    s8 chara;
    s8 unk2;
    u8 filler3;
    s16 unk4;
};

struct BilliardsApeB
{
    s8 unk0;
    u8 filler1[0x67];
};

void lbl_00005654(void)
{
    u8 *q = lbl_10000000;
    u8 *p = lbl_0001C2B8;
    struct BilliardsApeB *w = &((struct BilliardsApeB *)(q + 0x9878))[9];
    int i;
    int c;

    if (((struct BilliardsApeB *)(q + 0x9878))[9].unk0 != 1) {
        if (*(s32 *)(q + 0x20) == 0x1E) {
            *(s8 *)(q + 0x13) = 0x1E;
        } else if (*(s32 *)(q + 0x20) == 0x32) {
            start_screen_fade(0x101, 0xFFFFFF, 0xA);
        }
    }
    if (*(s32 *)(q + 0x20) > 0x3C) {
        lbl_00007C74();
        *(s8 *)(q + 0xB) = *(s8 *)(q + 0xA);
        *(s32 *)(q + 0x20) = 0;
        *(s8 *)(q + 0x14) = 0;
        *(s8 *)(q + 0x15) = 0;
        if (w->unk0 != 1) {
            start_screen_fade(0x100, 0xFFFFFF, 4);
            *(s8 *)(q + 0x10) = 0;
            *(s8 *)(q + 0xA) = 0x16;
            if (*(s16 *)(q + 0x1A) == 0) {
                *(s8 *)(q + 0x12) = 1;
                for (i = 1; i < 10; i++) {
                    if (((struct BilliardsApeB *)(q + 0x9878))[i].unk0 == 1) {
                        *(s8 *)(q + 0x12) = 0;
                        break;
                    }
                }
            } else {
                *(s8 *)(q + 0x12) = 0;
            }
            if (*(s16 *)(q + 0x1C) == 1) {
                lbl_00008EC0(0, 1);
                lbl_802F1DFC = 0;
                u_somePlayerId = 0;
                u_play_sound_0(0x174);
            } else if (*(s8 *)(q + 0x12) != 0) {
                lbl_00008EC0(1, 1);
                lbl_802F1DFC = 0;
                u_somePlayerId = 0;
                u_play_sound_0(0x48);
            }
            if (((struct BilliardsPlayerB *)(q + 0xA64))[lbl_802F1C32].unk2 != 0)
                func_8002BFCC(0x152, 0x153);
            else
                func_8002BFCC(0x156, 0x157);
            u_play_music(0, 8);
            cameraInfo[0].eye.x = *(f32 *)(p + 0x8B4);
            cameraInfo[0].eye.y = *(f32 *)(p + 0xA58);
            cameraInfo[0].eye.z = *(f32 *)(p + 0xA70);
            lbl_0001723C();
            *(s8 *)(q + 2) = 0;
            ((struct BilliardsPlayerB *)(q + 0xA64))[lbl_802F1C32].unk4 += 1;
            lbl_00008EC0(0xD, 1);
        } else {
            if (*(s8 *)(q + 0xF) == 0) {
                lbl_00008EC0(3, 1);
                lbl_802F1C32 = 1 - lbl_802F1C32;
                *(s16 *)(q + 0x1A) += 1;
                c = lbl_802F1C32;
                lbl_802F1DFC = ((struct BilliardsPlayerB *)(q + 0xA64))[c].chara;
                u_somePlayerId = c;
                u_play_sound_0(0x1E);
            }
            lbl_00003F4C();
            *(s8 *)(q + 0xA) = 0xE;
            *(s32 *)(q + 0x2C) = 0;
        }
    }
}

void lbl_000059A8(void)
{
    u8 *q = lbl_10000000;
    u8 *p = lbl_0001C2B8;
    int i;

    (*(struct Ape **)(q + 0x98DC))->flags |= 0x200000;
    if ((s8)*(u8 *)(q + 0x9878) != 1 && *(f32 *)(q + 0x988C) < *(f32 *)(p + 0xA78)) {
        *(f32 *)(q + 0x988C) =
            *(f32 *)(p + 0x948) + *(f32 *)(p + 0xA40) * *(f32 *)(q + 0x988C);
        *(s8 *)(q + 0x9878) = -2;
    }
    if (*(s32 *)(q + 0x20) <= 0x78)
        return;
    if ((s8)*(u8 *)(q + 0x9C20) != 1) {
        *(s8 *)(q + 0x9C20) = 1;
        *(f32 *)(q + 0x9C30) = *(f32 *)(p + 0xA7C);
        *(f32 *)(q + 0x9C34) = *(f32 *)(p + 0x8C0);
        *(f32 *)(q + 0x9C38) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x9C54) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x9C58) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x9C5C) = *(f32 *)(p + 0x8B4);
        do {
            for (i = 0; i < 9; i++) {
                if ((s8)*(u8 *)&((u8 *)(q + 0x9878))[i * 0x68] == 1 &&
                    mathutil_sum_of_sq_2(*(f32 *)&((u8 *)(q + 0x9888))[i * 0x68] - *(f32 *)(q + 0x9C30),
                                         *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68] - *(f32 *)(q + 0x9C38)) <
                        *(f32 *)(p + 0x9F0)) {
                    *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68] -= *(f32 *)(p + 0x8C0);
                    break;
                }
            }
        } while (i < 9);
    }
    for (i = 1; i < 10; i++) {
        if ((s8)*(u8 *)&((u8 *)(q + 0x9878))[i * 0x68] == 1) {
            *(s8 *)(q + 0x49) = i;
            break;
        }
    }
    for (i = 0; i < 10; i++) {
        *(Vec *)&((u8 *)(q + 0x9894))[i * 0x68] = *(Vec *)&((u8 *)(q + 0x9888))[i * 0x68];
        *(f32 *)&((u8 *)(q + 0x98BC))[i * 0x68] = *(f32 *)(p + 0x8B4);
        *(f32 *)&((u8 *)(q + 0x98C0))[i * 0x68] = *(f32 *)(p + 0x8B4);
        *(f32 *)&((u8 *)(q + 0x98C4))[i * 0x68] = *(f32 *)(p + 0x8B4);
        *(f32 *)&((u8 *)(q + 0x98C8))[i * 0x68] = *(f32 *)(p + 0x8B8);
        *(f32 *)&((u8 *)(q + 0x98CC))[i * 0x68] = *(f32 *)(p + 0x8B4);
        *(f32 *)&((u8 *)(q + 0x98D0))[i * 0x68] = *(f32 *)(p + 0x8B4);
        *(f32 *)&((u8 *)(q + 0x98D4))[i * 0x68] = *(f32 *)(p + 0x8B4);
        *(f32 *)&((u8 *)(q + 0x98D8))[i * 0x68] = *(f32 *)(p + 0x8B8);
        *(s8 *)&((u8 *)(q + 0x987B))[i * 0x68] = 0;
    }
    *(s8 *)(q + 0x10) = 0;
    lbl_802F1C32 = 1 - lbl_802F1C32;
    *(s16 *)(q + 0x1A) += 1;
    lbl_802F1DFC = 0;
    u_somePlayerId = 0;
    u_play_sound_0(0x17B);
    *(f32 *)(q + 0x50) = *(f32 *)(p + 0x9C8);
    *(s8 *)(q + 0xB) = *(s8 *)(q + 0xA);
    *(s32 *)(q + 0x20) = 0;
    *(s8 *)(q + 0xA) = 0xD;
    lbl_0001B880();
    lbl_00003CC8();
    u_play_music(0x64, 8);
}
struct BPart5DD0 {
    s8 active;
    u8 filler1[3];
    Vec pos;
    Vec vel;
    s16 u1c;
    s16 u1e;
    s16 u20;
    s16 u22;
};
struct BApe5DD0 {
    s8 state;
    u8 filler1[0x63];
    struct Ape *ape;
};
/* lbl_00005DD0 -- run 20 draft a.  Confetti/particle update.  Byte-offset
   addressing style copied from the MATCHED siblings lbl_00000800 and this
   run's lbl_0000367C and lbl_00003F4C.  */
void lbl_00005DD0(void)
{
    u8 *q = lbl_10000000;
    u8 *p = lbl_0001C2B8;
    int m3;
    s8 c;
    int n;
    int m;
    s8 st;
    s8 ok;
    s8 w8;
    int w;
    int i;
    int k;
    f32 e;
    f32 s;
    Vec v;
    f32 ek;

    st = 0;
    ((struct BApe5DD0 *)(q + 0x9878))[0].ape->flags |= 0x80000;
    for (i = 1; i < 9; i++) {
        if (((struct BApe5DD0 *)(q + 0x9878))[i].state == 1)
            ((struct BApe5DD0 *)(q + 0x9878))[i].ape->flags |= 0x80000;
    }

    if (*(s8 *)(q + 0x9c20) != 0) {
        *(f32 *)(q + 0x9c34) =
            *(f32 *)(q + 0x9c34) + *(f32 *)(q + 0x9c58);
        *(f32 *)(q + 0x9c58) = *(f32 *)(q + 0x9c58) - *(f32 *)(p + 0xa80);
        if (*(f32 *)(q + 0x9c58) < *(f32 *)(p + 0x8b4)) {
            ok = 1;
            for (i = 2; i < 9; i++) {
                if (*(s8 *)&((u8 *)(q + 0x9878))[i * 0x68] == 1) {
                    ok = 0;
                    break;
                }
            }
            if (*(s8 *)&((u8 *)(q + 0x9878))[1 * 0x68] != 1)
                ok = 0;
            *(s8 *)(q + 0x9c20) = 0;
            for (n = 0; n < 0x40; n++) {
                if (ok != 0) {
                    *(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] = 1;
                    *(Vec *)&((u8 *)(q + 0x9cc0))[n * 0x24] =
                        *(Vec *)(q + 0x9c30);
                    mathutil_mtxA_from_identity();
                    switch ((rand() & 0x7fff) % 5) {
                    case 0:
                        mathutil_mtxA_rotate_z_sin_cos(*(f32 *)(p + 0xa84),
                                                       *(f32 *)(p + 0xa88));
                        break;
                    case 1:
                        mathutil_mtxA_rotate_z_sin_cos(*(f32 *)(p + 0xa8c),
                                                       *(f32 *)(p + 0xa90));
                        break;
                    case 2:
                        mathutil_mtxA_rotate_z_sin_cos(*(f32 *)(p + 0x8b4),
                                                       *(f32 *)(p + 0xa18));
                        break;
                    case 3:
                        mathutil_mtxA_rotate_z_sin_cos(*(f32 *)(p + 0xa94),
                                                       *(f32 *)(p + 0xa90));
                        break;
                    default:
                        mathutil_mtxA_rotate_z_sin_cos(*(f32 *)(p + 0xa98),
                                                       *(f32 *)(p + 0xa88));
                        break;
                    }
                    mathutil_mtxA_translate_xyz(*(f32 *)(p + 0xa9c),
                                                *(f32 *)(p + 0x8b4),
                                                *(f32 *)(p + 0x8b4));
                    *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24] =
                        *(f32 *)(p + 0x8b4);
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] =
                        *(f32 *)(p + 0xaa0)
                        * ((f32)rand() / *(f32 *)(p + 0x8d8)
                           - *(f32 *)(p + 0x8c0));
                    *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24] =
                        *(f32 *)(p + 0x8b4);
                    mathutil_mtxA_tf_point(
                        &((struct BPart5DD0 *)(q + 0x9cbc))[n].vel,
                        &((struct BPart5DD0 *)(q + 0x9cbc))[n].vel);
                } else if (*(s8 *)(q + 0x12) != 0) {
                    *(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] = 1;
                    *(Vec *)&((u8 *)(q + 0x9cc0))[n * 0x24] =
                        *(Vec *)(q + 0x9c30);
                    *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24] =
                        (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] =
                        (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                    *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24] =
                        *(f32 *)(p + 0x8b4);
                    mathutil_vec_normalize_len(
                        &((struct BPart5DD0 *)(q + 0x9cbc))[n].vel);
                    *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24] *= *(f32 *)(p + 0xaa4);
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] *= *(f32 *)(p + 0xaa4);
                    *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24] *= *(f32 *)(p + 0xaa4);
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] =
                        *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24]
                        - *(f64 *)(p + 0xaa8)
                              * (*(f64 *)(p + 0x998)
                                 - __fabs(*(f32 *)&((u8 *)(q
                                                           + 0x9ccc))[n * 0x24]));
                } else if (*(s16 *)(q + 0x1c) == 1) {
                    *(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] = 1;
                    *(Vec *)&((u8 *)(q + 0x9cc0))[n * 0x24] =
                        *(Vec *)(q + 0x9c30);
                    *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24] =
                        (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] =
                        (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                    *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24] =
                        *(f32 *)(p + 0x8b4);
                    mathutil_vec_normalize_len(
                        &((struct BPart5DD0 *)(q + 0x9cbc))[n].vel);
                    *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24] *= *(f32 *)(p + 0xab0);
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] *= *(f32 *)(p + 0xab0);
                    *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24] *= *(f32 *)(p + 0xab0);
                } else {
                    w = 0;
                    if (((struct BilliardsPlayerB *)(q + 0xa64))[0].unk4
                            < *(s8 *)(q + 0x11) / 2 + 1
                        && ((struct BilliardsPlayerB *)(q + 0xa64))[1].unk4
                               < *(s8 *)(q + 0x11) / 2 + 1)
                        w = 1;
                    w8 = w;
                    if (w8 != 0 && n > 9) {
                        *(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] = 0;
                        continue;
                    }
                    *(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] = 1;
                    *(Vec *)&((u8 *)(q + 0x9cc0))[n * 0x24] =
                        *(Vec *)(q + 0x9c30);
                    *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24] =
                        (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] =
                        (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                    *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24] =
                        (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                    mathutil_vec_normalize_len(
                        &((struct BPart5DD0 *)(q + 0x9cbc))[n].vel);
                    if (w8 != 0)
                        e = *(f32 *)(p + 0xa3c);
                    else
                        e = *(f32 *)(p + 0xab0);
                    *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24] *= e;
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] *= e;
                    *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24] *= e;
                }
                *(s16 *)&((u8 *)(q + 0x9cd8))[n * 0x24] = rand() & 0x7fff;
                *(s16 *)&((u8 *)(q + 0x9cda))[n * 0x24] = rand() & 0x7fff;
                *(s16 *)&((u8 *)(q + 0x9cdc))[n * 0x24] =
                    (rand() & 0x7ff) + 0x800;
                *(s16 *)&((u8 *)(q + 0x9cde))[n * 0x24] =
                    (rand() & 0x7ff) + 0x800;
                if (rand() & 1)
                    *(s16 *)&((u8 *)(q + 0x9cdc))[n * 0x24] =
                        -*(s16 *)&((u8 *)(q + 0x9cdc))[n * 0x24];
                if (rand() & 1)
                    *(s16 *)&((u8 *)(q + 0x9cde))[n * 0x24] =
                        -*(s16 *)&((u8 *)(q + 0x9cde))[n * 0x24];
            }
            lbl_802F1DFC = 0;
            u_somePlayerId = 0;
            u_play_sound_0(0x14d);
            *(s32 *)(q + 0x20) = 0;
        } else {
            for (n = 0; n < 0x40; n++)
                *(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] = 0;
        }
    } else if (*(f32 *)(q + 0x9c28) > *(f32 *)(p + 0xab4)) {
        for (n = 0; n < 0x40; n++) {
            if (*(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] != 0) {
                *(f32 *)&((u8 *)(q + 0x9cc0))[n * 0x24] =
                    *(f32 *)&((u8 *)(q + 0x9cc0))[n * 0x24]
                    + *(f32 *)&((u8 *)(q + 0x9ccc))[n * 0x24];
                *(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24] =
                    *(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24]
                    + *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24];
                *(f32 *)&((u8 *)(q + 0x9cc8))[n * 0x24] =
                    *(f32 *)&((u8 *)(q + 0x9cc8))[n * 0x24]
                    + *(f32 *)&((u8 *)(q + 0x9cd4))[n * 0x24];
                *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] =
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24]
                    - *(f32 *)(p + 0xab8);
                *(s16 *)&((u8 *)(q + 0x9cd8))[n * 0x24] =
                    *(s16 *)&((u8 *)(q + 0x9cd8))[n * 0x24]
                    + *(s16 *)&((u8 *)(q + 0x9cdc))[n * 0x24];
                *(s16 *)&((u8 *)(q + 0x9cda))[n * 0x24] =
                    *(s16 *)&((u8 *)(q + 0x9cda))[n * 0x24]
                    + *(s16 *)&((u8 *)(q + 0x9cde))[n * 0x24];
                if (*(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24]
                    < *(f32 *)(p + 0x8b4))
                    *(s8 *)&((u8 *)(q + 0x9cbc))[n * 0x24] = 0;
            }
        }
        if (*(s32 *)(q + 0x20) == 0x78) {
            for (n = 0; n < 0x40; n++) {
                k = 0;
                do {
                    *(f32 *)&((u8 *)(q + 0x9cc0))[n * 0x24] =
                        *(f32 *)(p + 0x8d0)
                            * (*(f32 *)(p + 0xabc)
                               * ((f32)rand() / *(f32 *)(p + 0x8d8)))
                        - *(f32 *)(p + 0x9f8) - *(f32 *)(p + 0xac0);
                    *(f32 *)&((u8 *)(q + 0x9cc8))[n * 0x24] =
                        *(f32 *)(p + 0x8d0)
                            * (*(f32 *)(p + 0xac4)
                               * ((f32)rand() / *(f32 *)(p + 0x8d8)))
                        - *(f32 *)(p + 0x95c) - *(f32 *)(p + 0xac0);
                    k++;
                    ek = *(f32 *)(p + 0xaa0) * (f32)k;
                } while (mathutil_sum_of_sq_2(
                             *(f32 *)&((u8 *)(q + 0x9cc0))[n * 0x24]
                                 - *(f32 *)(q + 0x9888),
                             *(f32 *)&((u8 *)(q + 0x9cc8))[n * 0x24]
                                 - *(f32 *)(q + 0x9890))
                         > *(f32 *)(p + 0x8c0) * ek
                               * (*(f32 *)(p + 0x8c0) * ek));
                for (m = 0; m < n; m++) {
                    if (mathutil_sum_of_sq_2(
                            *(f32 *)&((u8 *)(q + 0x9cc0))[n * 0x24]
                                - *(f32 *)&((u8 *)(q + 0x9cc0))[m * 0x24],
                            *(f32 *)&((u8 *)(q + 0x9cc8))[n * 0x24]
                                - *(f32 *)&((u8 *)(q + 0x9cc8))[m * 0x24])
                        < *(f32 *)(p + 0xac8))
                        break;
                }
                if (m != n) {
                    n--;
                    continue;
                }
                for (m = 0; m < 10; m++) {
                    if (*(s8 *)&((u8 *)(q + 0x9878))[m * 0x68] == 1) {
                        if (mathutil_sum_of_sq_2(
                                *(f32 *)&((u8 *)(q + 0x9888))[m * 0x68]
                                    - *(f32 *)&((u8 *)(q + 0x9cc0))[n * 0x24],
                                *(f32 *)&((u8 *)(q + 0x9890))[m * 0x68]
                                    - *(f32 *)&((u8 *)(q + 0x9cc8))[n * 0x24])
                            < *(f32 *)(p + 0xacc))
                            break;
                    }
                }
                if (m != 10) {
                    n--;
                    continue;
                }
                if (*(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24]
                    > *(f32 *)(p + 0xa5c))
                    *(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24] =
                        *(f32 *)(p + 0xa5c);
            }

            *(f32 *)(q + 0x9c28) = *(f32 *)(p + 0x8b4);
            c = 0;
            *(f32 *)(q + 0x9c2c) = *(f32 *)(p + 0x8b4);
            *(f32 *)(q + 0x9880) = *(f32 *)(p + 0x8b8);
            *(f32 *)(q + 0x9884) = *(f32 *)(p + 0x8b4);
            do {
                c++;
                v.x = (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                v.y = *(f32 *)(p + 0x8b4);
                v.z = (f32)rand() / *(f32 *)(p + 0x8d8) - *(f32 *)(p + 0x8c0);
                e = v.x * v.x + v.z * v.z;
                if (e > *(f32 *)(p + 0x944)) {
                    e = *(f32 *)(p + 0xa5c) * mathutil_rsqrt(e);
                    v.x = v.x * e;
                    v.z = v.z * e;
                    if (v.x + *(f32 *)(q + 0x9888) < *(f32 *)(p + 0x9f8)
                        && v.x + *(f32 *)(q + 0x9888) > *(f32 *)(p + 0x9fc)
                        && v.z + *(f32 *)(q + 0x9890) < *(f32 *)(p + 0x95c)
                        && v.z + *(f32 *)(q + 0x9890) > *(f32 *)(p + 0x9dc)) {
                        for (m3 = 1; m3 < 9; m3++) {
                            if (*(s8 *)&((u8 *)(q + 0x9878))[m3 * 0x68] == 1) {
                                if (mathutil_sum_of_sq_2(
                                        *(f32 *)(q + 0x9888) + v.x
                                            - *(f32 *)&((u8 *)(q
                                                               + 0x9888))[m3
                                                                          * 0x68],
                                        *(f32 *)(q + 0x9890) + v.z
                                            - *(f32 *)&((u8 *)(q
                                                               + 0x9890))[m3
                                                                          * 0x68])
                                    < *(f32 *)(p + 0xad0))
                                    break;
                                if (lbl_00018608(
                                        *(f32 *)(q + 0x9888),
                                        *(f32 *)(q + 0x9890),
                                        *(f32 *)(q + 0x9888) + v.x,
                                        *(f32 *)(q + 0x9890) + v.z,
                                        *(f32 *)&((u8 *)(q + 0x9888))[m3 * 0x68],
                                        *(f32 *)&((u8 *)(q + 0x9890))[m3 * 0x68])
                                    < *(f32 *)(p + 0x8c0))
                                    break;
                            }
                        }
                        if (m3 == 9)
                            c = -1;
                    }
                }
            } while (c > -1 && c < 100);

            cameraInfo[0].eye.x = *(f32 *)(q + 0x9888) + v.x;
            cameraInfo[0].eye.z = *(f32 *)(q + 0x9890) + v.z;
            if (c < 100)
                cameraInfo[0].eye.y = *(f32 *)(p + 0x8c0);
            else
                cameraInfo[0].eye.y = *(f32 *)(p + 0xa1c);
            *(s32 *)(q + 0x20) = 0;
            lbl_802F1C30 = 0x1800;
        }
    } else {
        for (n = 0; n < 0x40; n++) {
            if (__fabs(*(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24]
                       - *(f32 *)(p + 0xad4))
                > *(f64 *)(p + 0x9e0)) {
                *(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24] =
                    *(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24]
                    + *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24];
                *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24] =
                    *(f32 *)&((u8 *)(q + 0x9cd0))[n * 0x24]
                    - *(f32 *)(p + 0xab8);
                if (*(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24]
                    < *(f32 *)(p + 0xad4))
                    *(f32 *)&((u8 *)(q + 0x9cc4))[n * 0x24] =
                        *(f32 *)(p + 0xad4);
            }
            *(s16 *)&((u8 *)(q + 0x9cd8))[n * 0x24] = 0;
            *(s16 *)&((u8 *)(q + 0x9cda))[n * 0x24] =
                *(s16 *)&((u8 *)(q + 0x9cda))[n * 0x24]
                + *(s16 *)&((u8 *)(q + 0x9cde))[n * 0x24];
        }
        if (*(s32 *)(q + 0x20) > 0xb4)
            st = 1;
    }

    if (lbl_0000939C(1))
        st = 2;
    if (st != 0) {
        event_finish(0x12);
        event_start(0x12);
        u_play_music(0x64, 8);
        lbl_00018008();
        if (*(s8 *)(q + 4) != 0) {
            if (controllerInfo[playerControllerIDs[0]].held.button != 0x200)
                *(s8 *)(q + 4) = 0;
        }
    }
}
#pragma peephole on
void lbl_00006DC0(void)
{
    u8 *p = lbl_0001C2B8;
    u8 *q = lbl_10000000;
    Vec sp24;
    Vec d;
    s8 sp10[5];
    s8 sp8[5];
    int i;
    int j;
    int ok;
    s8 cnt;
    s8 flag;
    s8 hit;
    f32 t;
    cnt = 0;
    sp24 = *(Vec *)(p + 0xAD8);
    flag = ((ok = (*(s16 *)(q + 0xA68) < *(s8 *)(q + 0x11) / 2 + 1 &&
                   *(s16 *)(q + 0xA6E) < *(s8 *)(q + 0x11) / 2 + 1)) != 0 ||
            *(s8 *)(q + 0x11) == -1);
    if (flag != 0) {
        if (*(s32 *)(q + 0x20) == 1) {
            cameraInfo[0].eye.x = *(f32 *)(p + 0x9C4);
            cameraInfo[0].eye.y = *(f32 *)(p + 0xA1C);
            cameraInfo[0].eye.z = *(f32 *)(p + 0x8B4);
            *(f32 *)(q + 0x9C34) = *(f32 *)(p + 0x8C0);
            for (i = 0; i < 2; i++) {
                *(f32 *)&((u8 *)(q + 0x98CC))[i * 0x68] = *(f32 *)(p + 0x8B4);
                *(f32 *)&((u8 *)(q + 0x98D0))[i * 0x68] = *(f32 *)(p + 0x8B4);
                *(f32 *)&((u8 *)(q + 0x98D4))[i * 0x68] = *(f32 *)(p + 0x8B4);
                *(f32 *)&((u8 *)(q + 0x98D8))[i * 0x68] = *(f32 *)(p + 0x8B8);
            }
        }
        *(s8 *)(q + 0x9878) = 0;
        *(f32 *)(q + 0x9880) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x9884) = *(f32 *)(p + 0x8B4);
        for (i = 1; i < 10; i++) {
            *(s8 *)&((u8 *)(q + 0x9878))[i * 0x68] = 1;
            *(f32 *)&((u8 *)(q + 0x9880))[i * 0x68] = *(f32 *)(p + 0x8B8);
            *(f32 *)&((u8 *)(q + 0x9884))[i * 0x68] = *(f32 *)(p + 0x8B4);
            if (*(f32 *)&((u8 *)(q + 0x988C))[i * 0x68] < *(f32 *)(p + 0xAE4)) {
                *(f32 *)&((u8 *)(q + 0x988C))[i * 0x68] += *(f32 *)(p + 0x9EC);
                if (*(f32 *)&((u8 *)(q + 0x988C))[i * 0x68] >= *(f32 *)(p + 0x8C0))
                    *(f32 *)&((u8 *)(q + 0x988C))[i * 0x68] = *(f32 *)(p + 0x8C0);
            } else {
                Vec *v = (Vec *)&((u8 *)(q + 0x98AC))[i * 0x68];
                f32 s;

                *(f32 *)&((u8 *)(q + 0x988C))[i * 0x68] = *(f32 *)(p + 0x8C0);
                *(f32 *)&((u8 *)(q + 0x98AC))[i * 0x68] = *(f32 *)&((u8 *)(q + 0x98A0))[i * 0x68] - *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68];
                *(f32 *)&((u8 *)(q + 0x98B0))[i * 0x68] = *(f32 *)(p + 0x8B4);
                *(f32 *)&((u8 *)(q + 0x98B4))[i * 0x68] = *(f32 *)&((u8 *)(q + 0x98A8))[i * 0x68] - *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68];
                s = mathutil_vec_sq_len(v);
                if (s > *(f32 *)(p + 0x944)) {
                    if (s > *(f32 *)(p + 0x9E8)) {
                        mathutil_vec_normalize_len(v);
                        *(f32 *)&((u8 *)(q + 0x98AC))[i * 0x68] *= *(f32 *)(p + 0x9EC);
                        *(f32 *)&((u8 *)(q + 0x98B4))[i * 0x68] *= *(f32 *)(p + 0x9EC);
                    } else {
                        cnt++;
                    }
                    *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68] += *(f32 *)&((u8 *)(q + 0x98AC))[i * 0x68];
                    *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68] += *(f32 *)&((u8 *)(q + 0x98B4))[i * 0x68];
                    if (i != 0) {
                        Quaternion *qq = (Quaternion *)&((u8 *)(q + 0x98CC))[i * 0x68];

                        u_math_unk8(qq, (Vec *)&((u8 *)(q + 0x98AC))[i * 0x68], &sp24,
                                    *(f32 *)(p + 0x8C0));
                    }
                } else {
                    cnt++;
                    *(f32 *)&((u8 *)(q + 0x98CC))[i * 0x68] = *(f32 *)(p + 0x8B4);
                    *(f32 *)&((u8 *)(q + 0x98D0))[i * 0x68] = *(f32 *)(p + 0x8B4);
                    *(f32 *)&((u8 *)(q + 0x98D4))[i * 0x68] = *(f32 *)(p + 0x8B4);
                    *(f32 *)&((u8 *)(q + 0x98D8))[i * 0x68] = *(f32 *)(p + 0x8B8);
                }
            }
        }
        if (cnt == 9 && *(s32 *)(q + 0x20) < 0x1A4)
            *(s32 *)(q + 0x20) = 0x1A4;
        cnt = 0;
        do {
            hit = 0;
            for (i = 0; i < 9; i++) {
                if ((s8)*(u8 *)&((u8 *)(q + 0x9878))[i * 0x68] != 1)
                    continue;
                for (j = i + 1; j < 10; j++) {
                    if ((s8)*(u8 *)&((u8 *)(q + 0x9878))[j * 0x68] != 1)
                        continue;
                    d.x = *(f32 *)&((u8 *)(q + 0x9888))[i * 0x68] - *(f32 *)&((u8 *)(q + 0x9888))[j * 0x68];
                    d.y = *(f32 *)&((u8 *)(q + 0x988C))[i * 0x68] - *(f32 *)&((u8 *)(q + 0x988C))[j * 0x68];
                    d.z = *(f32 *)&((u8 *)(q + 0x9890))[i * 0x68] - *(f32 *)&((u8 *)(q + 0x9890))[j * 0x68];
                    if (d.x * d.x + d.y * d.y + d.z * d.z < *(f32 *)(p + 0x8B8)) {
                        t = mathutil_sqrt(*(f32 *)(p + 0x8B8) - d.x * d.x - d.z * d.z);
                        *(f32 *)&((u8 *)(q + 0x988C))[i * 0x68] = t + *(f32 *)&((u8 *)(q + 0x988C))[j * 0x68];
                        hit = 1;
                    }
                }
            }
            cnt++;
        } while (hit != 0 && cnt < 0x64);
    } else {
        if (*(s32 *)(q + 0x20) == 1) {
            lbl_802F1DFC = 0;
            u_somePlayerId = 0;
            u_play_sound_0(0x1E0);
        }
        *(f32 *)(q + 0x98F0) = *(f32 *)(p + 0x954);
        *(f32 *)(q + 0x98F8) = *(f32 *)(p + 0xAE8);
        *(f32 *)(q + 0x9958) = *(f32 *)(p + 0x8DC);
        *(f32 *)(q + 0x9960) = *(f32 *)(p + 0xAE8);
        *(f32 *)(q + 0x99C0) = *(f32 *)(p + 0x954);
        *(f32 *)(q + 0x99C8) = *(f32 *)(p + 0x8E4);
        *(f32 *)(q + 0x9A28) = *(f32 *)(p + 0x8DC);
        *(f32 *)(q + 0x9A30) = *(f32 *)(p + 0x8E4);
        *(f32 *)(q + 0x98E8) = *(f32 *)(p + 0x8B8);
        *(f32 *)(q + 0x9950) = *(f32 *)(p + 0x8B8);
        *(f32 *)(q + 0x99B8) = *(f32 *)(p + 0x8B8);
        *(f32 *)(q + 0x9A20) = *(f32 *)(p + 0x8B8);
        *(f32 *)(q + 0x98EC) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x9954) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x99BC) = *(f32 *)(p + 0x8B4);
        *(f32 *)(q + 0x9A24) = *(f32 *)(p + 0x8B4);
    }
    if ((flag != 0 && (*(s32 *)(q + 0x20) > 0x1E0 || lbl_0000939C(0) != 0)) ||
        (flag == 0 && *(s32 *)(q + 0x20) > 0xB4 && lbl_0000939C(0) != 0)) {
        if (*(s8 *)(q + 0x11) != -1 &&
            ((*(s8 *)(q + 0x1E) == 0 &&
              (*(s16 *)(q + 0xA68) >= *(s8 *)(q + 0x11) / 2 + 1 ||
               *(s16 *)(q + 0xA6E) >= *(s8 *)(q + 0x11) / 2 + 1)) ||
             ((s8)*(u8 *)(q + 0x1E) == 4 &&
              *(s16 *)(q + 0xA68) >= *(s8 *)(q + 0x11) / 2 + 1) ||
             (*(s8 *)(q + 0x1E) > 0 &&
              *(s16 *)(q + 0xA6E) >= *(s8 *)(q + 0x11) / 2 + 1))) {
            for (i = 15; i >= 0; i--) {
                if (*(s32 *)&((u8 *)(q + 0x64))[i * 4] != -1) {
                    thread_kill(*(s32 *)&((u8 *)(q + 0x64))[i * 4]);
                    *(s32 *)&((u8 *)(q + 0x64))[i * 4] = -1;
                }
            }
            for (i = 0; i < 10; i++)
                *(s8 *)&((u8 *)(q + 0x9878))[i * 0x68] = 0;
            camera_set_state_all(0x46);
            *(s8 *)(q + 0xB) = *(s8 *)(q + 0xA);
            *(s32 *)(q + 0x20) = 0;
            *(s8 *)(q + 0xA) = 0x19;
            *(s8 *)(q + 0x17) = 0;
            event_finish(0x12);
            event_start(0x12);
            u_play_music(0x64, 8);
            event_start(0xD);
            if ((s8)*(u8 *)(q + 0x1E) == 4 &&
                *(s16 *)(q + 0xA68) >= *(s8 *)(q + 0x11) / 2 + 1) {
                sp10[4] = *(u8 *)(q + 0xA65);
                sp10[0] = 0x40;
                sp10[1] = 0x41;
                sp10[2] = 0x42;
                sp10[3] = 0x43;
                sp8[4] = 0;
                sp8[0] = 3;
                sp8[1] = 3;
                sp8[2] = 3;
                sp8[3] = 3;
                pauseMenuState.unk4 |= 2;
                *(s8 *)(q + 0x1E) = 5;
                func_8009CAE0(sp10, sp8, 0);
            } else {
                sp10[0] = *(u8 *)(q + 0xA65);
                if (*(s8 *)(q + 0xA66) != 0)
                    sp10[0] |= 0x40;
                sp10[1] = *(u8 *)(q + 0xA6B);
                if (*(s8 *)(q + 0xA6C) != 0)
                    sp10[1] |= 0x40;
                sp10[3] = -1;
                sp10[2] = -1;
                if (*(s16 *)(q + 0xA68) > *(s16 *)(q + 0xA6E)) {
                    sp8[0] = 0;
                    sp8[1] = 1;
                    lbl_802F1C32 = 0;
                } else {
                    sp8[0] = 1;
                    sp8[1] = 0;
                    lbl_802F1C32 = 1;
                }
                pauseMenuState.unk4 |= 2;
                func_8009C5E4(sp10, sp8);
            }
            lbl_00009EC4();
            start_screen_fade(0x100, 0xFFFFFF, 4);
        } else if (*(s8 *)(q + 0x1E) > 0 &&
                   *(s16 *)(q + 0xA68) >= *(s8 *)(q + 0x11) / 2 + 1) {
            *(s8 *)(q + 0x1E) = *(u8 *)(q + 0x1E) + 1;
            if ((s8)*(u8 *)(q + 0x1E) == 4 &&
                (*(s8 *)(q + 0x11) >= 0x5A ||
                 (*(s16 *)(q + 0x9782) + *(s16 *)(q + 0x97CA) + *(s16 *)(q + 0x9812) == 0 &&
                  (s8)*(u8 *)(q + 0x61) == 4 && *(s8 *)(q + 0x11) >= 3) ||
                 (controllerInfo[playerControllerIDs[0]].held.triggerLeft > 0x14 &&
                  controllerInfo[playerControllerIDs[0]].held.triggerLeft < 0x64 &&
                  controllerInfo[playerControllerIDs[0]].held.triggerRight > 0x14 &&
                  controllerInfo[playerControllerIDs[0]].held.triggerRight < 0x64)))
                *(s8 *)(q + 4) = 1;
            else
                *(s8 *)(q + 4) = 0;
            *(s8 *)(q + 0xB) = *(s8 *)(q + 0xA);
            *(s32 *)(q + 0x20) = 0;
            *(s8 *)(q + 0xA) = 7;
            cameraInfo[0].eye.x = *(f32 *)(p + 0x958);
            cameraInfo[0].eye.y = *(f32 *)(p + 0x8C0);
            cameraInfo[0].eye.z = *(f32 *)(p + 0x95C);
            for (i = 0; i < 10; i++) {
                *(s8 *)&((u8 *)(q + 0x9878))[i * 0x68] = 0;
                *(f32 *)&((u8 *)(q + 0x9880))[i * 0x68] = *(f32 *)(p + 0x8B4);
                *(f32 *)&((u8 *)(q + 0x9884))[i * 0x68] = *(f32 *)(p + 0x8B4);
            }
            *(s8 *)(q + 0x9878) = 1;
            *(s8 *)(q + 0x98E0) = 1;
            *(s8 *)(q + 0xA6B) = *(s8 *)&((u8 *)(p + 0x8AF))[*(s8 *)(q + 0x1E)];
            *(s16 *)(q + 0xA68) = 0;
            *(s16 *)(q + 0xA6E) = 0;
            lbl_00003CC8();
            u_play_music(0x64, 8);
        } else {
            *(s32 *)(q + 0x20) = 0;
            *(s8 *)(q + 0xB) = *(s8 *)(q + 0xA);
            lbl_802F1C32 = 1 - lbl_802F1C32;
            lbl_00000800();
            lbl_802F1DFC = *(s8 *)&((u8 *)(q + 0xA65))[lbl_802F1C32 * 6];
            u_somePlayerId = lbl_802F1C32;
            u_play_sound_0(0x1E);
            lbl_00008EC0(4, 1);
            *(s8 *)(q + 0xA) = 0xC;
            lbl_00003CC8();
            u_set_global_skelanim_speed_scale(*(f32 *)(p + 0x8B8));
            u_play_music(0x64, 8);
        }
    }
}
#pragma peephole on
void lbl_000077D8(void)
{
    Mtx m;
    u8 *b = lbl_10000000;
    u8 *c = lbl_0001C2B8;

    mathutil_mtxA_from_identity();
    mathutil_mtxA_translate_xyz(*(f32 *)(c + 0x8b4), *(f32 *)(c + 0x8b8),
                                *(f32 *)(c + 0x8b4));
    mathutil_mtxA_to_mtx(m);
    func_8009DB40(m);

    if (*(s32 *)(b + 0x20) == 0xf0 && *(s8 *)(b + 0x1e) == 5) {
        func_8009DDC4(2);
        camera_set_state_all(0x41);
        cameraInfo[1].state = 0x42;
        cameraInfo[0].unk26 = 10;
        cameraInfo[0].flags |= 0x10;
        cameraInfo[1].unk26 = 10;
        cameraInfo[1].flags |= 0x10;
        lbl_802F1C30 = 0x2aaa;
    }

    if (*(s8 *)(b + 0x1e) == 5 && *(s32 *)(b + 0x20) > 0xf0) {
        if (lbl_802F1C30 <= 0x1000)
            func_8009DB9C(0xb);
    }

    if ((*(s8 *)(b + 0x1e) != 5 && *(s32 *)(b + 0x20) > 0x258)
        || (*(s8 *)(b + 0x1e) == 5 && *(s8 *)(b + 0x17) != 0)) {
        if (lbl_0000939C(2) != 0) {
            u_play_sound_0(0xd1);
            *(s32 *)(b + 0x20) = -61;
        }
    }

    if (*(s32 *)(b + 0x20) < 0) {
        if (*(s32 *)(b + 0x20) == -61) {
            start_screen_fade(0x101, 0xffffff, 0x3c);
            u_play_music(0x3c, 2);
        }
        if (*(s32 *)(b + 0x20) == -1) {
            mini_commend_free_data();
            func_80012434(modeCtrl.gameType);
        }
    }
}
/* lbl_00007974 -- run 19 draft a, decoded from a blank page.
   Reachable TODAY: src/mini_billiards_7.c.o already emits the SIGNED magic and
   the link map places it at 0x1CBD0, which is the address this function loads.
   No carve, no merge.  */
void lbl_00007974(void)
{
    u8 *b = lbl_10000000;
    u8 *c = lbl_0001C2B8;
    int ang;
    struct BB7974 *w;
    int i;

    if (*(s32 *)(b + 0x20) == 1) {
        lbl_802F1DFC = 0;
        u_somePlayerId = 0;
        switch (*(s8 *)(b + 0x1e)) {
        case 1:
            u_play_sound_0(0x16f);
            break;
        case 2:
            SoundRevID(u_play_sound_1_dupe(0x170), 0x20);
            break;
        case 3:
            SoundRevID(u_play_sound_1_dupe(0x171), 0x40);
            break;
        case 4:
            if (*(s8 *)(b + 4) != 0)
                SoundRevID(u_play_sound_1_dupe(0x182), 0x7f);
            else
                SoundRevID(u_play_sound_1_dupe(0x178), 0x60);
            break;
        }
    }

    if (*(s32 *)(b + 0x20) == 4) {
        lbl_802F1DFC = 0;
        u_somePlayerId = 0;
        switch (*(s8 *)(b + 0x1e)) {
        case 4:
            if (*(s8 *)(b + 4) != 0)
                SoundRevID(u_play_sound_1_dupe(0x182), 0x7f);
            else
                SoundRevID(u_play_sound_1_dupe(0x178), 0x60);
            break;
        }
    }

    *(f32 *)(b + 0x9888) = *(f32 *)(c + 0xa18);
    *(f32 *)(b + 0x988c) = *(f32 *)(c + 0x8c0);
    *(f32 *)(b + 0x9890) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x98f0) = *(f32 *)(c + 0x8b8);
    *(f32 *)(b + 0x98f4) = *(f32 *)(c + 0x8c0);
    *(f32 *)(b + 0x98f8) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x9880) = *(f32 *)(c + 0x8b8);
    *(f32 *)(b + 0x9884) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x98e8) = *(f32 *)(c + 0x8b8);
    *(f32 *)(b + 0x98ec) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x98cc) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x98d0) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x98d4) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x98d8) = *(f32 *)(c + 0x8b8);
    *(f32 *)(b + 0x9934) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x9938) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x993c) = *(f32 *)(c + 0x8b4);
    *(f32 *)(b + 0x9940) = *(f32 *)(c + 0x8b8);

    if (*(s8 *)(b + 4) != 0) {
        w = (struct BB7974 *)(b + 0x9878);
        for (i = 0, ang = 0x6000; i < 7; i++) {
            func_80007214((s16)ang, &((struct BB7974 *)(b + 0x9878))[i + 2].x,
                          &((struct BB7974 *)(b + 0x9878))[i + 2].z);
            w[2].x *= *(f32 *)(c + 0xaec);
            w[2].z *= *(f32 *)(c + 0xaec);
            w[2].y = *(f32 *)(c + 0x8c0);
            w[2].state = 1;
            w[2].unk54 = *(f32 *)(c + 0x8b4);
            w[2].unk58 = *(f32 *)(c + 0x8b4);
            w[2].unk5C = *(f32 *)(c + 0x8b4);
            w[2].unk60 = *(f32 *)(c + 0x8b8);
            w++;
            ang += 0xaaa;
        }
    }

    cameraInfo[0].eye.x =
        *(f32 *)(c + 0x908) * (f32)(0x78 - *(s32 *)(b + 0x20));
    cameraInfo[0].eye.y = *(f32 *)(c + 0x8c0);
    cameraInfo[0].eye.z = *(f32 *)(c + 0x95c);

    if (*(s32 *)(b + 0x20) > 0x78 || lbl_0000939C(0) != 0) {
        *(s8 *)(b + 0xb) = *(s8 *)(b + 0xa);
        *(s32 *)(b + 0x20) = 0;
        *(s8 *)(b + 0xa) = 8;
        lbl_00002B4C();
        lbl_00003CC8();
    }
}
#pragma peephole on
void lbl_00007C74(void)
{
    int i;
    for (i = 0; i < 64; i++) {
        *(s16 *)(lbl_1000A5BC + i * 0x10 + 0x0) = -1;
        *(s32 *)(lbl_1000A5BC + i * 0x10 + 0xc) = 0;
    }
}
void lbl_00007D18(s16 arg0, s32 arg1)
{
    struct Work7D18 *w = (struct Work7D18 *)lbl_10000000;
    struct Rec7D18 *p = w->recs;
    int i;
    for (i = 0; i < 64; p++, i++) {
        if (p->unk0 == -1) {
            w->recs[i].unk0 = arg0;
            w->recs[i].unkC = arg1;
            w->recs[i].unk4 = lbl_802F1DFC;
            w->recs[i].unk8 = u_somePlayerId;
            return;
        }
    }
}
asm void lbl_00007D80(void)
{
    nofralloc
#include "../asm/nonmatchings/mini_billiards/lbl_00007D80.s"
}
#pragma peephole on
asm void lbl_00008EC0(int a, int b)
{
    nofralloc
#include "../asm/nonmatchings/mini_billiards/lbl_00008EC0.s"
}
#pragma peephole on
#pragma force_active reset
