/*
 * sel_ngc_rel.c -- REL module, structurally split for per-function
 * byte-matching (part 29 of 56; contiguous .text range).  Each function
 * below is an asm-include of its body in asm/nonmatchings/sel_ngc_rel/.
 * To convert one to C, isolate it into its own pure-C file (see the
 * --isolate option of tools/rel_split.py) -- an asm sibling in the same
 * TU disables mwcc's optimizer for the C function.  Keep the Makefile
 * SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <dolphin.h>
#include "stddef.h"
#include "stdio.h"
#include "stdlib.h"
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "pool.h"
#include "rend_efc.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "pause_menu.h"
#include "string.h"
#include "avdisp.h"
#include "background.h"
#include "obj_collision.h"
#include "ord_tbl.h"
#include "stcoli.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/sel_ngc_rel.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_00011B68[];
extern u8 lbl_00011BC0[];
extern u8 lbl_00011BC8[];
extern u8 lbl_00011BD4[];
extern u8 lbl_00011C40[];
extern u8 lbl_00011CB0[];
extern u8 lbl_00011CB8[];
extern u8 lbl_00011D00[];
extern u8 lbl_00011D08[];
extern u8 lbl_00011D44[];
extern u8 lbl_00011E70[];
extern u8 lbl_00011E7C[];
extern u8 lbl_00011EC8[];
extern u8 lbl_00012030[];
extern u8 lbl_00012034[];
extern u8 lbl_00012038[];
extern u8 lbl_0001203C[];
extern u8 lbl_00012160[];
extern u8 lbl_00012180[];
extern u8 lbl_0001219C[];
extern u8 lbl_00012238[];
extern u8 lbl_0001225C[];
extern u8 lbl_000125FC[];
extern u8 lbl_00012620[];
extern u8 lbl_00012644[];
extern u8 lbl_00012730[];
extern u8 lbl_00012798[];
extern u8 lbl_000127B8[];
extern u8 lbl_000127D8[];
extern u8 lbl_000127F8[];
extern u8 lbl_00012970[];
extern u8 lbl_00016420[];
extern u8 lbl_00016440[];
extern u8 lbl_00016484[];
extern u8 lbl_0001681C[];
extern u8 lbl_00016B48[];
extern u8 lbl_00017048[];
extern u8 lbl_00017420[];
extern u8 lbl_00017460[];
extern u8 lbl_0001746C[];
extern u8 lbl_00017478[];
extern u8 lbl_00017490[];
extern u8 lbl_10000000[];
extern u8 lbl_10000018[];
extern u8 lbl_1000003C[];
extern u8 lbl_100000C0[];
extern u8 lbl_10000804[];
extern u8 lbl_100009D4[];
extern u8 lbl_100009D8[];
extern u8 g_totalPlayPoints[];
extern u8 lbl_801EED50[];
extern u8 lbl_801EED98[];
extern u8 lbl_8027CE24[];
extern u8 lbl_802F1FA8[];
extern u8 lbl_802F1FAC[];
extern u8 lbl_802F1FB0[];
extern u8 lbl_802F1FB4[];
extern u8 u_isCompetitionModeCourse[];

// Imported functions the code calls that no included header declares.
extern void __cvt_fp2unsigned();
extern void are_all_continues_unlocked();
extern void course_first();
extern int course_floor_count(int, u32);
extern void effect_draw();
extern void empty_file_cache();
extern void empty_load_queue();
extern void file_preload();
extern void floor_to_stage_id();
extern void func_8009F4C4();
extern void func_80067310();
extern int is_floor_visited(int, int, u32);
extern void is_minigame_unlocked();
extern void item_draw();
extern void lens_flare_draw();
extern void lens_flare_draw_mask();
extern void memcard_set_mode();
extern void nl2ngc_draw_model_sort_translucent_alt2();
extern void preview_create();
extern void preview_create_with_allocated_tex();
extern void preview_draw();
extern void preview_free();
extern void preview_main();
extern void spend_play_points();
extern void start_preview_image_read();
extern void stobj_draw();
extern void textbox_add_text();
extern void textbox_set_properties();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_00000234(void);
void lbl_0000033C(void);
void lbl_000005D4(void);
void lbl_00001910(void);
void lbl_00001968(void);
void lbl_00001B38(void);
void lbl_00001D58(void);
void lbl_00001E10(void);
void lbl_00002358(void);
void lbl_00002484(void);
void lbl_0000259C(void);
void lbl_0000269C(void);
void lbl_000027AC(void);
void lbl_000028A8(void);
void lbl_000029A8(void);
void lbl_00002D00(void);
void lbl_00002EC0(void);
void lbl_000030F4(void);
void lbl_00009868(void);
void lbl_0000A3A4(void);
void lbl_0000A4A0(void);
void lbl_0000A544(void);
void lbl_0000A634(void);
void lbl_0000A658(void);
void lbl_0000A67C(void);
void lbl_0000A6C8(void);
void lbl_0000A7B0(void);
void lbl_0000A7D4(void);
void lbl_0000A840(void);
void lbl_0000A870();
void lbl_0000A950(void);
void lbl_0000B1C0(void);
void lbl_0000B920(void);
void lbl_0000BEE8(struct Sprite *);
void lbl_0000C970(void);
void lbl_0000D82C(struct Sprite *sprite);
void lbl_0000DCA4(s8 *alive, struct Sprite *sprite);
void lbl_0000DEC8(s8 *alive, struct Sprite *sprite);
void lbl_0000E068(struct Sprite *sprite);
void lbl_0000E368(s8 *alive, struct Sprite *sprite);
void lbl_0000E778(void);
void lbl_0000ECB0(void);
void lbl_0000F788(void);
void lbl_0000FE0C(void);
void lbl_0000FF7C(s8 *alive, struct Sprite *sprite);
void lbl_00010214(struct Sprite *sprite);
void lbl_00010438(void);
void lbl_00011330(void);
void lbl_00011424(void);
void lbl_00011688(void);
void lbl_00011728(void);
void lbl_00011824(void);
void lbl_000118E4(void);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
void lbl_0000AFB0(struct Sprite *sprite);
void lbl_0000B0FC(s8 *alive, struct Sprite *sprite);
static void lbl_0000C518(void);
void lbl_0000D39C(s8 *alive, struct Sprite *sprite);
struct SelNgcSlotPos
{
    f32 x;
    f32 y;
};
extern int is_load_queue_not_empty(void);
void lbl_0000D5A8(struct Sprite *sprite);
void lbl_0000D7C0(s8 *alive, struct Sprite *sprite);
void lbl_0000DDF4(struct Sprite *sprite);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
void lbl_0000E43C(s8 *alive, struct Sprite *sprite);
void lbl_0000E4BC(s8 *alive, struct Sprite *sprite);
void lbl_0000E540(struct Sprite *sprite);
void lbl_0000E620(struct Sprite *sprite);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
void lbl_0000EBD4(int index);

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
void lbl_000101BC(s8 *alive, struct Sprite *sprite);

#pragma force_active on
void lbl_0000A950(void)
{
    u8 *tbl = lbl_00012730;
    u8 *k = lbl_00011CB0;
    struct Sprite *sprite;
    f64 pad;

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->type = 1;
        sprite->bmpId = 0x404;
        sprite->x = *(f32 *)(k + 0x14);
        sprite->y = *(f32 *)(k + 0x18);
        sprite->depth = *(f32 *)(k + 0x1C);
        sprite->textAlign = 4;
        sprite->flags |= 0x40000;
        sprintf(sprite->text, (char *)(tbl + 0xE8));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->tag = 0x16;
        sprite->fontId = 0xB1;
        sprite->x = *(f32 *)(k + 0x14);
        sprite->y = *(f32 *)(k + 0x20);
        sprite->textAlign = 4;
        sprite->bmpId = 0x40D;
        sprite->flags |= 0x200000;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000AFB0;
        strcpy(sprite->text, (char *)(tbl + 0xEC));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->tag = 0x17;
        sprite->fontId = 0xB1;
        sprite->x = *(f32 *)(tbl + 0x28);
        sprite->y = *(f32 *)(tbl + 0x2C);
        sprite->textAlign = 4;
        sprite->userVar = 0x11;
        sprite->bmpId = 0x40C;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000B0FC;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000B1C0;
        strcpy(sprite->text, (char *)(tbl + 0xF4));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->tag = 0x18;
        sprite->fontId = 0xB1;
        sprite->x = *(f32 *)(tbl + 0x40);
        sprite->y = *(f32 *)(tbl + 0x44);
        sprite->textAlign = 4;
        sprite->userVar = 0;
        sprite->bmpId = 0x416;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000B0FC;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000B920;
        strcpy(sprite->text, (char *)(tbl + 0xF8));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->tag = 0x19;
        sprite->fontId = 0x36;
        sprite->x = *(f32 *)(tbl + 0x50);
        sprite->y = *(f32 *)(tbl + 0x54);
        sprite->textAlign = 4;
        sprite->userVar = 0;
        sprite->bmpId = 0x417;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000B0FC;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000BEE8;
        strcpy(sprite->text, (char *)(tbl + 0x100));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->tag = 0x1A;
        sprite->fontId = 0xB1;
        sprite->x = *(f32 *)(tbl + 0x60);
        sprite->y = *(f32 *)(tbl + 0x64);
        sprite->textAlign = 4;
        sprite->userVar = 0;
        sprite->bmpId = 0x433;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000B0FC;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000C970;
        strcpy(sprite->text, (char *)(tbl + 0x108));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->type = 1;
        sprite->tag = 0x1B;
        sprite->x = *(f32 *)(tbl + 0x68);
        sprite->y = *(f32 *)(tbl + 0x6C) + (modeCtrl.gameType == 2 ? 0x18 : 0);
        sprite->textAlign = 4;
        sprite->userVar = 0;
        sprite->scaleX = *(f32 *)(k + 0xC);
        sprite->scaleY = modeCtrl.gameType == 2 ? *(f64 *)(k + 0x28) : *(f64 *)(k + 0x30);
        sprite->counter = 9;
        sprite->bmpId = 0x429;
        sprite->depth = *(f32 *)(k + 0x38);
        sprite->flags |= 0x40000;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000D39C;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000D5A8;
        strcpy(sprite->text, (char *)(tbl + 0x110));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->fontId = 0xB1;
        sprite->textAlign = 4;
        sprite->depth = *(f32 *)(k + 0x3C);
        sprite->scaleX = *(f32 *)(k + 0x40);
        sprite->scaleY = *(f32 *)(k + 0x40);
        sprite->depth = *(f32 *)(k + 0x44);
        sprite->userVar = 0;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000E368;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000E540;
        strcpy(sprite->text, (char *)(tbl + 0x11C));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->type = 1;
        sprite->tag = 0x1C;
        sprite->x = *(f32 *)(tbl + 0x88);
        sprite->y = *(f32 *)(tbl + 0x8C);
        sprite->textAlign = 4;
        sprite->userVar = 0;
        sprite->bmpId = 0x42A;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000D7C0;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000D82C;
        strcpy(sprite->text, (char *)(tbl + 0x12C));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->type = 1;
        sprite->tag = 0x21;
        sprite->x = *(f32 *)(tbl + 0xA8);
        sprite->y = *(f32 *)(tbl + 0xAC);
        sprite->textAlign = 4;
        sprite->userVar = 0;
        sprite->bmpId = 0x406;
        sprite->depth = *(f32 *)(k + 0x38);
        sprite->flags |= 0x40000;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000DCA4;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000DDF4;
        strcpy(sprite->text, (char *)(tbl + 0x138));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->fontId = 0xB1;
        sprite->textAlign = 4;
        sprite->scaleX = *(f32 *)(k + 0x40);
        sprite->scaleY = *(f32 *)(k + 0x40);
        sprite->depth = *(f32 *)(k + 0x44);
        sprite->userVar = 0;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000E43C;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000E540;
        strcpy(sprite->text, (char *)(tbl + 0x144));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->textAlign = 4;
        sprite->depth = *(f32 *)(k + 0x44);
        sprite->userVar = 0;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000E43C;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000E620;
        strcpy(sprite->text, (char *)(tbl + 0x154));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->type = 1;
        sprite->tag = 0x22;
        sprite->x = *(f32 *)(tbl + 0xC8);
        sprite->y = *(f32 *)(tbl + 0xCC);
        sprite->textAlign = 4;
        sprite->userVar = 0;
        sprite->bmpId = 0x409;
        sprite->depth = *(f32 *)(k + 0x38);
        sprite->flags |= 0x40000;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000DEC8;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000E068;
        strcpy(sprite->text, (char *)(tbl + 0x168));
    }

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->fontId = 0xB1;
        sprite->textAlign = 4;
        sprite->depth = *(f32 *)(k + 0x3C);
        sprite->scaleX = *(f32 *)(k + 0x48);
        sprite->scaleY = *(f32 *)(k + 0x48);
        sprite->depth = *(f32 *)(k + 0x44);
        sprite->userVar = 0;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000E4BC;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000E778;
        strcpy(sprite->text, (char *)(tbl + 0x178));
    }
}
#pragma force_active reset

#pragma force_active on
void lbl_0000AFB0(struct Sprite *sprite)
{
    void (*save)(struct Sprite *);

    lbl_0000A870();
    reset_text_draw_settings();
    set_text_font(sprite->fontId);
    func_80071B50(sprite->flags);
    strcpy(sprite->text, *(char **)(lbl_00012970 + sprite->userVar * 4));
    save = sprite->drawFunc;
    sprite->drawFunc = NULL;
    calc_sprite_bounds(sprite, &sprite->left, &sprite->top, &sprite->right, &sprite->bottom);
    sprite->drawFunc = save;
    set_text_mul_color(0x202000);
    set_text_pos(sprite->left + 3, sprite->top + 3);
    sprite_puts(sprite->text);
    set_text_mul_color(0xFFFF00);
    set_text_pos(sprite->left, sprite->top);
    sprite_puts(sprite->text);
}
#pragma force_active reset

#pragma force_active on
// sprite mainFunc: ease towards the selected/unselected slot for this tag.
void lbl_0000B0FC(s8 *alive, struct Sprite *sprite)
{
    f32 *tbl = (f32 *)lbl_00012730;
    f64 *k = (f64 *)lbl_00011CB0;
    int i = sprite->tag - 23;

    switch (sprite->userVar)
    {
    case 0:
        sprite->x = sprite->x + k[11] * (tbl[i * 4 + 12] - sprite->x);
        sprite->y = sprite->y + k[11] * (tbl[i * 4 + 13] - sprite->y);
        break;
    default:
        sprite->x = sprite->x + k[11] * (tbl[i * 4 + 10] - sprite->x);
        sprite->y = sprite->y + k[11] * (tbl[i * 4 + 11] - sprite->y);
        break;
    }
}
#pragma force_active reset

#pragma force_active on
asm void lbl_0000B1C0(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_0000B1C0.s"
}
#pragma peephole on
asm void lbl_0000B920(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_0000B920.s"
}
#pragma peephole on
void lbl_0000BEE8(struct Sprite *sprite)
{
    NLsprarg sp;
    u8 *k = lbl_00011CB0;
    int i;
    int slot;
    int color;
    int sel;
    int shade;
    int floors;
    int hit;
    f32 px;
    f32 py;
    u8 *rec2;

    i = *(s32 *)lbl_802F1FAC < *(s32 *)lbl_802F1FB0 - 1 ? *(s32 *)lbl_802F1FAC : *(s32 *)lbl_802F1FB0 - 1;
    *(u8 **)lbl_802F1FB4 = lbl_8027CE24 + i * 8;
    lbl_0000A870(sprite);

    sp.zm_x = sprite->scaleX;
    sp.zm_y = sprite->scaleY;
    sp.u0 = *(f32 *)(k + 8);
    sp.v0 = *(f32 *)(k + 8);
    sp.u1 = *(f32 *)(k + 0xC);
    sp.v1 = *(f32 *)(k + 0xC);
    sp.ang = sprite->rotation;
    sp.trnsl = sprite->opacity;
    sp.listType = -1;
    sp.attr = (sprite->flags & ~0xF) | 0xA;

    for (i = 0; i <= 2; i++)
    {
        u32 rf = *(u32 *)(*(u8 **)lbl_802F1FB4 + 4);

        slot = i;
        if (rf & 8)
            slot += 3;
        if (rf & 0x10)
            slot = 6;
        if (sprite->userVar == 1 || i != *(s16 *)(*(u8 **)lbl_802F1FB4 + 2))
        {
            color = 0xC0C0C0;
            sel = -1;
        }
        else
        {
            color = 0xFFFFFF;
            sel = *(s16 *)(*(u8 **)lbl_802F1FB4 + 2);
        }
        sp.sprno = ((s32 *)(k + 0x100))[slot];
        sp.x = (sprite->x - *(f32 *)(k + 0x16C)) + *(f32 *)(k + slot * 8 + 0xB8);
        sp.y = (sprite->y - *(f32 *)(k + 0x170)) + *(f32 *)(k + slot * 8 + 0xBC);
        sp.z = sprite->depth
             + (sel == i ? *(f64 *)(k + 0x178) : *(f64 *)(k + 0x180));
        sp.base_color =
            ((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | (color | color);
        sp.offset_color = 0;
        nlSprPut(&sp);

        if (sprite->userVar == 1
            || i != *(s16 *)(*(u8 **)lbl_802F1FB4 + 2))
            color = 0x404040;
        else
            color = 0xFFFFFF;
        sp.sprno = ((s32 *)(k + 0x148))[slot];
        sp.x = sp.x + *(f32 *)(k + 0x188);
        if (i == 0 || i == 2 || slot >= 6)
            sp.y = sp.y - *(f32 *)(k + 0x188);
        else
            sp.y = sp.y + *(f32 *)(k + 0x188);
        sp.z = sp.z - *(f64 *)(k + 0x190);
        sp.base_color =
            ((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | (color | color);
        if (sprite->userVar == 2 && *(s32 *)lbl_802F1FA8 == 0
            && i == *(s16 *)(*(u8 **)lbl_802F1FB4 + 2))
            shade = (s32)(*(f64 *)(k + 0x198)
                          * (*(f64 *)(k + 0x30)
                             - __fabs(mathutil_sin(globalAnimTimer << 9))));
        else
            shade = 0;
        sp.offset_color = shade | ((shade << 16) | (shade << 8));
        nlSprPut(&sp);
    }

    *(u32 *)((u8 *)&modeCtrl + 8) &= ~0x18;
    rec2 = *(u8 **)lbl_802F1FB4;
    *(u32 *)((u8 *)&modeCtrl + 8) |= ((u32 *)rec2)[1];
    floors = course_floor_count(*(s16 *)(rec2 + 2), ((u32 *)rec2)[1]);
    *(u32 *)((u8 *)&modeCtrl + 8) &= ~*(u32 *)(*(u8 **)lbl_802F1FB4 + 4);

    reset_text_draw_settings();
    set_text_font(sprite->fontId);
    func_80071B1C(sprite->depth - *(f64 *)(k + 0x58));

    for (slot = 0; slot < 50; slot++)
    {
        hit = 0;
        if (sprite->userVar == 1 || slot > floors - 1
            || !is_floor_visited(*(s16 *)(*(u8 **)lbl_802F1FB4 + 2), slot + 1,
                                 *(s32 *)(*(u8 **)lbl_802F1FB4 + 4)))
        {
            set_text_mul_color(0x808000);
            set_text_opacity(*(f32 *)(k + 0x1A0));
        }
        else
        {
            set_text_mul_color(0xC0C000);
            set_text_opacity(*(f32 *)(k + 0xC));
        }

        if (sprite->userVar == 2 && *(s32 *)lbl_802F1FA8 == 2
            && slot == *(s16 *)(*(u8 **)lbl_802F1FB4) - 1)
        {
            shade = (s32)(*(f64 *)(k + 0xB0)
                          * __fabs(mathutil_sin(globalAnimTimer << 9)));
            hit = 1;
        }
        else
            shade = 0;
        set_text_add_color(shade | ((shade << 16) | (shade << 8)));

        px = *(f32 *)(k + 0x1A4) + (sprite->x - *(f32 *)(k + 0x16C))
           + (slot % 10) * 32;
        py = *(f32 *)(k + 0x1A4) + (sprite->y - *(f32 *)(k + 0x170))
           + (slot / 10) * 32;
        set_text_pos(px, py);
        sprite_printf((char *)lbl_00016484, slot + 1);
        set_text_add_color(0);
        set_text_mul_color(0x202000);
        set_text_pos(*(f32 *)(k + 0x70) + px, *(f32 *)(k + 0x70) + py);
        sprite_printf((char *)lbl_00016484, slot + 1);

        if (hit)
        {
            sp.sprno = 0x408;
            sp.x = *(f32 *)(k + 0x1A8) + px;
            sp.y = *(f32 *)(k + 0x1AC) + py;
            sp.z = sprite->depth - *(f64 *)(k + 0x1B0);
            sp.zm_x = *(f32 *)(k + 0x1B8);
            sp.zm_y = *(f32 *)(k + 0x1BC);
            sp.trnsl = sprite->opacity;
            sp.base_color =
                (((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | 0xFF00FF)
                | ((shade >> 1) + 0x80) * 256;
            sp.offset_color = 0;
            nlSprPut(&sp);
        }
    }
}
#pragma peephole on
static asm void lbl_0000C518(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_0000C518.s"
}
#pragma peephole on
asm void lbl_0000C970(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_0000C970.s"
}
#pragma peephole on
void lbl_0000D39C(s8 *alive, struct Sprite *sprite)
{
    struct SelNgcSlotPos *tbl = (struct SelNgcSlotPos *)lbl_00012730;
    u8 *k = lbl_00011CB0;

    sprite->x = sprite->x + *(f64 *)(k + 0x58) * (tbl[sprite->userVar + 13].x - sprite->x);
    switch (modeCtrl.gameType)
    {
    case 2:
        sprite->scaleY = *(f32 *)(k + 0x2C0);
        sprite->y = sprite->y + *(f64 *)(k + 0x58) * ((*(f32 *)(k + 0x2C4) + tbl[sprite->userVar + 13].y) - sprite->y);
        break;
    default:
        sprite->scaleY = *(f32 *)(k + 0xC);
        sprite->y = sprite->y + *(f64 *)(k + 0x58) * (tbl[sprite->userVar + 13].y - sprite->y);
        break;
    }

    switch (sprite->userVar)
    {
    case 2:
    case 3:
        if (sprite->counter > 0)
            sprite->counter--;
        break;
    default:
        if (sprite->counter < 9)
            sprite->counter++;
        break;
    }

    if (find_sprite_with_tag(0x21)->userVar == 0 && find_sprite_with_tag(0x22)->userVar == 0)
    {
        u8 *g = (u8 *)&lbl_801EEDA8;

        *(f32 *)(g + 0xF8) = (sprite->x - *(f64 *)(k + 0x2C8)) + ((f32 *)(k + 0x220))[sprite->counter];
        *(f32 *)(g + 0xFC) = ((f32 *)(k + 0x248))[sprite->counter];
        *(f32 *)(g + 0x100) = sprite->scaleX * ((f32 *)(k + 0x270))[sprite->counter];
        *(f32 *)(g + 0x104) = sprite->scaleY * ((f32 *)(k + 0x298))[sprite->counter];
        if (sprite->userVar == 3 && sprite->x > *(f32 *)(k + 0x2D0))
        {
            sprite->userVar = 0;
            sprite->counter = 9;
        }
    }
}
void lbl_0000D5A8(struct Sprite *sprite)
{
    u8 *k = (u8 *)lbl_00011CB0;
    NLsprarg sp;

    sp.u0 = *(f32 *)(k + 8);
    sp.v0 = *(f32 *)(k + 8);
    sp.u1 = *(f32 *)(k + 0xC);
    sp.v1 = *(f32 *)(k + 0xC);
    sp.trnsl = sprite->opacity;
    sp.listType = NLSPR_LISTTYPE_AUTO;
    sp.attr = (sprite->flags & ~0xF) | NLSPR_DISP_CC;
    sp.base_color = ((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | 0xFFFFFF;
    sp.offset_color = 0;
    sp.sprno = sprite->bmpId;
    sp.x = sprite->x;
    sp.y = sprite->y;
    sp.z = sprite->depth;
    sp.zm_x = sprite->scaleX;
    sp.zm_y = sprite->scaleY;
    sp.ang = sprite->rotation;
    nlSprPut(&sp);

    if (sprite->counter > 0)
    {
        sp.base_color = 0xFFFFFF;
        sp.offset_color = 0;
    }
    else if (is_load_queue_not_empty())
    {
        sp.base_color = 0;
        sp.offset_color = 0;
    }
    else if (sprite->counter == 0)
    {
        sp.base_color = 0;
        sp.offset_color = (backgroundInfo.backdropColor.r << 16)
                        | (backgroundInfo.backdropColor.g << 8)
                        | backgroundInfo.backdropColor.b;
    }

    sp.sprno = ((globalAnimTimer >> 2) & 1) ? 0x427 : 0x431;
    sp.x = sprite->x - *(f64 *)(k + 0x30);
    sp.y = sprite->y - *(f64 *)(k + 0x2D8);
    sp.z = sprite->depth - *(f64 *)(k + 0x2E0);
    sp.zm_x = sprite->scaleX * (sprite->x - *(f32 *)(lbl_00012798 + 0x10) < *(f64 *)(k + 0x2E8)
                                ? *(f64 *)(k + 0x2F0) : *(f64 *)(k + 0x2F8));
    sp.zm_y = *(f64 *)(k + 0x300) * sprite->scaleY;
    sp.ang = (globalAnimTimer & 2) << 14;
    nlSprPut(&sp);
}
// sprite mainFunc: ease the sprite towards the (x,y) slot userVar selects.
void lbl_0000D7C0(s8 *alive, struct Sprite *sprite)
{
    u8 *tbl = lbl_000127B8;
    u8 *k = lbl_00011D08;

    sprite->x = sprite->x
              + *(f64 *)k * (*(f32 *)(tbl + sprite->userVar * 8) - sprite->x);
    sprite->y = sprite->y
              + *(f64 *)k * (*(f32 *)(tbl + sprite->userVar * 8 + 4) - sprite->y);
}
// sprite drawFunc: the panel, then one row per save-file slot -- name, page
// number, selection pip, and a pulsing cursor on the active row.
void lbl_0000D82C(struct Sprite *sprite)
{
    u8 *tbl = lbl_00012730;
    u8 *k = lbl_00011CB0;
    NLsprarg sp;
    f32 hy;
    f32 bx;
    f32 by;
    f32 x;
    f64 ty;
    int pulse;
    int i;

    sp.u0 = *(f32 *)(k + 8);
    sp.v0 = *(f32 *)(k + 8);
    sp.u1 = *(f32 *)(k + 0xC);
    sp.v1 = *(f32 *)(k + 0xC);
    sp.trnsl = sprite->opacity;
    sp.listType = NLSPR_LISTTYPE_AUTO;
    sp.attr = (sprite->flags & ~0xF) | NLSPR_DISP_CC;
    sp.base_color = ((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | 0xFFFFFF;
    sp.offset_color = 0;
    sp.sprno = sprite->bmpId;
    sp.x = sprite->x;
    sp.y = sprite->y;
    sp.z = sprite->depth;
    sp.zm_x = sprite->scaleX;
    sp.zm_y = sprite->scaleY;
    sp.ang = sprite->rotation;
    nlSprPut(&sp);

    reset_text_draw_settings();

    bx = sprite->x - *(f32 *)(k + 0x308);
    by = sprite->y - *(f32 *)(k + 0x30C);
    pulse = *(f64 *)(k + 0x310) * __fabs(mathutil_sin(globalAnimTimer << 9));
    hy = *(f32 *)(k + 0x1F8) + by;

    for (i = 0; i < 5; i++)
    {
        *(u8 **)lbl_802F1FB4 = lbl_8027CE24 + i * 8;
        x = bx + i * 39;
        sp.base_color = ((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | 0xFFFFFF;
        set_text_font(0x37);
        set_text_mul_color((*(s16 *)(*(u8 **)lbl_802F1FB4 + 2) == 3
                            || i >= *(s32 *)lbl_802F1FB0) ? 0 : 0xFFFFFF);
        set_text_pos(x - *(f32 *)(k + 0x78), *(f32 *)(k + 0x318) + by);
        if (*(u32 *)(*(u8 **)lbl_802F1FB4 + 4) & 0x10)
            sprite_puts((char *)(tbl + 0x4134));
        else
            sprite_printf((char *)(tbl + 0x3CEC),
                          *(s16 *)(*(u8 **)lbl_802F1FB4 + 2) + 4);

        if (i >= *(s32 *)lbl_802F1FAC)
        {
            sp.sprno = 0x428;
            sp.x = x;
            sp.y = by;
            sp.z = sprite->depth - *(f64 *)(k + 0x190);
            sp.zm_x = *(f64 *)(k + 0x320) * sprite->scaleX;
            sp.zm_y = *(f64 *)(k + 0x328) * sprite->scaleY;
            sp.ang = (globalAnimTimer & 2) << 14;
            sp.base_color = (i >= *(s32 *)lbl_802F1FB0) ? 0 : 0xFFFFFF;
            nlSprPut(&sp);
        }

        if (i < *(s32 *)lbl_802F1FB0 && *(s16 *)(*(u8 **)lbl_802F1FB4 + 2) != 3)
        {
            func_80071B1C(sprite->depth - *(f64 *)(k + 0x190));
            set_text_mul_color(0xFFFF00);
            if ((*(u32 *)(*(u8 **)lbl_802F1FB4 + 4) & 8)
             && !(*(u32 *)(*(u8 **)lbl_802F1FB4 + 4) & 0x10))
            {
                set_text_font(0x34);
                set_text_pos(*(f32 *)(k + 0x70) + x, ty = (*(f32 *)(k + 0x78) + by) - *(f64 *)k);
                sprite_printf((char *)(tbl + 0x3D54), *(s16 *)*(u8 **)lbl_802F1FB4);
                set_text_pos(x - *(f32 *)(k + 0x188), ty);
                sprite_puts((char *)(tbl + 0x4138));
            }
            else
            {
                set_text_font(0x35);
                set_text_pos(x, (*(f32 *)(k + 0x78) + by) - *(f64 *)k);
                sprite_printf((char *)(tbl + 0x3D54), *(s16 *)*(u8 **)lbl_802F1FB4);
            }

            if (sprite->userVar != 0 && sprite->userVar != 1
             && i == *(s32 *)lbl_802F1FAC)
            {
                sp.base_color = (((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24)
                                 | 0xFF00FF) | pulse * 256;
                sp.sprno = 0x432;
                sp.x = *(f32 *)(k + 0xC) + x;
                sp.y = hy;
                sp.z = sprite->depth - *(f64 *)(k + 0x330);
                sp.zm_x = *(f32 *)(k + 0xC);
                sp.zm_y = *(f32 *)(k + 0xC);
                sp.ang = 0;
                nlSprPut(&sp);
            }
        }
    }
}
#pragma peephole on
// sprite mainFunc: ease towards the (x,y) slot userVar selects, then drive the
// shared preview transform while both neighbour sprites are idle.
void lbl_0000DCA4(s8 *alive, struct Sprite *sprite)
{
    u8 *k = lbl_00011CB0;

    sprite->x = sprite->x + *(f64 *)(k + 0x58) * (((struct SelNgcSlotPos *)lbl_000127D8)[sprite->userVar].x - sprite->x);
    sprite->y = sprite->y + *(f64 *)(k + 0x58) * (((struct SelNgcSlotPos *)lbl_000127D8)[sprite->userVar].y - sprite->y);

    if (find_sprite_with_tag(0x1B)->userVar == 0 && find_sprite_with_tag(0x22)->userVar == 0)
    {
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0xF8) = *(f32 *)(k + 0x338) + sprite->x;
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0xFC) = *(f32 *)(k + 0x33C);
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0x100) = sprite->userVar == 0 ? 0 : 0xC8;
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0x104) = *(f32 *)(k + 0x340);
        if (sprite->userVar == 3 && sprite->x > *(f32 *)(k + 0x344))
            sprite->userVar = 0;
    }
}
// sprite drawFunc: plain centred bitmap blit, colour scaled by opacity.
void lbl_0000DDF4(struct Sprite *sprite)
{
    u8 *tbl = lbl_00011CB0;
    NLsprarg sp;

    sp.u0 = *(f32 *)(tbl + 8);
    sp.v0 = *(f32 *)(tbl + 8);
    sp.u1 = *(f32 *)(tbl + 0xC);
    sp.v1 = *(f32 *)(tbl + 0xC);
    sp.trnsl = sprite->opacity;
    sp.listType = NLSPR_LISTTYPE_AUTO;
    sp.attr = (sprite->flags & ~0xF) | NLSPR_DISP_CC;
    sp.base_color = ((s32)(*(f32 *)(tbl + 0x10) * sprite->opacity) << 24) | 0xFFFFFF;
    sp.offset_color = 0;
    sp.sprno = sprite->bmpId;
    sp.x = sprite->x;
    sp.y = sprite->y;
    sp.z = sprite->depth;
    sp.zm_x = sprite->scaleX;
    sp.zm_y = sprite->scaleY;
    sp.ang = sprite->rotation;
    nlSprPut(&sp);
}
// sprite mainFunc: same easing as lbl_0000DCA4 for the other slot table.
void lbl_0000DEC8(s8 *alive, struct Sprite *sprite)
{
    u8 *k = lbl_00011CB0;

    sprite->x = sprite->x + *(f64 *)(k + 0x58) * (((struct SelNgcSlotPos *)lbl_000127F8)[sprite->userVar].x - sprite->x);
    sprite->y = sprite->y + *(f64 *)(k + 0x58) * (((struct SelNgcSlotPos *)lbl_000127F8)[sprite->userVar].y - sprite->y);

    if (find_sprite_with_tag(0x1B)->userVar == 0 && find_sprite_with_tag(0x21)->userVar == 0)
    {
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0xF8) =
            (sprite->x - *(f32 *)(k + 0x348)) + *(s8 *)(lbl_801EED98 + 0xA) * 0xB2;
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0xFC) = *(f32 *)(k + 0x34C);
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0x100) =
            (sprite->userVar == 0 || sprite->userVar == 1) ? 0 : 0xAC;
        *(f32 *)((u8 *)&lbl_801EEDA8 + 0x104) = *(f32 *)(k + 0x350);
        if (sprite->userVar == 3 && sprite->x < *(f32 *)(k + 0x354))
            sprite->userVar = 0;
    }
}
// sprite drawFunc: the panel, then one pip per slot, then a pulsing highlight
// on the slot the save-data cursor is sitting on.
void lbl_0000E068(struct Sprite *sprite)
{
    u8 *k = lbl_00011CB0;
    s8 *g = (s8 *)lbl_801EED98;
    NLsprarg sp;
    int pulse;
    int i;

    pulse = *(f64 *)(k + 0x310) * __fabs(mathutil_sin(globalAnimTimer << 9));

    sp.u0 = *(f32 *)(k + 8);
    sp.v0 = *(f32 *)(k + 8);
    sp.u1 = *(f32 *)(k + 0xC);
    sp.v1 = *(f32 *)(k + 0xC);
    sp.trnsl = sprite->opacity;
    sp.listType = NLSPR_LISTTYPE_AUTO;
    sp.attr = (sprite->flags & ~0xF) | NLSPR_DISP_CC;
    sp.base_color = ((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | 0xFFFFFF;
    sp.offset_color = 0;
    sp.sprno = sprite->bmpId;
    sp.x = sprite->x;
    sp.y = sprite->y;
    sp.z = sprite->depth;
    sp.zm_x = sprite->scaleX;
    sp.zm_y = sprite->scaleY;
    sp.ang = sprite->rotation;
    nlSprPut(&sp);

    for (i = 0; i < 3; i++)
    {
        sp.sprno = 0x428;
        sp.x = (*(f32 *)(k + 0x358) + sprite->x) + i * 66;
        sp.y = *(f32 *)(k + 0x208) + sprite->y;
        sp.z = sprite->depth - *(f64 *)(k + 0x360);
        sp.zm_x = *(f64 *)(k + 0x368) * sprite->scaleX;
        sp.zm_y = *(f64 *)(k + 0x370) * sprite->scaleY;
        sp.ang = (globalAnimTimer & 2) << 14;
        sp.base_color = (g[4] == 1 && i > 0) ? 0 : 0xFFFFFF;
        nlSprPut(&sp);

        if (sprite->userVar != 0 && sprite->userVar != 1
         && g[9] == i
         && !(g[4] == 1 && i > 0))
        {
            sp.sprno = 0x432;
            sp.x = *(f32 *)(k + 0x188) + ((*(f32 *)(k + 0x358) + sprite->x) + i * 66);
            sp.y = *(f32 *)(k + 0x188) + (*(f32 *)(k + 0x208) + sprite->y);
            sp.z = sprite->depth - *(f64 *)(k + 0x2E0);
            sp.zm_x = *(f64 *)(k + 0x378) * sprite->scaleX;
            sp.zm_y = (f64)sprite->scaleY;
            sp.ang = 0;
            sp.base_color = (((s32)(*(f32 *)(k + 0x10) * sprite->opacity) << 24) | 0xFF00FF) | (pulse & 0xFF) * 256;
            nlSprPut(&sp);
        }
    }
}
// sprite mainFunc: track the tag-0x1B sprite, offset by a mode-dependent gap.
void lbl_0000E368(s8 *alive, struct Sprite *sprite)
{
    struct Sprite *s = find_sprite_with_tag(0x1B);

    if (s != NULL)
    {
        sprite->userVar = (s->userVar == 2 && *(s32 *)u_isCompetitionModeCourse == 0) ? 1 : 0;
        sprite->x = *(f32 *)lbl_00011D44 + s->x;
        sprite->y = s->y + (modeCtrl.gameType == 1 ? 0x2C : 0x42);
    }
}
// sprite mainFunc: park this sprite at a fixed offset from sprite tag 0x21.
void lbl_0000E43C(s8 *alive, struct Sprite *sprite)
{
    struct Sprite *anchor = find_sprite_with_tag(0x21);

    if (anchor != NULL)
    {
        sprite->userVar = (*(s32 *)&lbl_801EEDA8 == 0x1F) ? 1 : 0;
        sprite->x = *(f32 *)lbl_00012030 + anchor->x;
        sprite->y = *(f32 *)lbl_00012034 + anchor->y;
    }
}
// sprite mainFunc: park this sprite at a fixed offset from sprite tag 0x22.
void lbl_0000E4BC(s8 *alive, struct Sprite *sprite)
{
    struct Sprite *anchor = find_sprite_with_tag(0x22);

    if (anchor != NULL)
    {
        sprite->userVar = (*(s32 *)&lbl_801EEDA8 == 0x24) ? 1 : 0;
        sprite->x = anchor->x - *(f32 *)lbl_00012038;
        sprite->y = *(f32 *)lbl_0001203C + anchor->y;
    }
}
// sprite drawFunc: drop-shadowed caption drawn twice (black then white).
void lbl_0000E540(struct Sprite *sprite)
{
    u8 *tbl = lbl_00011CB0;

    if (sprite->userVar == 0)
        return;

    reset_text_draw_settings();
    func_80071B50(0x220000);
    set_text_font(sprite->fontId);
    set_text_scale(*(f32 *)(tbl + 0x40), *(f32 *)(tbl + 0x40));
    func_80071B1C(*(f64 *)(tbl + 0x190) + sprite->depth);
    set_text_pos(*(f32 *)(tbl + 0x70) + (sprite->x - *(f32 *)(tbl + 0x390)),
                 *(f32 *)(tbl + 0x70) + sprite->y);
    set_text_mul_color(0x000000);
    sprite_puts((char *)lbl_00016440);
    func_80071B1C(sprite->depth);
    set_text_pos(sprite->x - *(f32 *)(tbl + 0x390), sprite->y);
    set_text_mul_color(0xFFFFFF);
    sprite_puts((char *)lbl_00016420);
}
// sprite drawFunc: three overlapping bitmaps making up one wide banner.
void lbl_0000E620(struct Sprite *sprite)
{
    f32 *tbl = (f32 *)lbl_00011CB0;
    NLsprarg sp;

    sp.z = sprite->depth;
    sp.ang = sprite->rotation;
    sp.u0 = tbl[2];
    sp.v0 = tbl[2];
    sp.u1 = tbl[3];
    sp.v1 = tbl[3];
    sp.zm_x = sprite->scaleX;
    sp.zm_y = sprite->scaleY;
    sp.trnsl = sprite->opacity;
    sp.listType = NLSPR_LISTTYPE_AUTO;
    sp.attr = (sprite->flags & ~0xF) | NLSPR_DISP_CC;
    sp.base_color = ((s32)(tbl[4] * sprite->opacity) << 24) | 0xFFFFFF;
    sp.offset_color = 0;
    sp.sprno = 0x436;
    sp.x = sprite->x - tbl[0xE5];
    sp.y = sprite->y - tbl[0xE6];
    nlSprPut(&sp);
    sp.sprno = 0x434;
    sp.x = sprite->x - tbl[0xE7];
    sp.y = sprite->y - tbl[0xE6];
    nlSprPut(&sp);
    sp.sprno = 0x438;
    sp.x = sprite->x - tbl[0xE8];
    sp.y = sprite->y - tbl[0xE6];
    nlSprPut(&sp);
}
asm void lbl_0000E778(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_0000E778.s"
}
#pragma peephole on
// build one of the numbered selection sprites.
void lbl_0000EBD4(int index)
{
    u8 *tbl = lbl_00012730;
    u8 *k = lbl_00011CB0;
    struct Sprite *sprite;

    sprite = create_sprite();
    if (sprite != NULL)
    {
        u8 *pos = tbl + index * 8;

        sprite->tag = index + 0x32;
        sprite->type = 1;
        sprite->x = *(f32 *)(pos + 0x432C);
        sprite->y = *(f32 *)(pos + 0x4330);
        sprite->depth = *(f32 *)(k + 0x3B4);
        sprite->textAlign = 0;
        sprite->scaleX = *(f32 *)(k + 8);
        sprite->scaleY = *(f32 *)(k + 8);
        sprite->opacity = *(f32 *)(k + 8);
        sprite->userVar = 6;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000ECB0;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_0000F788;
        sprite->bmpId = index;
        sprintf(sprite->text, (char *)(tbl + 0x43FC), index);
    }
}
asm void lbl_0000ECB0(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_0000ECB0.s"
}
#pragma peephole on
asm void lbl_0000F788(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_0000F788.s"
}
#pragma peephole on
// build the mode banner sprite, then the four numbered course-slot sprites.
void lbl_0000FE0C(void)
{
    u8 *tbl = lbl_00012730;
    u8 *k = lbl_00011CB0;
    int i;
    struct Sprite *sprite;

    sprite = create_sprite();
    if (sprite != NULL)
    {
        sprite->tag = 0x1D;
        sprite->type = 1;
        sprite->x = *(f32 *)(k + 0x14);
        sprite->y = *(f32 *)(k + 0x410);
        sprite->depth = *(f32 *)(k + 0x3B4);
        sprite->textAlign = 4;
        sprite->opacity = *(f32 *)(k + 8);
        sprite->userVar = 0;
        sprite->counter = 0xF;
        sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_0000FF7C;
        sprite->drawFunc = (void (*)(struct Sprite *))lbl_00010438;
        strcpy(sprite->text, (char *)(tbl + 0x4900));
        lbl_00010214(sprite);
    }

    for (i = 0; i < 4; i++)
    {
        sprite = create_sprite();
        if (sprite != NULL)
        {
            sprite->type = 1;
            sprite->bmpId = ((s32 *)(tbl + 0x48F0))[i];
            sprite->x = i * 0xA0 + 0x50;
            sprite->y = *(f32 *)(k + 0x74);
            sprite->depth = *(f32 *)(k + 0x390);
            sprite->textAlign = 4;
            sprite->flags |= 0x40000;
            sprite->opacity = *(f32 *)(k + 8);
            sprite->userVar = 0;
            sprite->counter = 0xF;
            sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_000101BC;
            sprintf(sprite->text, (char *)(tbl + 0x490C), i);
        }
    }
}
// sprite mainFunc: fade the banner in, settling the four course-slot bars
// towards their rest height; then fade out and kill the sprite.
void lbl_0000FF7C(s8 *alive, struct Sprite *sprite)
{
    u8 *k = lbl_00011CB0;
    int i;

    if (sprite->counter > 0)
        sprite->counter--;

    switch (sprite->userVar)
    {
    case 0:
        sprite->opacity = *(f32 *)(k + 0xC) - sprite->counter / *(f32 *)(k + 0xA8);
        for (i = 0; i < 4; i++)
        {
            f32 *g = (f32 *)(lbl_100009D8 + i * 0x10);
            f64 v = *(f64 *)(k + 0x30) - *(f64 *)(k + 0x418) * __fabs(g[0] - g[1]);

            g[2] = v < *(f64 *)(k + 0x98)
                 ? *(f64 *)(k + 0x98)
                 : (v > *(f64 *)(k + 0x30) ? *(f64 *)(k + 0x30) : v);
            g[1] = g[0];
        }
        break;
    case 1:
        sprite->counter = 0xF;
        sprite->userVar = 2;
    case 2:
        sprite->opacity = sprite->counter / *(f32 *)(k + 0xA8);
        if (sprite->counter == 0)
            *alive = 0;
        break;
    }
}
#pragma peephole on
// sprite mainFunc: track the opacity of sprite tag 0x1D, and kill this sprite
// once that one is gone.
void lbl_000101BC(s8 *alive, struct Sprite *sprite)
{
    struct Sprite *other = find_sprite_with_tag(0x1D);

    if (other == NULL)
        *alive = 0;
    else
        sprite->opacity = other->opacity;
}
asm void lbl_00010214(struct Sprite *sprite)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_00010214.s"
}
#pragma peephole on
asm void lbl_00010438(void)
{
    nofralloc
#include "../asm/nonmatchings/sel_ngc_rel/lbl_00010438.s"
}
#pragma peephole on
// build the three mode-select bitmaps down the right-hand column.
void lbl_00011330(void)
{
    u8 *tbl = lbl_00011CB0;
    struct Sprite *sprite;
    int i;

    for (i = 0; i < 3; i++)
    {
        sprite = create_sprite();
        if (sprite != NULL)
        {
            sprite->tag = i + 5;
            sprite->type = 1;
            sprite->bmpId = ((u32 *)(tbl + 0x440))[i];
            sprite->x = *((f32 **)lbl_00017460)[i];
            sprite->y = *(f32 *)(tbl + 0x494);
            sprite->depth = *(f64 *)tbl + *(f64 *)(tbl + 0x190) * i;
            sprite->textAlign = 4;
            sprite->userVar = 1;
            sprite->mainFunc = (void (*)(s8 *, struct Sprite *))lbl_00011424;
            sprintf(sprite->text, (char *)lbl_0001746C, i);
        }
    }
}
#pragma peephole on
#pragma force_active reset
