/*
 * test_mode.c -- REL module: isolated function lbl_0000E3E8.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <dolphin.h>
#include "stddef.h"
#include "stdio.h"
#include "stdlib.h"
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "pool.h"
#include "rend_efc.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "pause_menu.h"
#include "string.h"
#include "avdisp.h"
#include "background.h"
#include "obj_collision.h"
#include "ord_tbl.h"
#include "stcoli.h"
#include "preview.h"
#include "recplay.h"
#include "gxcache.h"
#include "memcard.h"
#include "ranking_screen.h"
#include "vibration.h"
#include "gxutil.h"
#include "perf.h"
#include "course.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/test_mode.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000FE78[];
extern u8 lbl_0000FEC8[];
extern u8 lbl_0000FED0[];
extern u8 lbl_0000FF00[];
extern u8 lbl_0000FF78[];
extern u8 lbl_00010070[];
extern u8 lbl_00010078[];
extern u8 lbl_00010080[];
extern u8 lbl_000100A8[];
extern u8 lbl_000100D8[];
extern u8 lbl_00010118[];
extern u8 lbl_00010124[];
extern u8 lbl_00010148[];
extern u8 lbl_00010150[];
extern u8 lbl_00010170[];
extern u8 lbl_000101B8[];
extern u8 lbl_000101E0[];
extern u8 lbl_000101EC[];
extern u8 lbl_000101FC[];
extern u8 lbl_00010278[];
extern u8 lbl_00010280[];
extern u8 lbl_00010298[];
extern u8 lbl_000102B0[];
extern u8 lbl_00010350[];
extern u8 lbl_00010364[];
extern u8 lbl_000103F4[];
extern u8 lbl_000106B4[];
extern u8 lbl_000109A8[];
extern u8 lbl_00010BEC[];
extern u8 lbl_00012330[];
extern u8 lbl_00012C10[];
extern u8 lbl_00012F7C[];
extern u8 lbl_00013158[];
extern u8 lbl_00013178[];
extern u8 lbl_0001323C[];
extern u8 lbl_0001324C[];
extern u8 lbl_000138AC[];
extern u8 lbl_000138B8[];
extern u8 lbl_00013920[];
extern u8 lbl_00013A1C[];
extern u8 lbl_00014638[];
extern u8 lbl_0001468C[];
extern u8 lbl_0001469C[];
extern u8 lbl_00014714[];
extern u8 lbl_000147EC[];
extern u8 lbl_00014810[];
extern u8 lbl_000148A8[];
extern u8 lbl_000148D8[];
extern u8 lbl_000148E8[];
extern u8 lbl_00014974[];
extern u8 lbl_000155BC[];
extern u8 lbl_000156F0[];
extern u8 lbl_00015868[];
extern u8 lbl_00015890[];
extern u8 lbl_000159EC[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000008[];
extern u8 lbl_10000040[];
extern u8 lbl_1000006C[];
extern u8 lbl_100000B4[];
extern u8 lbl_100000B8[];
extern u8 lbl_10000D5C[];
extern u8 lbl_10000D60[];
extern u8 lbl_10000D64[];
extern u8 lbl_10000E00[];
extern u8 lbl_10000F38[];
extern u8 lbl_10000F58[];
extern u8 lbl_10000F5C[];
extern u8 lbl_10000F60[];
extern u8 lbl_10000F70[];
extern u8 lbl_10000FA8[];
extern u8 lbl_10000FAC[];
extern u8 lbl_10003BAC[];
extern u8 lbl_10003BF8[];
extern u8 lbl_10003BFC[];
extern u8 lbl_10003C60[];
extern u8 lbl_10003C80[];
extern u8 bgTypeNames[];
extern u8 dipSwitchNames[];
extern u8 lbl_801C6420[];
extern u8 lbl_801C6470[];
extern u8 lbl_802F0980[];
extern u8 lbl_802F2130[];
extern u8 s_loadedSoundGroupIDs[];
extern u8 spriteTileOffsets[];
extern u8 u_isSoundGroupDataLoaded[];

// Imported functions the code calls that no included header declares.
extern void GXDrawCube();
extern void GXDrawCylinder();
extern void GXPixModeSync();
extern void PSMTXConcat();
extern void PSMTXCopy();
extern void PSMTXInverse();
extern void avdisp_get_eff_vertices();
extern void avdisp_get_eff_vtxinfo();
extern void avdisp_get_matrices();
extern void draw_test_camera_target();
extern void effect_draw();
extern void free_model();
extern void func_80036000();
extern void func_80086D20();
extern void func_8008B9DC();
extern void func_8008BFD8();
extern int func_800948EC();
extern void func_800A71B0();
extern void *func_800A722C();
extern void func_800A7314();
extern void func_800A7370();
extern void func_800A7440();
extern void get_font_bitmap_id();
extern void item_draw();
extern void load_model();
extern void mot_ape_8008BAA8();
extern void nl2ngc_draw_model_sort_translucent_alt2();
extern void nlObjModelListFree();
extern void nlObjModelListLoad();
extern void nlObjPut();
extern void set_shape_flags_in_model();
extern void stobj_draw();
extern void u_draw_ball_shadow();
extern void u_load_character_graphics();
extern void u_make_ape_sub();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_00000208(void);
void lbl_00000270(void);
void lbl_00000630(void);
void lbl_00000780(void);
void lbl_00000934(void);
void lbl_00001B78(void);
void lbl_00002108(void);
void lbl_0000215C(void);
void lbl_00002760(void);
void lbl_000031B8(void);
void lbl_00003A4C(void);
void lbl_00003C34(void);
void lbl_00003D94(void);
void lbl_000040B4(void);
void lbl_0000502C(void);
void lbl_00005384(void);
void lbl_000055E8(void);
void lbl_000056BC(void);
void lbl_000057C0(void);
void lbl_000065F0(void);
void lbl_00006974(void);
void lbl_000073EC(void);
void lbl_00007BE0(void);
void lbl_00007D20(void);
void lbl_00007FE8(void);
void lbl_00008008(void);
void lbl_00008808(void);
void lbl_0000884C(void);
void lbl_00008ADC(void);
void lbl_00008B00(void);
void lbl_00008B44(void);
void lbl_00008F40(void);
void lbl_00009060(void);
void lbl_00009338(void);
void lbl_000094C0(void);
void lbl_00009560(void);
void lbl_000095F8(void);
void lbl_00009998(void);
void lbl_00009A0C(void);
void lbl_0000A304(void);
void lbl_0000A440(void);
void lbl_0000A78C(void);
void lbl_0000A7DC(void);
void lbl_0000A7E0(void);
void lbl_0000A7E4(void);
void lbl_0000A7FC(void);
void lbl_0000AD30(void);
void lbl_0000ADEC(void);
void lbl_0000ADF0(void);
void lbl_0000AE7C(void);
void lbl_0000AEB8(void);
void lbl_0000AEDC(void);
void lbl_0000B364(void);
void lbl_0000B44C(void);
void lbl_0000B4A0(void);
void lbl_0000B57C(void);
void lbl_0000B6B0(void);
void lbl_0000BE00(void);
void lbl_0000BE94(void);
void lbl_0000BE98(void);
void lbl_0000BEB8(void);
void lbl_0000BFA0(void);
void lbl_0000BFE8(void);
void lbl_0000C00C(void);
void lbl_0000C0B0(void);
void lbl_0000C1B8(void);
void lbl_0000C240(void);
void lbl_0000C260(void);
void lbl_0000C3F0(void);
void lbl_0000C984(void);
void lbl_0000CB0C(void);
void lbl_0000CB10(void);
void lbl_0000CDE0(void);
int lbl_0000D084(void);
void lbl_0000D3C0(void);
void lbl_0000D844(void);
void lbl_0000D9FC(void);
void lbl_0000DB2C(void);
void lbl_0000DC60(char *, char *, ...);
void lbl_0000DDA4();
void lbl_0000E2E8(void);
void lbl_0000E3E8(void);
void lbl_0000E628(void);
void lbl_0000ECB4(void);
void lbl_0000EEF4(void);
void lbl_0000F6F0(void);
void lbl_0000F7BC(void);
void lbl_0000F940(void);
static inline int u_take(u8 *p) { s32 t = *(s32 *)(p + 0x54); *(s32 *)(p + 0x54) = 0; return t; } s32 lbl_0000FBA8(void);
void lbl_0000FD8C(void);


struct TestE3Work
{
    u8 filler0[0x4];
    /*0x04*/ struct Ape *ape;
    u8 filler8[0xC0-0x08];
    /*0xC0*/ struct Struct80089CBC *unkC0;
};

struct TestE3Ids
{
    s32 v[8];
};

// Carried over from the heads of the absorbed files (merged by
// tools/rel_merge_tu.py -- these are what the tool used to drop).
static void lbl_0000F498(int a);
static void lbl_0000F4D8(int arg);

#pragma force_active on
void lbl_0000E3E8(void)
{
    u8 *P = lbl_000101E0;
    struct TestE3Work *w = (struct TestE3Work *)lbl_10003BF8;
    struct Struct80089CBC *e = w->unkC0;

    mathutil_mtxA_push();
    mathutil_mtxA_from_identity();
    mathutil_mtxA_translate_xyz(*(f32 *)(P + 0xC), *(f32 *)(P + 0x7C),
                                *(f32 *)(P + 0x80));
    switch (e->unk0)
    {
    case 0:
    case 1:
    case 4:
    case 5:
    case 6:
        mathutil_mtxA_rotate_z(-16384);
        mathutil_mtxA_rotate_y(-16384);
        mathutil_mtxA_scale_s(*(f32 *)(P + 0x84));
        gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
        func_80086D20(w->ape, e->unk0, e->unk8);
        break;
    case 2:
    case 3:
        window_set_cursor_pos(15, 20);
        window_printf_2((char *)lbl_00015868);
        break;
    case 7:
    {
        struct TestE3Ids t;
        struct GMAModelEntry *ents;
        int i;
        int m;

        mathutil_mtxA_translate_xyz(*(f32 *)(P + 0xC), *(f32 *)(P + 0x88),
                                    *(f32 *)(P + 0xC));
        mathutil_mtxA_rotate_z(-16384);
        mathutil_mtxA_rotate_y(-16384);
        mathutil_mtxA_rotate_z((s16)(*(f32 *)(P + 0x8C) * (s32)e->unk8));
        mathutil_mtxA_scale_s(*(f32 *)(P + 0x84));
        window_set_cursor_pos(15, 18);
        window_printf_2((char *)lbl_00015890, e->unk8);
        t = *(struct TestE3Ids *)(P + 0x5C);
        ents = charaGMAs[w->ape->charaId * 2]->modelEntries;
        i = w->ape->charaId << 1;
        if (w->unkC0->unk10 == 4)
        {
            i++;
            mathutil_mtxA_translate_xyz(*(f32 *)(P + 0xC), *(f32 *)(P + 0x90),
                                        *(f32 *)(P + 0xC));
        }
        else
        {
            mathutil_mtxA_translate_xyz(*(f32 *)(P + 0xC), *(f32 *)(P + 0x94),
                                        *(f32 *)(P + 0xC));
        }
        m = t.v[i];
        gxutil_load_pos_nrm_matrix(mathutilData->mtxA, 0);
        avdisp_draw_model_unculled_sort_none(ents[m].model);
        break;
    }
    }
    mathutil_mtxA_pop();
}
asm void lbl_0000E628(void)
{
    nofralloc
#include "../asm/nonmatchings/test_mode/lbl_0000E628.s"
}
#pragma peephole on
void lbl_0000ECB4(void)
{
    u8 *q = lbl_000148E8;
    u8 *p = lbl_10003BF8;
    int z0;
    int z1;
    int z2;
    int z3;
    int z4;

    window_set_cursor_pos(4, 7);
    window_printf_2((char *)(q + 0xFC4));
    window_set_cursor_pos(1, 8);
    lbl_0000DC60((char *)(q + 0xFDC), (char *)(q + 0xF0C),
                 ((u32 *)(q + 0x8C))[*(int *)(p + 0xA8)]);
    lbl_0000DC60((char *)(q + 0xFF0), (char *)(q + 0xF0C),
                 ((char **)((u8 **)(q + 0xCD4))[*(int *)(p + 0xA8)])[((s32 *)(p + 0x10))[*(int *)(p + 0xA8)]]);
    lbl_0000DC60((char *)(q + 0x1004), (char *)(q + 0xF0C),
                 motLabel[(*(struct SomeMotInfoStruct **)(p + 0xAC))->animId]);
    lbl_0000DC60((char *)(q + 0x1018), (char *)(q + 0x102C), (*(struct SomeMotInfoStruct **)(p + 0xAC))->unk0);
    lbl_0000DC60((char *)(q + 0x1034), (char *)(q + 0xEFC), (*(struct SomeMotInfoStruct **)(p + 0xAC))->unk4);
    lbl_0000DC60((char *)(q + 0x1048), (char *)(q + 0xEFC), (*(struct SomeMotInfoStruct **)(p + 0xAC))->unk8);
    lbl_0000DC60((char *)(q + 0x105C), (char *)(q + 0xEFC), (*(struct SomeMotInfoStruct **)(p + 0xAC))->unk14);
    lbl_0000DC60((char *)(q + 0x1070), (char *)(q + 0x1084), (*(struct SomeMotInfoStruct **)(p + 0xAC))->u_maybeSpeed);
    lbl_0000DC60((char *)(q + 0x108C), (char *)(q + 0xF0C),
                 ((*(struct SomeMotInfoStruct **)(p + 0xAC))->unkC & 0x1) ? (char *)(q + 0xEA4) : (char *)(q + 0xEA8));
    lbl_0000DC60((char *)(q + 0x10A0), (char *)(q + 0xF0C),
                 ((*(struct SomeMotInfoStruct **)(p + 0xAC))->unkC & 0x2) ? (char *)(q + 0xEA4) : (char *)(q + 0xEA8));
    lbl_0000DC60((char *)(q + 0x10B4), (char *)(q + 0xF0C),
                 ((*(struct SomeMotInfoStruct **)(p + 0xAC))->unkC & 0x4) ? (char *)(q + 0xEA4) : (char *)(q + 0xEA8));
    lbl_0000DC60((char *)(q + 0x10C8), (char *)(q + 0xF0C),
                 ((*(struct SomeMotInfoStruct **)(p + 0xAC))->unkC & 0x8) ? (char *)(q + 0xEA4) : (char *)(q + 0xEA8));
    lbl_0000DC60((char *)(q + 0x10DC), (char *)(q + 0xF0C),
                 ((*(struct SomeMotInfoStruct **)(p + 0xAC))->unkC & 0x10) ? (char *)(q + 0xEA4) : (char *)(q + 0xEA8));
    lbl_0000DC60((char *)(q + 0x10F0), (char *)(q + 0x1100));
}
asm void lbl_0000EEF4(void)
{
    nofralloc
#include "../asm/nonmatchings/test_mode/lbl_0000EEF4.s"
}
#pragma peephole on
void lbl_0000F470(int enable)
{
    if (*(void **)lbl_10003C80 != NULL)
        return;
    if (enable == 0)
        return;
    *(void **)lbl_10003C80 = (void *)lbl_0000EEF4;
}
static void lbl_0000F498(int a)
{
    if (a != 0)
    {
        thread_kill(*(int *)lbl_10003BF8);
        *(int *)lbl_10003C60 = 0;
    }
}
static void lbl_0000F4D8(int arg)
{
    u8 *d = lbl_000148E8;
    void *h;
    char name[128];

    if (arg == 0)
        return;
    if (func_800948EC() == 0)
        return;
    func_800A71B0((char *)(d + 0x113C), name);
    if (strcmp(name, (char *)(d + 0x1144)) == 0)
    {
        char path[64];
        OSCalendarTime ct;
        void *buf;

        buf = OSAllocFromHeap(__OSCurrHeap, 0x4E000);
        OSTicksToCalendarTime(OSGetTime(), &ct);
        sprintf(path, (char *)(d + 0x114C), ct.mon + 1, ct.mday, ct.hour, ct.min,
                ct.sec);
        h = func_800A722C((char *)(d + 0x1174), 1);
        func_800A7370(h, buf, 0x4E000);
        func_800A7314(h);
        h = func_800A722C(path, 2);
        func_800A7440(h, buf, 0x4E000);
        func_800A7314(h);
        OSFreeToHeap(__OSCurrHeap, buf);
        h = func_800A722C((char *)(d + 0x118C), 2);
    }
    else if (strcmp(name, (char *)(d + 0x11A0)) == 0)
    {
        char path[64];
        OSCalendarTime ct;
        void *buf;

        buf = OSAllocFromHeap(__OSCurrHeap, 0x4E000);
        OSTicksToCalendarTime(OSGetTime(), &ct);
        sprintf(path, (char *)(d + 0x11AC), ct.year, ct.mon + 1, ct.mday, ct.hour,
                ct.min, ct.sec);
        h = func_800A722C((char *)(d + 0x11E0), 1);
        func_800A7370(h, buf, 0x4E000);
        func_800A7314(h);
        h = func_800A722C(path, 2);
        func_800A7440(h, buf, 0x4E000);
        func_800A7314(h);
        OSFreeToHeap(__OSCurrHeap, buf);
        h = func_800A722C((char *)(d + 0x11E0), 2);
    }
    else
    {
        h = func_800A722C((char *)(d + 0x1200), 2);
    }
    func_800A7440(h, motInfo, 0x4E000);
    func_800A7314(h);
}
asm void lbl_0000F6F0(void)
{
    nofralloc
#include "../asm/nonmatchings/test_mode/lbl_0000F6F0.s"
}
struct TestMotWork
{
    /*0x00*/ u8 filler0[4];
    /*0x04*/ struct Ape *ape;
    /*0x08*/ float unk8;
    /*0x0C*/ u8 fillerC[4];
    /*0x10*/ s32 unk10[23];
    /*0x6C*/ s32 charaId;
    /*0x70*/ u8 filler70[0xA8 - 0x70];
    /*0xA8*/ s32 unkA8;
    /*0xAC*/ struct SomeMotInfoStruct *unkAC;
};

#pragma peephole on
void lbl_0000F7BC(void)
{
    struct TestMotWork *w = (struct TestMotWork *)lbl_10003BF8;
    s32 animGroup;
    s32 frame;
    s32 b;
    s32 f;

    b = w->unkA8;
    if (b == 7 && (f = w->unk10[b]) >= (s32)((struct MotInfo *)&motInfo[w->charaId])->unk70[b])
    {
        animGroup = b;
        frame = f;
        mot_ape_8008BAA8(&animGroup, &frame);
        w->unkAC = (struct SomeMotInfoStruct *)((struct MotInfo *)&motInfo[w->charaId])->unk30[animGroup] + frame;
    }
    else
    {
        w->unkAC = (struct SomeMotInfoStruct *)((struct MotInfo *)&motInfo[w->charaId])->unk30[w->unkA8]
                   + w->unk10[w->unkA8];
    }
    if (w->unkAC != w->ape->unk1C || w->unkAC->animId != w->ape->unk0->u_animId)
    {
        w->ape->unk1C = w->unkAC;
        if (w->unkAC->animId > u_motAnimCount)
            w->unkAC->animId = 1;
        w->ape->unk28 = w->unkA8;
        w->ape->unkB0 = w->unk10[w->unkA8];
        func_8008B9DC(w->ape, w->unkAC->animId);
        w->unk8 = w->unkAC->u_maybeSpeed;
    }
}
asm void lbl_0000F940(void)
{
    nofralloc
#include "../asm/nonmatchings/test_mode/lbl_0000F940.s"
}
#pragma peephole on
#pragma opt_propagation off
s32 lbl_0000FBA8(void)
{
    u8 *p = lbl_10003BF8;
    void (*fn)(s32);
    s32 ok;
    u16 press = controllerInfo[0].pressed.button;
    u16 hold;
    s32 pad[4];

    *(s32 *)(p + 0x54) = press & PAD_BUTTON_A;
    *(s32 *)(p + 0x58) = press & PAD_BUTTON_B;
    hold = controllerInfo[0].held.button;
    *(s32 *)(p + 0x5C) = hold & PAD_BUTTON_Y;
    *(s32 *)(p + 0x60) = hold & PAD_BUTTON_X;
    lbl_0000D844();
    mathutil_mtxA_from_identity();
    *(float *)(p + 0xC) = *(float *)(p + 0xC) + controllerInfo[0].held.substickX * 10;
    mathutil_mtxA_rotate_y(*(float *)(p + 0xC));
    mathutil_mtxA_to_quat(&(*(struct Ape **)(p + 4))->unk60);
    (*(struct Ape **)(p + 4))->unk0->u_someDeltaTime =
        (*(struct SomeMotInfoStruct **)(p + 0xAC))->u_maybeSpeed;
    *(s32 *)(p + 0x9C) = 3;
    *(s32 *)(p + 0xA0) = 2;
    if (*(void **)(p + 0x88) != NULL)
        (*(void (**)(void))(p + 0x88))();
    else
        *(s32 *)(p + 0x78) = 0;
    lbl_0000D3C0();
    if (controllerInfo[0].pressed.button & PAD_BUTTON_LEFT)
    {
        if (--(*(struct Ape **)(p + 4))->colorId < 0)
            (*(struct Ape **)(p + 4))->colorId = 3;
    }
    else if (controllerInfo[0].pressed.button & PAD_BUTTON_RIGHT)
    {
        if (++(*(struct Ape **)(p + 4))->colorId > 3)
            (*(struct Ape **)(p + 4))->colorId = 0;
    }
    ape_skel_anim_main(*(struct Ape **)(p + 4));
    fn = *(void (**)(s32))(lbl_000156F0 + *(s32 *)(p + 0x64) * 8);
    fn((ok = (fn != NULL && *(void **)(p + 0x88) == NULL)) &&
       u_take(p));
    lbl_0000F7BC();
    return *(s32 *)(p + 0x68);
}
#pragma opt_propagation reset
#pragma force_active reset
