/*
 * test_mode.c -- REL module: isolated function lbl_0000F470.
 * This file holds exactly one function so it can be converted from the
 * asm-include below to matching C WITHOUT any asm sibling in the
 * translation unit.  That matters: mwcc's inline assembler turns off the
 * instruction scheduler + peephole optimizer for every C function that
 * shares a TU with an `asm` block, so a schedule-sensitive function only
 * reproduces the original when it sits alone in a pure-C file like this.
 * Keep the Makefile SOURCES order so the .text layout is preserved.
 * Generated by tools/rel_split.py -- regenerate rather than hand-editing.
 */

#include <dolphin.h>
#include "stddef.h"
#include "stdio.h"
#include "stdlib.h"
#include "global.h"
#include "ball.h"
#include "bitmap.h"
#include "camera.h"
#include "event.h"
#include "functions.h"
#include "game.h"
#include "info.h"
#include "input.h"
#include "light.h"
#include "mathutil.h"
#include "mode.h"
#include "mot_ape.h"
#include "polydisp.h"
#include "pool.h"
#include "rend_efc.h"
#include "sound.h"
#include "sprite.h"
#include "stage.h"
#include "thread.h"
#include "variables.h"
#include "window.h"
#include "world.h"
#include "pause_menu.h"
#include "string.h"
#include "avdisp.h"
#include "background.h"
#include "obj_collision.h"
#include "ord_tbl.h"
#include "stcoli.h"
#include "preview.h"
#include "recplay.h"
#include "gxcache.h"
#include "memcard.h"
#include "ranking_screen.h"
#include "vibration.h"
#include "gxutil.h"
#include "perf.h"
#include "course.h"

// Addresses loaded by the code that live in this module's data/rodata/bss
// (defined in asm/test_mode.s) or imported.  Declared so mwcc accepts `@ha/@l`.
extern u8 lbl_0000FE78[];
extern u8 lbl_0000FEC8[];
extern u8 lbl_0000FED0[];
extern u8 lbl_0000FF00[];
extern u8 lbl_0000FF78[];
extern u8 lbl_00010070[];
extern u8 lbl_00010078[];
extern u8 lbl_00010080[];
extern u8 lbl_000100A8[];
extern u8 lbl_000100D8[];
extern u8 lbl_00010118[];
extern u8 lbl_00010124[];
extern u8 lbl_00010148[];
extern u8 lbl_00010150[];
extern u8 lbl_00010170[];
extern u8 lbl_000101B8[];
extern u8 lbl_000101E0[];
extern u8 lbl_000101EC[];
extern u8 lbl_000101FC[];
extern u8 lbl_00010278[];
extern u8 lbl_00010280[];
extern u8 lbl_00010298[];
extern u8 lbl_000102B0[];
extern u8 lbl_00010350[];
extern u8 lbl_00010364[];
extern u8 lbl_000103F4[];
extern u8 lbl_000106B4[];
extern u8 lbl_000109A8[];
extern u8 lbl_00010BEC[];
extern u8 lbl_00012330[];
extern u8 lbl_00012C10[];
extern u8 lbl_00012F7C[];
extern u8 lbl_00013158[];
extern u8 lbl_00013178[];
extern u8 lbl_0001323C[];
extern u8 lbl_0001324C[];
extern u8 lbl_000138AC[];
extern u8 lbl_000138B8[];
extern u8 lbl_00013920[];
extern u8 lbl_00013A1C[];
extern u8 lbl_00014638[];
extern u8 lbl_0001468C[];
extern u8 lbl_0001469C[];
extern u8 lbl_00014714[];
extern u8 lbl_000147EC[];
extern u8 lbl_00014810[];
extern u8 lbl_000148A8[];
extern u8 lbl_000148D8[];
extern u8 lbl_000148E8[];
extern u8 lbl_00014974[];
extern u8 lbl_000155BC[];
extern u8 lbl_000156F0[];
extern u8 lbl_00015868[];
extern u8 lbl_00015890[];
extern u8 lbl_000159EC[];
extern u8 lbl_10000000[];
extern u8 lbl_10000004[];
extern u8 lbl_10000008[];
extern u8 lbl_10000040[];
extern u8 lbl_1000006C[];
extern u8 lbl_100000B4[];
extern u8 lbl_100000B8[];
extern u8 lbl_10000D5C[];
extern u8 lbl_10000D60[];
extern u8 lbl_10000D64[];
extern u8 lbl_10000E00[];
extern u8 lbl_10000F38[];
extern u8 lbl_10000F58[];
extern u8 lbl_10000F5C[];
extern u8 lbl_10000F60[];
extern u8 lbl_10000F70[];
extern u8 lbl_10000FA8[];
extern u8 lbl_10000FAC[];
extern u8 lbl_10003BAC[];
extern u8 lbl_10003BF8[];
extern u8 lbl_10003BFC[];
extern u8 lbl_10003C60[];
extern u8 lbl_10003C80[];
extern u8 bgTypeNames[];
extern u8 dipSwitchNames[];
extern u8 lbl_801C6420[];
extern u8 lbl_801C6470[];
extern u8 lbl_802F0980[];
extern u8 lbl_802F2130[];
extern u8 s_loadedSoundGroupIDs[];
extern u8 spriteTileOffsets[];
extern u8 u_isSoundGroupDataLoaded[];

// Imported functions the code calls that no included header declares.
extern void GXDrawCube();
extern void GXDrawCylinder();
extern void GXPixModeSync();
extern void PSMTXConcat();
extern void PSMTXCopy();
extern void PSMTXInverse();
extern void avdisp_get_eff_vertices();
extern void avdisp_get_eff_vtxinfo();
extern void avdisp_get_matrices();
extern void draw_test_camera_target();
extern void effect_draw();
extern void free_model();
extern void func_80036000();
extern void func_80086D20();
extern void func_8008B9DC();
extern void func_8008BFD8();
extern void func_800948EC();
extern void func_800A71B0();
extern void func_800A722C();
extern void func_800A7314();
extern void func_800A7370();
extern void func_800A7440();
extern void get_font_bitmap_id();
extern void item_draw();
extern void load_model();
extern void mot_ape_8008BAA8();
extern void nl2ngc_draw_model_sort_translucent_alt2();
extern void nlObjModelListFree();
extern void nlObjModelListLoad();
extern void nlObjPut();
extern void set_shape_flags_in_model();
extern void stobj_draw();
extern void u_draw_ball_shadow();
extern void u_load_character_graphics();
extern void u_make_ape_sub();

// Forward declarations so mwcc accepts `<fn>@ha/@l` and cross-function
// branches before each function is defined below.
void _prolog(void);
void _epilog(void);
void _unresolved(void);
void lbl_00000208(void);
void lbl_00000270(void);
void lbl_00000630(void);
void lbl_00000780(void);
void lbl_00000934(void);
void lbl_00001B78(void);
void lbl_00002108(void);
void lbl_0000215C(void);
void lbl_00002760(void);
void lbl_000031B8(void);
void lbl_00003A4C(void);
void lbl_00003C34(void);
void lbl_00003D94(void);
void lbl_000040B4(void);
void lbl_0000502C(void);
void lbl_00005384(void);
void lbl_000055E8(void);
void lbl_000056BC(void);
void lbl_000057C0(void);
void lbl_000065F0(void);
void lbl_00006974(void);
void lbl_000073EC(void);
void lbl_00007BE0(void);
void lbl_00007D20(void);
void lbl_00007FE8(void);
void lbl_00008008(void);
void lbl_00008808(void);
void lbl_0000884C(void);
void lbl_00008ADC(void);
void lbl_00008B00(void);
void lbl_00008B44(void);
void lbl_00008F40(void);
void lbl_00009060(void);
void lbl_00009338(void);
void lbl_000094C0(void);
void lbl_00009560(void);
void lbl_000095F8(void);
void lbl_00009998(void);
void lbl_00009A0C(void);
void lbl_0000A304(void);
void lbl_0000A440(void);
void lbl_0000A78C(void);
void lbl_0000A7DC(void);
void lbl_0000A7E0(void);
void lbl_0000A7E4(void);
void lbl_0000A7FC(void);
void lbl_0000AD30(void);
void lbl_0000ADEC(void);
void lbl_0000ADF0(void);
void lbl_0000AE7C(void);
void lbl_0000AEB8(void);
void lbl_0000AEDC(void);
void lbl_0000B364(void);
void lbl_0000B44C(void);
void lbl_0000B4A0(void);
void lbl_0000B57C(void);
void lbl_0000B6B0(void);
void lbl_0000BE00(void);
void lbl_0000BE94(void);
void lbl_0000BE98(void);
void lbl_0000BEB8(void);
void lbl_0000BFA0(void);
void lbl_0000BFE8(void);
void lbl_0000C00C(void);
void lbl_0000C0B0(void);
void lbl_0000C1B8(void);
void lbl_0000C240(void);
void lbl_0000C260(void);
void lbl_0000C3F0(void);
void lbl_0000C984(void);
void lbl_0000CB0C(void);
void lbl_0000CB10(void);
void lbl_0000CDE0(void);
void lbl_0000D084(void);
void lbl_0000D3C0(void);
void lbl_0000D844(void);
void lbl_0000D9FC(void);
void lbl_0000DB2C(void);
void lbl_0000DC60(void);
void lbl_0000DDA4(void);
void lbl_0000E2E8(void);
void lbl_0000E3E8(void);
void lbl_0000E628(void);
void lbl_0000ECB4(void);
void lbl_0000EEF4(void);
void lbl_0000F6F0(void);
void lbl_0000F7BC(void);
void lbl_0000F940(void);
void lbl_0000FBA8(void);
void lbl_0000FD8C(void);

#pragma force_active on
void lbl_0000F470(int enable)
{
    if (*(void **)lbl_10003C80 != NULL)
        return;
    if (enable == 0)
        return;
    *(void **)lbl_10003C80 = (void *)lbl_0000EEF4;
}
#pragma force_active reset
